Repository kubesphere/kubesphere, pull requests merged in 2019-11, with the labels that each got.

#1290 fix: privilege escalation
  pkg/apiserver/iam/im.go
  pkg/models/iam/im.go
Labels: approved, kind/bug, lgtm, size/S

#1310 fix: delete propagation policy
  pkg/models/iam/am.go
  pkg/models/iam/im.go
  pkg/models/workspaces/workspaces.go
Labels: approved, lgtm, size/S

#1322 refine iam policy rules
  pkg/constants/constants.go
  pkg/controller/workspace/workspace_controller.go
  pkg/models/iam/am.go
Labels: approved, kind/feature, lgtm, size/S

#1327 update app-store screenshot
  README_zh.md
Labels: approved, kind/documentation, lgtm, size/XS

#1333 fix broken link
  CONTRIBUTING.md
Labels: approved, kind/documentation, lgtm, size/S

#1341 refine iam policy rules
  pkg/controller/workspace/workspace_controller.go
  pkg/models/iam/am.go
Labels: approved, kind/bug, lgtm, size/S

#1350 fix slow component status api
  pkg/models/components/components.go
Labels: approved, kind/bug, size/S

#1353 fix slow component status api
  pkg/models/types.go
Labels: approved, kind/bug, size/XS

#1356 refine devops not enable log
  pkg/models/tenant/devops.go
Labels: approved, lgtm, size/XS

#1358 support querying resources without paging
  pkg/server/params/params.go
Labels: approved, kind/feature, lgtm, size/XS

#1361 refine workspaces-manager rules
  pkg/models/iam/am.go
Labels: approved, kind/bug, lgtm, size/S

#1384 fix: redefine prometheus client timeout
  pkg/simple/client/prometheus/prometheus.go
Labels: approved, kind/bug, lgtm, size/XS

#1392 job rerun with resourceVersion
  pkg/apis/operations/v1alpha2/register.go
  pkg/apis/resources/v1alpha2/register.go
  pkg/apiserver/operations/job.go
  pkg/models/workloads/jobs.go
Labels: approved, kind/api-change, kind/bug, lgtm, size/S

#1420 fix terminal resize
  pkg/models/terminal/terminal.go
Labels: approved, kind/bug, lgtm, size/XS

#1418 support node status filter
  pkg/models/resources/nodes.go
  pkg/models/resources/resources.go
Labels: approved, kind/feature, lgtm, size/M

#1434 fix openpitrix resource sort param
  pkg/apiserver/openpitrix/applications.go
  pkg/models/openpitrix/applications.go
  pkg/models/openpitrix/apps.go
  pkg/models/openpitrix/categories.go
  pkg/models/openpitrix/repos.go
Labels: approved, kind/bug, lgtm, size/S

#1465 update readme to 2.1
  README.md
  README_zh.md
Labels: approved, kind/documentation, lgtm, size/L

#1565 fix typo
  pkg/api/logging/v1alpha2/types.go
  pkg/models/devops/project_pipeline.go
  pkg/models/registries/registry_client.go
  pkg/models/registries/token.go
Labels: approved, area/devops, area/logging, kind/documentation, lgtm, size/XS

#1590 change router underlying resource apiversion
  pkg/models/routers/routers.go
  pkg/models/routers/routers_suite_test.go
  pkg/models/routers/routers_test.go
Labels: approved, kind/bug, size/M
