Repository kubesphere/kubesphere, pull requests merged in 2019-09, with the labels that each got.

#688 add Readme for Chinese version, refine Readme-En
  README.md
  README_zh.md
  docs/images/architecture-zh.png
  docs/images/dashboard-zh.png
  docs/images/roadmap-2.0.2-en.png
  docs/images/roadmap-2.0.2-zh.png
Labels: approved, lgtm, size/L

#678 get devops count by username
  pkg/apis/network/v1alpha1/common.go
  pkg/apis/tenant/v1alpha2/register.go
  pkg/apiserver/tenant/tenant.go
  pkg/models/tenant/devops.go
Labels: approved, kind/bug, lgtm, size/M

#643 fix: policy rules cannot be updated during upgrade
  pkg/controller/namespace/namespace_controller.go
Labels: approved, kind/bug, lgtm, size/L

#686 fix: email validation
  pkg/apiserver/iam/im.go
Labels: approved, area/iam, kind/bug, lgtm, size/M

#639 add docker image search api
  go.mod
  go.sum
  pkg/apis/resources/v1alpha2/register.go
  pkg/apiserver/registries/registries.go
  pkg/constants/constants.go
  pkg/models/registries/blob.go
  pkg/models/registries/image.go
  pkg/models/registries/image_type.go
  pkg/models/registries/manifest.go
  pkg/models/registries/manifest_test.go
  pkg/models/registries/registries.go
  pkg/models/registries/registry_client.go
  pkg/models/registries/registry_client_test.go
  pkg/models/registries/token.go
  pkg/models/registries/token_test.go
  tools/cmd/doc-gen/main.go
  vendor/github.com/docker/distribution/.gitignore
  vendor/github.com/docker/distribution/.gometalinter.json
  vendor/github.com/docker/distribution/.mailmap
  vendor/github.com/docker/distribution/.travis.yml
  vendor/github.com/docker/distribution/BUILDING.md
  vendor/github.com/docker/distribution/CONTRIBUTING.md
  vendor/github.com/docker/distribution/Dockerfile
  vendor/github.com/docker/distribution/MAINTAINERS
  vendor/github.com/docker/distribution/Makefile
  vendor/github.com/docker/distribution/README.md
  vendor/github.com/docker/distribution/ROADMAP.md
  vendor/github.com/docker/distribution/blobs.go
  vendor/github.com/docker/distribution/doc.go
  vendor/github.com/docker/distribution/errors.go
  vendor/github.com/docker/distribution/manifest/doc.go
  vendor/github.com/docker/distribution/manifest/schema2/builder.go
  vendor/github.com/docker/distribution/manifest/schema2/manifest.go
  vendor/github.com/docker/distribution/manifest/versioned.go
  vendor/github.com/docker/distribution/manifests.go
  vendor/github.com/docker/distribution/registry.go
  vendor/github.com/docker/distribution/tags.go
  vendor/github.com/docker/distribution/vendor.conf
  vendor/github.com/opencontainers/image-spec/LICENSE
  vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/layout.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
  vendor/github.com/opencontainers/image-spec/specs-go/version.go
  vendor/github.com/opencontainers/image-spec/specs-go/versioned.go
  vendor/modules.txt
Labels: approved, area/api, area/documentation, lgtm, size/XXL

#684 feat: support horizontalpodautoscalers query
  cmd/ks-apiserver/app/server.go
  pkg/models/resources/horizontalpodautoscalers.go
  pkg/models/resources/resources.go
Labels: approved, area/api, kind/feature, lgtm, size/L

#697 do not genereate unused structs
  Makefile
  api/api-rules/violation_exceptions.list
  api/openapi-spec/swagger.json
  cmd/controller-manager/controller-manager.go
  pkg/apis/apis.go
  pkg/apis/devops/v1alpha1/openapi_generated.go
  pkg/apis/devops/v1alpha2/register.go
  pkg/apis/network/v1alpha1/openapi_generated.go
  pkg/apis/servicemesh/v1alpha2/openapi_generated.go
  pkg/apis/tenant/v1alpha1/openapi_generated.go
Labels: approved, lgtm, size/XXL

#700 add dependency scripts
  go.mod
  hack/lint-dependencies.sh
Labels: approved, kind/feature, lgtm, size/M

#693 Add PVC stats API
  pkg/apis/monitoring/v1alpha2/register.go
  pkg/apiserver/monitoring/monitoring.go
  pkg/constants/constants.go
  pkg/models/metrics/metrics.go
  pkg/models/metrics/metricsrule.go
  pkg/models/metrics/metricsruleconst.go
  pkg/simple/client/prometheus/prometheusclient.go
Labels: approved, kind/feature, lgtm, size/L

#708 api do not return 401
  pkg/apiserver/devops/devops.go
Labels: approved, lgtm, size/XS

#692 ✨support calico with k8s storage
  Makefile
  cmd/ks-network/main.go
  kustomize/network/calico-etcd/kustomization.yaml
  kustomize/network/calico-etcd/network.yaml
  kustomize/network/calico-etcd/patch_image_name.yaml
  kustomize/network/calico-etcd/patch_role_binding.yaml
  kustomize/network/calico-etcd/role.yaml
  kustomize/network/calico-etcd/role_binding.yaml
  kustomize/network/calico-k8s/kustomization.yaml
  kustomize/network/calico-k8s/network.yaml
  kustomize/network/calico-k8s/patch_image_name.yaml
  kustomize/network/calico-k8s/patch_role_binding.yaml
  kustomize/network/calico-k8s/role.yaml
  kustomize/network/crds/kustomization.yaml
  pkg/controller/network/provider/calico_k8s.go
  pkg/controller/network/runoption/option.go
  pkg/test/testing.go
  test/network/test.sh
Labels: approved, area/networking, kind/feature, lgtm, size/L

#701 remove unused types and funcs
  pkg/apis/logging/v1alpha2/register.go
  pkg/apiserver/logging/logging.go
  pkg/filter/logging.go
  pkg/models/log/logcrd.go
  pkg/models/log/types.go
Labels: approved, kind/cleanup, lgtm, size/L

#711 ✨add porter-system
  pkg/constants/constants.go
Labels: approved, area/networking, kind/feature, lgtm, size/XS

#720 update check pipeline script & cronjob script
  pkg/apis/devops/v1alpha2/register.go
  pkg/apiserver/devops/devops.go
  pkg/models/devops/devops.go
  pkg/models/devops/devops_test.go
  pkg/models/devops/json.go
  pkg/models/devops/urlconfig.go
Labels: approved, area/devops, kind/api-change, kind/feature, lgtm, size/L

#718 multi branch pipeline trigger
  pkg/models/devops/project_pipeline.go
  pkg/models/devops/project_pipeline_test.go
Labels: approved, area/devops, kind/api-change, lgtm, size/L

#723 add pvc utilisation metrics
  pkg/models/devops/devops.go
  pkg/models/devops/devops_test.go
  pkg/models/metrics/metricsruleconst.go
Labels: approved, kind/feature, lgtm, size/M

#689 refine log search
  pkg/apiserver/logging/logging.go
  pkg/models/log/logcollector.go
  pkg/simple/client/elasticsearch/esclient.go
  pkg/simple/client/elasticsearch/types.go
  pkg/utils/stringutils/string.go
Labels: approved, kind/bug, kind/cleanup, lgtm, size/XXL

#729 add ks-apiserver options
  cmd/ks-apiserver/app/options/options.go
Labels: approved, kind/bug, size/XS

#730 add ks-apiserver options
  pkg/simple/client/redis/options.go
Labels: kind/bug

#731 add ks-apiserver options
  pkg/simple/client/openpitrix/options.go
  pkg/simple/client/prometheus/options.go
Labels: kind/bug

#736 update devops flags default value
  cmd/ks-apiserver/app/server.go
  pkg/simple/client/s2is3/options.go
Labels: approved, lgtm, size/S

#738 add more option comments
  pkg/server/config/config.go
  pkg/simple/client/devops/options.go
  pkg/simple/client/k8s/kubernetes.go
  pkg/simple/client/ldap/options.go
  pkg/simple/client/mysql/options.go
  pkg/simple/client/openpitrix/options.go
  pkg/simple/client/prometheus/options.go
  pkg/simple/client/redis/options.go
  pkg/simple/client/s2is3/options.go
  pkg/simple/client/sonarqube/options.go
Labels: approved, kind/documentation, kind/feature, size/L

#744 Corrected the scripts directory in README files
  README.md
  README_zh.md
Labels: approved, lgtm, size/XS

#739 add expand volume controller
  cmd/controller-manager/app/controllers.go
  pkg/controller/storage/expansion/expansion_controller.go
  pkg/controller/storage/expansion/expansion_controller_test.go
  pkg/controller/storage/expansion/expansion_util.go
Labels: approved, kind/feature, lgtm, size/XL

#751 docker api version negotiation
  go.mod
  go.sum
  pkg/models/registries/registries.go
  vendor/github.com/docker/docker/AUTHORS
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/container/container_changes.go
  vendor/github.com/docker/docker/api/types/container/container_create.go
  vendor/github.com/docker/docker/api/types/container/container_top.go
  vendor/github.com/docker/docker/api/types/container/container_update.go
  vendor/github.com/docker/docker/api/types/container/container_wait.go
  vendor/github.com/docker/docker/api/types/container/host_config.go
  vendor/github.com/docker/docker/api/types/filters/parse.go
  vendor/github.com/docker/docker/api/types/image/image_history.go
  vendor/github.com/docker/docker/api/types/volume/volume_create.go
  vendor/github.com/docker/docker/api/types/volume/volume_list.go
  vendor/github.com/docker/docker/client/client.go
  vendor/github.com/docker/docker/client/hijack.go
  vendor/github.com/docker/docker/client/interface.go
  vendor/github.com/docker/docker/client/options.go
  vendor/github.com/docker/docker/client/ping.go
  vendor/github.com/docker/docker/client/request.go
  vendor/github.com/docker/docker/client/session.go
  vendor/modules.txt
Labels: approved, kind/bug, lgtm, size/L

#753 fix: null pointer exception
  pkg/simple/client/factory.go
Labels: approved, lgtm, size/XS

#754 cleanup glog
  cmd/ks-iam/app/server.go
  go.mod
Labels: approved, kind/cleanup, lgtm, size/XS

#757 refactor logging options
  cmd/ks-apiserver/app/options/options.go
  cmd/ks-apiserver/app/options/validation.go
  cmd/ks-apiserver/app/server.go
  pkg/api/logging/v1alpha2/types.go
  pkg/apis/logging/v1alpha2/register.go
  pkg/apis/tenant/v1alpha2/register.go
  pkg/apiserver/logging/logging.go
  pkg/apiserver/tenant/tenant.go
  pkg/models/log/logcrd.go
  pkg/server/config/config.go
  pkg/server/config/config_test.go
  pkg/simple/client/alerting/options.go
  pkg/simple/client/elasticsearch/esclient.go
  pkg/simple/client/elasticsearch/interface.go
  pkg/simple/client/elasticsearch/options.go
  pkg/simple/client/elasticsearch/versions/v5/elasticsearch.go
  pkg/simple/client/elasticsearch/versions/v6/elasticsearch.go
  pkg/simple/client/elasticsearch/versions/v7/elasticsearch.go
  pkg/simple/client/factory.go
  pkg/simple/client/notification/options.go
Labels: approved, kind/feature, lgtm, size/XL

#759 fix apiserver setup logs
  cmd/ks-apiserver/app/server.go
Labels: approved, kind/bug, size/S

#762 fix cronjob msg parse
  pkg/models/devops/devops.go
  pkg/models/devops/devops_test.go
Labels: approved, area/devops, lgtm, size/S

#765 Remove creating Ceph secret controller
  pkg/controller/namespace/namespace_controller.go
Labels: approved, kind/cleanup, lgtm, size/M

#756 refactor monitor module
  pkg/api/monitoring/v1alpha2/types.go
  pkg/apis/monitoring/v1alpha2/register.go
  pkg/apiserver/monitoring/monitoring.go
  pkg/models/metrics/constants.go
  pkg/models/metrics/metrics.go
  pkg/models/metrics/metrics_rules.go
  pkg/models/metrics/metricsrule.go
  pkg/models/metrics/metricsruleconst.go
  pkg/models/metrics/namespaces.go
  pkg/models/metrics/types.go
  pkg/models/metrics/util.go
  pkg/models/workspaces/workspaces.go
  pkg/simple/client/prometheus/prometheus.go
Labels: approved, kind/api-change, kind/cleanup, lgtm, size/XXL

#766 fix kubesphere gateway bug
  install/ingress-controller/ingress-controller.yaml
  pkg/models/routers/routers.go
Labels: approved, kind/bug, size/S

#772 fix request logs
  pkg/server/filter/logging.go
Labels: approved, kind/bug, size/S

#774 fix: controller error handle function
  pkg/controller/application/application_controller.go
  pkg/controller/destinationrule/destinationrule_controller.go
  pkg/controller/job/job_controller.go
  pkg/controller/virtualservice/virtualservice_controller.go
Labels: approved, kind/bug, lgtm, size/XS

#771 fix: ldap connection pool leak
  pkg/models/iam/im.go
  pkg/simple/client/ldap/ldap.go
Labels: approved, kind/bug, lgtm, size/L

#778 fix config nil error
  cmd/ks-apiserver/app/options/options.go
  cmd/ks-apiserver/app/options/validation.go
  cmd/ks-apiserver/app/server.go
  pkg/simple/client/alerting/options.go
  pkg/simple/client/devops/options.go
  pkg/simple/client/elasticsearch/options.go
  pkg/simple/client/k8s/options.go
  pkg/simple/client/kubesphere/options.go
  pkg/simple/client/ldap/options.go
  pkg/simple/client/mysql/options.go
  pkg/simple/client/notification/options.go
  pkg/simple/client/openpitrix/options.go
  pkg/simple/client/prometheus/options.go
  pkg/simple/client/redis/options.go
  pkg/simple/client/s2is3/options.go
  pkg/simple/client/servicemesh/options.go
  pkg/simple/client/sonarqube/options.go
  pkg/utils/reflectutils/reflect.go
Labels: approved, size/M

#783 update resourceMap
  pkg/models/quotas/quotas.go
Labels: approved, lgtm, size/XS

#785 fix servicemesh options nil bug
  cmd/ks-apiserver/app/server.go
  pkg/server/config/config.go
  pkg/server/config/config_test.go
  pkg/simple/client/alerting/options.go
  pkg/simple/client/devops/options.go
  pkg/simple/client/elasticsearch/options.go
  pkg/simple/client/k8s/options.go
  pkg/simple/client/kubesphere/options.go
  pkg/simple/client/ldap/options.go
  pkg/simple/client/mysql/options.go
  pkg/simple/client/openpitrix/options.go
  pkg/simple/client/prometheus/options.go
  pkg/simple/client/redis/options.go
  pkg/simple/client/s2is3/options.go
  pkg/simple/client/servicemesh/options.go
  pkg/simple/client/sonarqube/options.go
Labels: approved, kind/bug, size/L

#768 feat: allow to export logs
  pkg/api/logging/v1alpha2/types.go
  pkg/apis/logging/v1alpha2/register.go
  pkg/apis/tenant/v1alpha2/register.go
  pkg/apiserver/logging/logging.go
  pkg/apiserver/tenant/tenant.go
  pkg/simple/client/elasticsearch/esclient.go
  pkg/simple/client/elasticsearch/interface.go
  pkg/simple/client/elasticsearch/versions/v5/elasticsearch.go
  pkg/simple/client/elasticsearch/versions/v6/elasticsearch.go
  pkg/simple/client/elasticsearch/versions/v7/elasticsearch.go
  pkg/utils/stringutils/string.go
Labels: approved, kind/api-change, kind/cleanup, kind/feature, lgtm, size/XL

#789 monitor: filter out non-labeled workspace
  pkg/models/metrics/metrics.go
Labels: approved, kind/bug, lgtm, size/XS

#792 refine readme, add more cncf icons and screenshot
  README.md
  README_zh.md
Labels: approved, kind/documentation, lgtm, size/M

#793 default set honarRefspec true
  pkg/models/devops/project_pipeline.go
Labels: approved, lgtm, size/XS

#798 fix typo & regenerate swagger
  api/ks-openapi-spec/swagger.json
  pkg/models/devops/project_pipeline.go
  tools/cmd/doc-gen/main.go
Labels: approved, kind/documentation, lgtm, size/XXL

#799 log: fix elastic version detection
  pkg/simple/client/elasticsearch/esclient.go
  pkg/simple/client/elasticsearch/options.go
  pkg/simple/client/elasticsearch/versions/v5/elasticsearch.go
  pkg/simple/client/elasticsearch/versions/v6/elasticsearch.go
  pkg/simple/client/elasticsearch/versions/v7/elasticsearch.go
Labels: approved, kind/bug, lgtm, size/M

#800 fix apigateway clientset bug
  cmd/hypersphere/hypersphere.go
  cmd/ks-apigateway/apiserver.go
  cmd/ks-apigateway/app/server.go
Labels: approved, kind/bug, size/M

#801 fix apigateway clientset bug
  cmd/ks-apigateway/app/server.go
Labels: kind/bug

#802 fix hypersphere apis installation
  cmd/ks-apiserver/apiserver.go
  cmd/ks-apiserver/app/server.go
Labels: approved, kind/bug, size/S

#809 update s2i download url
  pkg/models/devops/s2ibinary_handler.go
Labels: approved, lgtm, size/XS

#814 fix hypersphere apis installation
  cmd/ks-apigateway/apiserver.go
  cmd/ks-apigateway/app/server.go
  cmd/ks-apiserver/app/server.go
  cmd/ks-iam/apiserver.go
  cmd/ks-iam/app/server.go
  pkg/apigateway/caddy-plugin/authenticate/auto_load.go
  pkg/apigateway/caddy-plugin/authentication/auto_load.go
  pkg/apigateway/caddy-plugin/swagger/auto_load.go
  pkg/apigateway/plugins.go
  pkg/apis/kapis.go
Labels: approved, kind/bug, kind/feature, size/L

#813 log: fix crash if api caller has no access to provided namespaces
  pkg/apiserver/tenant/tenant.go
Labels: approved, kind/bug, lgtm, size/XS

#816 fix stripping config options
  pkg/server/config/config.go
  pkg/simple/client/openpitrix/options.go
Labels: approved, kind/bug, size/S

#815 parse 401 err, change code to 428
  pkg/apiserver/devops/devops.go
Labels: approved, lgtm, size/S

#818 fix pipeline input support any type
  pkg/models/devops/json.go
Labels: approved, area/devops, kind/bug, lgtm, size/XS

#821 format
  pkg/models/devops/json.go
Labels: approved, kind/cleanup, lgtm, size/XS

#811 fix: filter app template in built-in repo
  pkg/apiserver/openpitrix/categories.go
  pkg/controller/namespace/namespace_controller.go
  pkg/models/openpitrix/apps.go
Labels: approved, kind/bug, lgtm, size/S

#831 metrics: add missing placeholder
  pkg/models/metrics/metrics_rules.go
Labels: approved, kind/bug, lgtm, size/XS

#830 skip informer creating when corresponding crd not exists
  cmd/ks-apiserver/app/server.go
  pkg/simple/client/k8s/kubernetes.go
Labels: approved, kind/bug, size/M

#841 log: cleanup es client options
  pkg/server/config/config_test.go
  pkg/simple/client/elasticsearch/esclient.go
  pkg/simple/client/elasticsearch/options.go
Labels: approved, kind/cleanup, lgtm, size/M

#836 fix: filter pod by service name
  pkg/models/resources/pods.go
Labels: approved, lgtm, size/XS
