Repository kubesphere/kubesphere, pull requests merged in 2019-10, with the labels that each got.

#835 clean up s2ibinary
  pkg/controller/s2irun/s2irun_controller.go
Labels: approved, lgtm, size/M

#876 remove useless logs
  pkg/controller/clusterrolebinding/clusterrolebinding_controller.go
  pkg/controller/namespace/namespace_controller.go
Labels: approved, kind/cleanup, lgtm, size/S

#881 input omitempty
  pkg/models/devops/json.go
Labels: approved, lgtm, size/S

#878 update iam policy
  pkg/controller/workspace/workspace_controller.go
  pkg/models/iam/am.go
Labels: approved, kind/api-change, lgtm, size/M

#888 strip senstive information
  pkg/server/config/config.go
Labels: approved, size/M

#889 refine annotation key
  pkg/constants/constants.go
Labels: approved, kind/api-change, lgtm, size/XS

#896 修正source to image 链接404的问题
  README_zh.md
Labels: approved, kind/documentation, lgtm, size/XS

#894 update namespace operator policy rules
  pkg/controller/namespace/namespace_controller.go
Labels: approved, kind/bug, lgtm, size/XS

#918 fix controller manager bug
  cmd/controller-manager/app/server.go
Labels: approved, kind/bug, size/S

#903 fix: return early when err is nil
  pkg/controller/namespace/namespace_controller.go
Labels: approved, kind/bug, lgtm, size/XS

#919 fix missing scheme in kubeconfig
  pkg/simple/client/k8s/kubernetes.go
Labels: approved, area/apiserver, kind/bug, lgtm, size/XS

#944 do not set content md5 manually
  pkg/models/devops/s2ibinary_handler.go
Labels: approved, lgtm, size/XS

#938 refine clusterrolebinding controller
  pkg/controller/clusterrolebinding/clusterrolebinding_controller.go
Labels: approved, lgtm, size/S

#946 remove log highlighting
  pkg/api/logging/v1alpha2/types.go
  pkg/simple/client/elasticsearch/esclient.go
Labels: approved, kind/cleanup, lgtm, size/M

#990 fix github webhook Content type support
  pkg/apis/devops/v1alpha2/register.go
Labels: approved, area/devops, kind/bug, lgtm, size/XS

#991 fix: add missing parameter
  pkg/apiserver/openpitrix/apps.go
  pkg/models/openpitrix/apps.go
  pkg/models/openpitrix/types.go
Labels: approved, kind/bug, lgtm, size/S

#1004 update devops flyway image for arm
  pkg/db/Dockerfile
Labels: approved, lgtm, size/XS

#1005 fix crash when monitoring component is disabled
  pkg/models/metrics/namespaces.go
  pkg/models/metrics/util.go
Labels: approved, kind/bug, lgtm, size/XS

#1063 change download log file type to plain text explictly
  pkg/apis/logging/v1alpha2/register.go
  pkg/apis/tenant/v1alpha2/register.go
  pkg/apiserver/logging/logging.go
  pkg/apiserver/tenant/tenant.go
Labels: approved, kind/cleanup, lgtm, size/S

#1065 monitor: no need to produce error when devops is disabled
  pkg/models/metrics/metrics.go
  pkg/models/workspaces/workspaces.go
Labels: approved, kind/cleanup, lgtm, size/S

#1038 fix: sort deployment by last update time
  pkg/models/resources/deployments.go
  pkg/models/resources/pods.go
  pkg/models/resources/resources.go
Labels: approved, kind/bug, lgtm, size/S

#1073 refine es error format
  pkg/simple/client/elasticsearch/esclient.go
  pkg/simple/client/elasticsearch/versions/v5/elasticsearch.go
  pkg/simple/client/elasticsearch/versions/v6/elasticsearch.go
  pkg/simple/client/elasticsearch/versions/v7/elasticsearch.go
Labels: approved, kind/cleanup, lgtm, size/XS

#1068 feat: support app.k8s.io applications paging query
  cmd/ks-apiserver/app/server.go
  pkg/informers/informers.go
  pkg/models/resources/appplications.go
  pkg/models/resources/resources.go
  pkg/simple/client/k8s/kubernetes.go
Labels: approved, kind/api-change, kind/feature, lgtm, size/L

#607 feat: token management
  cmd/ks-iam/app/options/options.go
  cmd/ks-iam/app/server.go
  pkg/apigateway/caddy-plugin/authenticate/authenticate.go
  pkg/apigateway/caddy-plugin/authenticate/auto_load.go
  pkg/apis/iam/v1alpha2/register.go
  pkg/apiserver/iam/auth.go
  pkg/models/iam/im.go
  pkg/models/types.go
  pkg/server/config/config.go
  pkg/server/config/config_test.go
  pkg/simple/client/factory.go
  pkg/simple/client/redis/options.go
  pkg/simple/client/redis/redis.go
Labels: approved, area/iam, kind/feature, lgtm, size/XL

#1095 refine policy rules
  pkg/controller/namespace/namespace_controller.go
Labels: approved, kind/bug, lgtm, size/XS

#1104 fix: null pointer exception
  pkg/apigateway/caddy-plugin/authenticate/authenticate.go
  pkg/apigateway/caddy-plugin/authenticate/auto_load.go
Labels: approved, kind/bug, lgtm, size/M

#1109 support application sorting
  pkg/apiserver/openpitrix/applications.go
  pkg/apiserver/openpitrix/apps.go
  pkg/models/openpitrix/applications.go
Labels: approved, kind/bug, lgtm, size/S

#1111 feat: support user-facing role filter
  pkg/models/resources/clusterroles.go
  pkg/models/resources/resources.go
  pkg/models/resources/roles.go
Labels: approved, kind/api-change, kind/feature, lgtm, size/S

#1159 fix: allow workspace-viewer view audits log
  pkg/controller/workspace/workspace_controller.go
Labels: approved, kind/bug, lgtm, size/XS

#1169 fix: deployed instances counting error
  pkg/apiserver/openpitrix/apps.go
Labels: approved, kind/bug, lgtm, size/XS

#1170 add metric namespace_configmap_count
  pkg/models/metrics/metrics_rules.go
Labels: approved, kind/design, lgtm, size/XS

#1181 fix: do not delete devops project when devops is not enabled
  pkg/controller/workspace/workspace_controller.go
Labels: approved, lgtm, size/XS

#1199 fix set sonarqube options
  cmd/ks-apiserver/app/server.go
Labels: approved, kind/bug, lgtm, size/XS

#1213 improve path exclusion rule
  pkg/apigateway/caddy-plugin/authenticate/authenticate.go
  pkg/apigateway/caddy-plugin/authenticate/auto_load.go
  pkg/apigateway/caddy-plugin/authentication/authentication.go
  pkg/apigateway/caddy-plugin/authentication/auto_load.go
  pkg/apigateway/caddy-plugin/internal/exclusion_rule.go
Labels: approved, kind/feature, lgtm, size/M

#1250 add back metric workload_memory_usage
  pkg/models/metrics/metrics_rules.go
Labels: approved, kind/cleanup, lgtm, size/XS
