Repository kubesphere/kubesphere, pull requests merged in 2019-12, with the labels that each got.

#1625 kubesphere-add-default-param
  pkg/apiserver/resources/resources.go
  pkg/server/params/params.go
Labels: approved, kind/cleanup, lgtm, size/S

#1551 contributing guide
  CONTRIBUTING.md
  Makefile
  README.md
  README_zh.md
  docs/design/README.md
  docs/design/arch.dot
  docs/en/concepts-and-designs/README.md
  docs/en/concepts-and-designs/overview.md
  docs/en/guides/Development-workflow.md
  docs/en/guides/How-to-build.md
  docs/en/guides/How-to-connect-remote-service.md
  docs/en/guides/How-to-run-KubeSphere-core.md
  docs/en/guides/README.md
  docs/en/guides/code-of-conduct.md
  docs/en/guides/pull-requests.md
  docs/en/guides/screenshots.md
  docs/prereqs.md
  docs/welcome-to-KubeSphere-new-developer-guide.md
Labels: approved, kind/cleanup, lgtm, size/XL

#1622 add KubeSphere CLA
  README.md
  README_zh.md
  docs/cla.md
Labels: approved, kind/documentation, lgtm, size/M

#1626 modified the resources
  pkg/models/resources/resources.go
Labels: approved, lgtm, size/S

#1651 remove dependency on kubernetes repo
  cmd/controller-manager/app/options/options.go
  go.mod
  go.sum
  hack/pin-dependency.sh
  pkg/controller/application/application_controller.go
  pkg/controller/destinationrule/destinationrule_controller.go
  pkg/controller/job/job_controller.go
  pkg/controller/s2ibinary/s2ibinary_controller.go
  pkg/controller/s2irun/s2irun_controller.go
  pkg/controller/virtualservice/virtualservice_controller.go
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/pkg/client/leaderelectionconfig/BUILD
  vendor/k8s.io/kubernetes/pkg/client/leaderelectionconfig/config.go
  vendor/k8s.io/kubernetes/pkg/util/metrics/BUILD
  vendor/k8s.io/kubernetes/pkg/util/metrics/util.go
  vendor/modules.txt
  vendor/openpitrix.io/openpitrix/pkg/client/access/client.go
  vendor/openpitrix.io/openpitrix/pkg/client/account/client.go
  vendor/openpitrix.io/openpitrix/pkg/client/client.go
Labels: approved, kind/cleanup, size/XL

#1659 fix jenkins request func parameters
  pkg/gojenkins/request.go
Labels: approved, area/devops, kind/bug, lgtm, size/S

#1679 Update Readme
  README.md
Labels: approved, area/documentation, kind/documentation, lgtm, size/M

#1691 add powered-by-kubesphere.md
  README.md
  docs/powered-by-kubesphere.md
Labels: approved, kind/documentation, lgtm, size/S
