Repository kubesphere/kubesphere, pull requests merged in 2019-07, with the labels that each got.

#602 Update code-of-conduct.md
  docs/code-of-conduct.md
Labels: approved, lgtm

#612 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#608 🌟 add support of workspace networkpolicy
  .gitignore
  .travis.yml
  Makefile
  config/crds/network.kubesphere.io_workspacenetworkpolicies.yaml
  go.mod
  go.sum
  hack/generate_client.sh
  hack/generate_group.sh
  pkg/apis/addtoscheme_network_v1alpha1.go
  pkg/apis/network/group.go
  pkg/apis/network/v1alpha1/doc.go
  pkg/apis/network/v1alpha1/register.go
  pkg/apis/network/v1alpha1/v1alpha1_suite_test.go
  pkg/apis/network/v1alpha1/workspacenetworkpolicy_types.go
  pkg/apis/network/v1alpha1/workspacenetworkpolicy_types_test.go
  pkg/apis/network/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/servicemesh/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/tenant/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/network/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/network/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/network/v1alpha1/fake/fake_network_client.go
  pkg/client/clientset/versioned/typed/network/v1alpha1/fake/fake_workspacenetworkpolicy.go
  pkg/client/clientset/versioned/typed/network/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/network/v1alpha1/network_client.go
  pkg/client/clientset/versioned/typed/network/v1alpha1/workspacenetworkpolicy.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/network/interface.go
  pkg/client/informers/externalversions/network/v1alpha1/interface.go
  pkg/client/informers/externalversions/network/v1alpha1/workspacenetworkpolicy.go
  pkg/client/listers/network/v1alpha1/expansion_generated.go
  pkg/client/listers/network/v1alpha1/workspacenetworkpolicy.go
  pkg/controller/network/testing/controller.go
  pkg/controller/network/testing/util.go
  pkg/controller/network/wsnetworkpolicy/controller.go
  pkg/controller/network/wsnetworkpolicy/reconcile.go
  pkg/controller/network/wsnetworkpolicy/wsnetworkpolicy_suite_test.go
  pkg/controller/network/wsnetworkpolicy/wsnetworkpolicy_test.go
Labels: approved, area/networking, lgtm, size/XXL

#613 Update README
  README.md
Labels: approved, lgtm, size/XS

#614 📄 add networking owners
  pkg/apis/network/OWNERS
  pkg/controller/network/OWNERS
Labels: approved, lgtm, size/S
