Repository kubesphere/kubesphere, pull requests merged in 2019-08, with the labels that each got.

#617 fix internal issue #1131
  pkg/models/devops/json.go
Labels: approved, area/devops, lgtm, size/XS

#603 Contribution guide
  CONTRIBUTING.md
  README.md
  build/ks-apigateway/Dockerfile
  build/ks-apiserver/Dockerfile
  build/ks-controller-manager/Dockerfile
  build/ks-iam/Dockerfile
  hack/docker_build.sh
Labels: approved, area/documentation, lgtm, size/M

#620 add devops owners
  pkg/apis/devops/OWNERS
  pkg/apiserver/devops/OWNERS
  pkg/gojenkins/OWNERS
  pkg/models/devops/OWNERS
  pkg/models/git/OWNERS
  pkg/simple/client/devops_mysql/OWNERS
  pkg/simple/client/sonarqube/OWNERS
Labels: approved, lgtm, size/M

#635 add architecture diagram and installation command record
  README.md
Labels: approved, lgtm, size/S

#636 fix pod quota metrics
  pkg/models/metrics/metricsruleconst.go
Labels: approved, kind/bug, lgtm, size/XS

#627 update s2i version
  api/openapi-spec/swagger.json
  go.mod
  go.sum
  vendor/github.com/kubesphere/s2ioperator/pkg/apis/devops/v1alpha1/openapi_generated.go
  vendor/github.com/kubesphere/s2ioperator/pkg/apis/devops/v1alpha1/s2ibuilder_types.go
  vendor/github.com/kubesphere/s2ioperator/pkg/apis/devops/v1alpha1/s2ibuildertemplate_types.go
  vendor/github.com/kubesphere/s2ioperator/pkg/apis/devops/v1alpha1/s2irun_types.go
  vendor/github.com/kubesphere/s2ioperator/pkg/apis/devops/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, size/L

#649 fix: mistakenly delete workspace role binding
  pkg/models/iam/im.go
Labels: approved, kind/bug, lgtm, size/S

#621 support empty label filter
  pkg/models/resources/clusterroles.go
  pkg/models/resources/configmaps.go
  pkg/models/resources/cronjobs.go
  pkg/models/resources/daemonsets.go
  pkg/models/resources/deployments.go
  pkg/models/resources/ingresses.go
  pkg/models/resources/jobs.go
  pkg/models/resources/namespaces.go
  pkg/models/resources/nodes.go
  pkg/models/resources/persistentvolumeclaims.go
  pkg/models/resources/pods.go
  pkg/models/resources/resources.go
  pkg/models/resources/roles.go
  pkg/models/resources/s2ibuilder.go
  pkg/models/resources/s2ibuildertemplate.go
  pkg/models/resources/s2irun.go
  pkg/models/resources/secrets.go
  pkg/models/resources/services.go
  pkg/models/resources/statefulsets.go
  pkg/models/resources/storageclasses.go
  pkg/models/resources/workspaces.go
  pkg/models/tenant/namespaces.go
  pkg/models/tenant/workspaces.go
  pkg/params/params.go
Labels: approved, area/apiserver, lgtm, size/L

#667 fix: recycle ldap connections in pool
  pkg/models/iam/im.go
Labels: approved, kind/bug, lgtm, size/XS

#670 Pipeline Support Bitbucket Scm
  pkg/apis/devops/v1alpha2/register.go
  pkg/apiserver/devops/devops.go
  pkg/models/devops/devops.go
  pkg/models/devops/json.go
  pkg/models/devops/project_pipeline.go
  pkg/models/devops/project_pipeline_test.go
  pkg/models/devops/urlconfig.go
Labels: approved, area/devops, kind/feature, lgtm, size/XXL

#679 create scm servers always return match server
  pkg/models/devops/devops.go
Labels: approved, area/devops, lgtm, size/S
