Repository kubesphere/kubesphere, pull requests merged in 2020-11, with the labels that each got.

#3050 Fix the out-of-date slack invitation link in the issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/installation_failure.md
Labels: approved, dco-signoff: no, kind/documentation, lgtm, size/S

#3016 chore: fix typing error
  pkg/apis/devops/v1alpha1/s2ibuilder_types.go
Labels: approved, dco-signoff: yes, kind/flake, lgtm, size/XS

#3046 fix: adapt to different parameter types for pipeline
  pkg/simple/client/devops/pipeline.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/XS

#3002 Add node metric: node_pleg_quantile
  pkg/models/monitoring/named_metrics.go
  pkg/simple/client/monitoring/prometheus/promql.go
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/XS

#3069 minor cleanup
  pkg/kapis/monitoring/group.go
  pkg/models/monitoring/monitoring.go
  pkg/models/monitoring/namespaces.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M

#3087 fix issue #3086
  cmd/ks-apiserver/app/server.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#3045 kiali k8s client support out-cluster
  cmd/ks-apiserver/app/server.go
  go.mod
  go.sum
  vendor/github.com/kiali/kiali/handlers/utils.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/M

#3032 feat: add group and groupbinding controller
  cmd/controller-manager/app/controllers.go
  pkg/apis/iam/v1alpha2/group_test.go
  pkg/apis/iam/v1alpha2/groupbinding_test.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/authentication/authenticators/basic/basic.go
  pkg/apiserver/authentication/authenticators/jwttoken/jwt_token.go
  pkg/apiserver/authorization/authorizerfactory/rbac.go
  pkg/controller/group/group_controller.go
  pkg/controller/group/group_controller_test.go
  pkg/controller/groupbinding/groupbinding_controller.go
  pkg/controller/groupbinding/groupbinding_controller_test.go
  pkg/controller/user/user_controller.go
  pkg/kapis/iam/v1alpha2/handler.go
  pkg/models/iam/am/am.go
  pkg/models/iam/im/authenticator.go
  pkg/models/tenant/devops.go
  pkg/models/tenant/tenant.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XXL

#3073 feat: group auth, add group & groupbinding api
  pkg/apis/iam/v1alpha2/groupbinding_types.go
  pkg/apiserver/apiserver.go
  pkg/kapis/iam/v1alpha2/handler.go
  pkg/kapis/iam/v1alpha2/register.go
  pkg/models/iam/group/group.go
  pkg/models/resources/v1alpha3/group/group.go
  pkg/models/resources/v1alpha3/group/group_test.go
  pkg/models/resources/v1alpha3/groupbinding/groupbinding.go
  pkg/models/resources/v1alpha3/groupbinding/groupbinding_test.go
  pkg/models/resources/v1alpha3/resource/resource.go
  tools/cmd/doc-gen/main.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XL

#3104 Make the issues template can keep comment section
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#3109 fix e2e build issue
  Makefile
  test/e2e/e2e_test.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#3118 Feat: support runnig ks-controller-manager without ldap option
  cmd/controller-manager/app/server.go
  pkg/apiserver/authentication/authenticators/jwttoken/jwt_token.go
  pkg/controller/user/user_controller.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/S

#3042 Fix container terminal security risk
  pkg/apiserver/apiserver.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/kapis/terminal/v1alpha2/register.go
  pkg/models/tenant/tenant.go
  pkg/models/tenant/tenent_test.go
  tools/cmd/doc-gen/main.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#3120 Feat: support runnig ks-apiserver without redis option && change log level
  cmd/controller-manager/app/server.go
  cmd/ks-apiserver/app/options/options.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/S

#3080 Add param WeaveScopeHost
  pkg/apiserver/apiserver.go
  pkg/apiserver/config/config_test.go
  pkg/kapis/network/v1alpha2/handler.go
  pkg/simple/client/network/options.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3121 Fix the errors found by go vet
  pkg/controller/storage/expansion/expansion_controller_test.go
  pkg/models/registries/blob.go
  pkg/models/registries/manifest.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#3113 fix: private key not match public key
  pkg/controller/certificatesigningrequest/certificatesigningrequest_controller.go
  pkg/models/kubeconfig/kubeconfig.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#3098 fix: cascade delete resources
  pkg/controller/namespace/namespace_controller.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#3136 bugfix: multi-cluster-status-condition
  pkg/controller/cluster/cluster_controller.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#3127 add rolebinding api
  pkg/kapis/iam/v1alpha2/handler.go
  pkg/kapis/iam/v1alpha2/register.go
  pkg/models/iam/am/am.go
  pkg/models/iam/group/group.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/L

#3139 improve LDAP identity provider
  pkg/apiserver/authentication/identityprovider/ldap_provider.go
  pkg/apiserver/authentication/identityprovider/ldap_provider_test.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/L

#3138 refactor controllers
  pkg/controller/group/group_controller.go
  pkg/controller/group/group_controller_test.go
  pkg/controller/groupbinding/groupbinding_controller.go
  pkg/controller/groupbinding/groupbinding_controller_test.go
  pkg/controller/utils/controller/basecontroller.go
  pkg/controller/utils/controller/basecontroller_test.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/L

#3125 Add support discover tags for multi-branch pipeline
  api/api-rules/violation_exceptions.list
  api/ks-openapi-spec/swagger.json
  config/crds/devops.kubesphere.io_pipelines.yaml
  pkg/apis/devops/v1alpha3/pipeline_types.go
  pkg/apis/devops/v1alpha3/zz_generated.deepcopy.go
  pkg/controller/pipeline/pipeline_controller.go
  pkg/simple/client/devops/jenkins/pipeline_internal.go
Labels: approved, area/devops, dco-signoff: yes, kind/feature, lgtm, size/XL

#3126 feature: add sync state for devops
  .gitignore
  pkg/apis/devops/v1alpha3/credential_types.go
  pkg/apis/devops/v1alpha3/devopsproject_types.go
  pkg/apis/devops/v1alpha3/pipeline_types.go
  pkg/controller/devopscredential/devopscredential_controller.go
  pkg/controller/devopscredential/devopscredential_controller_test.go
  pkg/controller/devopsproject/devopsproject_controller.go
  pkg/controller/devopsproject/devopsproject_controller_test.go
  pkg/controller/pipeline/pipeline_controller.go
  pkg/controller/pipeline/pipeline_controller_test.go
  pkg/models/devops/common.go
  pkg/models/devops/devops.go
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/L

#3141 Adding a feature request issue template
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#3144 fix makefile build on mac
  hack/gobuild.sh
Labels: approved, dco-signoff: yes, kind/bug, size/XS

#3147 Fix panic against with pipeline-multibranch-defaults-plugin
  pkg/simple/client/devops/jenkins/pipeline_internal.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/XS

#3129 Avoid docker login everytime even it is done before
  Makefile
  hack/docker_build.sh
  install/scripts/docker_push
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S
