Repository kubesphere/kubesphere, pull requests merged in 2020-10, with the labels that each got.

#2935 fix: upgrade credential
  pkg/models/devops/devops.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2980 add status deleting of volumesnapshot
  pkg/models/resources/v1alpha3/volumesnapshot/volumesnapshot.go
  pkg/models/resources/v1alpha3/volumesnapshot/volumesnapshot_test.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3004 fmt
  pkg/models/resources/v1alpha3/volumesnapshot/volumesnapshot.go
Labels: dco-signoff: yes, kind/cleanup, size/XS

#3003 Fix for issue #2832
  pkg/kapis/openpitrix/v1/handler.go
Labels: approved, dco-signoff: no, lgtm, size/XS

#2997 support aliyun idaas oauth login
  pkg/apiserver/authentication/identityprovider/aliyunidaas/idaas.go
  pkg/apiserver/authentication/oauth/oauth_options.go
  pkg/apiserver/authentication/options/authenticate_options.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/L

#3014 fix application status
  pkg/controller/application/application_controller.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#3021 skip reconcile cluster if not join federation
  pkg/controller/cluster/cluster_controller.go
Labels: approved, dco-signoff: yes, kind/bug, size/XS

#3023 feat: group authorization
  config/crds/iam.kubesphere.io_groupbindings.yaml
  config/crds/iam.kubesphere.io_groups.yaml
  config/samples/iam_v1alpha2_group.yaml
  config/samples/iam_v1alpha2_groupbinding.yaml
  config/samples/iam_v1alpha2_rolebindings.yaml
  pkg/apis/iam/v1alpha2/group_types.go
  pkg/apis/iam/v1alpha2/groupbinding_types.go
  pkg/apis/iam/v1alpha2/register.go
  pkg/apis/iam/v1alpha2/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/iam/v1alpha2/fake/fake_group.go
  pkg/client/clientset/versioned/typed/iam/v1alpha2/fake/fake_groupbinding.go
  pkg/client/clientset/versioned/typed/iam/v1alpha2/fake/fake_iam_client.go
  pkg/client/clientset/versioned/typed/iam/v1alpha2/generated_expansion.go
  pkg/client/clientset/versioned/typed/iam/v1alpha2/group.go
  pkg/client/clientset/versioned/typed/iam/v1alpha2/groupbinding.go
  pkg/client/clientset/versioned/typed/iam/v1alpha2/iam_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/iam/v1alpha2/group.go
  pkg/client/informers/externalversions/iam/v1alpha2/groupbinding.go
  pkg/client/informers/externalversions/iam/v1alpha2/interface.go
  pkg/client/listers/iam/v1alpha2/expansion_generated.go
  pkg/client/listers/iam/v1alpha2/group.go
  pkg/client/listers/iam/v1alpha2/groupbinding.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#3029 refine api docs
  api/ks-openapi-spec/swagger.json
  go.mod
  go.sum
  pkg/constants/constants.go
  pkg/kapis/cluster/v1alpha1/register.go
  pkg/kapis/devops/v1alpha2/register.go
  pkg/kapis/iam/v1alpha2/register.go
  pkg/kapis/oauth/register.go
  pkg/kapis/openpitrix/v1/register.go
  pkg/kapis/resources/v1alpha2/register.go
  pkg/kapis/tenant/v1alpha2/register.go
  tools/cmd/doc-gen/main.go
  vendor/github.com/emicklei/go-restful-openapi/CHANGES.md
  vendor/github.com/emicklei/go-restful-openapi/README.md
  vendor/github.com/emicklei/go-restful-openapi/build_path.go
  vendor/github.com/emicklei/go-restful-openapi/config.go
  vendor/github.com/emicklei/go-restful-openapi/definition_builder.go
  vendor/github.com/emicklei/go-restful-openapi/go.mod
  vendor/github.com/emicklei/go-restful-openapi/go.sum
  vendor/github.com/emicklei/go-restful-openapi/spec_resource.go
  vendor/github.com/emicklei/go-restful/.gitignore
  vendor/github.com/emicklei/go-restful/.travis.yml
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/Makefile
  vendor/github.com/emicklei/go-restful/README.md
  vendor/github.com/emicklei/go-restful/container.go
  vendor/github.com/emicklei/go-restful/curly.go
  vendor/github.com/emicklei/go-restful/custom_verb.go
  vendor/github.com/emicklei/go-restful/jsr311.go
  vendor/github.com/emicklei/go-restful/path_processor.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/github.com/emicklei/go-restful/route_builder.go
  vendor/github.com/emicklei/go-restful/service_error.go
  vendor/github.com/emicklei/go-restful/web_service.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/cleanup, kind/documentation, lgtm, size/XXL

#3039 fix dead links in readme
  README.md
Labels: dco-signoff: yes, kind/documentation, size/S
