Repository kubesphere/kubesphere, pull requests merged in 2020-02, with the labels that each got.

#1804 update issue template to emphasize English only
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/installation_failure.md
Labels: approved, kind/documentation, lgtm, size/M

#1817 fix: in cluster kubeconfig CA data is empty
  pkg/models/kubeconfig/kubeconfig.go
Labels: approved, kind/bug, lgtm, size/S

#1819 update container metrics
  pkg/apis/monitoring/v1alpha2/register.go
  pkg/models/metrics/metrics.go
  pkg/models/metrics/metrics_rules.go
Labels: approved, kind/cleanup, lgtm, size/M

#1812 validate pipeline config
  pkg/apiserver/devops/project_pipeline.go
  pkg/models/devops/project_pipeline_handler.go
  pkg/models/devops/project_pipeline_test.go
Labels: approved, area/devops, kind/bug, lgtm, size/L

#1821 fix: cease cluster
  pkg/models/openpitrix/applications.go
Labels: approved, kind/bug, lgtm, size/XS

#1826 create & update credential use form
  pkg/gojenkins/jenkins.go
Labels: approved, area/devops, kind/bug, lgtm, size/S

#1828 push image on branch release 2.1
  .travis.yml
  hack/docker_build.sh
Labels: approved, lgtm, size/S

#1833 fix: use constants
  pkg/apiserver/openpitrix/apps.go
  pkg/models/openpitrix/repos.go
  pkg/models/openpitrix/types.go
Labels: approved, kind/bug, lgtm, size/XS

#1823 fix doc-gen conflict
  pkg/models/metrics/metrics_rules.go
Labels: approved, kind/bug, lgtm, size/XS

#1831 verify secret
  pkg/models/registries/image_type.go
  pkg/models/registries/registries.go
  pkg/models/registries/registries_test.go
Labels: approved, lgtm, size/M

#1839 update secret verify
  pkg/models/registries/registries.go
  pkg/models/registries/registries_test.go
Labels: approved, kind/bug, lgtm, size/S

#1836 fix: remove owner reference when unbind workspace
  pkg/controller/namespace/namespace_controller.go
  pkg/models/workspaces/workspaces.go
Labels: approved, kind/bug, lgtm, size/M

#1850 fix: workspaces-manager cannot be overwrite
  pkg/models/iam/am.go
Labels: approved, kind/bug, lgtm, size/S

#1853 Update powered-by-kubesphere.md
  docs/powered-by-kubesphere.md
Labels: approved, kind/documentation, size/XS

#1860 bump kiali version
  go.mod
Labels: approved, kind/bug, size/XS

#1846 fix: create context with owner path
  pkg/simple/client/openpitrix/openpitrixclient.go
Labels: approved, kind/bug, lgtm, size/XS

#1848 fix: verify old password if it's defined
  pkg/apiserver/iam/im.go
Labels: approved, lgtm, size/S

#1852 fix: delete login logs when account is deleted
  pkg/models/iam/im.go
Labels: approved, kind/bug, lgtm, size/S

#1857 update builtin metrics
  pkg/models/metrics/metrics_rules.go
Labels: approved, kind/cleanup, lgtm, size/XS

#1875 fix: default reverse param always false
  pkg/apiserver/iam/am.go
  pkg/apiserver/iam/im.go
  pkg/apiserver/openpitrix/applications.go
  pkg/apiserver/openpitrix/apps.go
  pkg/apiserver/openpitrix/categories.go
  pkg/apiserver/openpitrix/repos.go
  pkg/apiserver/resources/resources.go
  pkg/apiserver/tenant/tenant.go
Labels: approved, kind/bug, lgtm, size/S

#1908 fix: use constants
  pkg/apiserver/openpitrix/apps.go
  pkg/apiserver/openpitrix/categories.go
Labels: approved, kind/bug, lgtm, size/XS

#1920 fix: role binding change
  pkg/controller/clusterrolebinding/clusterrolebinding_controller.go
  pkg/controller/namespace/namespace_controller.go
  pkg/models/iam/am.go
Labels: approved, kind/bug, lgtm, size/L

#1894 Devops refactor
  pkg/apiserver/tenant/tenant.go
  pkg/kapis/devops/v1alpha2/handler.go
  pkg/kapis/devops/v1alpha2/member.go
  pkg/kapis/devops/v1alpha2/pipeline_sonar.go
  pkg/kapis/devops/v1alpha2/register.go
Labels: size/XXL

#1786 code refactor
  cmd/controller-manager/app/options/options.go
  cmd/ks-apiserver/app/options/options.go
  cmd/ks-apiserver/app/server.go
  cmd/ks-iam/app/options/options.go
  go.mod
  pkg/api/iam/v1alpha2/types.go
  pkg/apiserver/iam/am.go
  pkg/apiserver/iam/auth.go
  pkg/apiserver/iam/groups.go
  pkg/apiserver/iam/im.go
  pkg/apiserver/iam/types.go
  pkg/apiserver/iam/workspaces.go
  pkg/kapis/iam/v1alpha2/handler.go
  pkg/kapis/iam/v1alpha2/register.go
  pkg/kapis/kapis.go
  pkg/kapis/openpitrix/v1/handler.go
  pkg/kapis/tenant/v1alpha2/devops.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/kapis/terminal/v1alpha2/register.go
  pkg/models/iam/am.go
  pkg/models/iam/im.go
  pkg/models/iam/im_test.go
  pkg/models/iam/types.go
  pkg/models/openpitrix/applications_test.go
  pkg/models/tenant/namespaces.go
  pkg/models/tenant/tenant.go
  pkg/models/tenant/workspaces.go
  pkg/server/config/config.go
  pkg/server/errors/errors.go
  pkg/simple/client/factory.go
  pkg/simple/client/ldap/channel.go
  pkg/simple/client/ldap/conn.go
  pkg/simple/client/ldap/ldap.go
  pkg/simple/client/ldap/mock.go
  pkg/simple/client/ldap/options.go
  pkg/simple/client/openpitrix/openpitrix.go
  pkg/simple/client/openpitrix/options.go
  pkg/utils/jwtutil/jwt.go
Labels: kind/cleanup, size/XXL

#1685 add monitoring dev guides
  docs/en/concepts-and-designs/README.md
  docs/en/concepts-and-designs/kubesphere-monitoring.md
  docs/en/guides/README.md
  docs/en/guides/kubesphere-monitoring-development-guide.md
  docs/images/kubesphere-monitoring-architecture.png
Labels: approved, kind/documentation, lgtm, size/M

#1689 update s2i docs
  docs/en/concepts-and-designs/README.md
  docs/en/concepts-and-designs/s2i_b2i_overview.md
  docs/en/guides/README.md
  docs/images/s2i_arch.png
Labels: approved, kind/documentation, lgtm, size/M

#1681 add logging dev guides
  docs/en/concepts-and-designs/README.md
  docs/en/concepts-and-designs/kubesphere-logging.md
  docs/en/guides/README.md
  docs/en/guides/kubesphere-logging-devlopment-guide.md
  docs/images/kubesphere-logging-fluentbit.png
  docs/images/kubesphere-logging-overview.png
Labels: approved, kind/documentation, lgtm, size/L

#1922 code refactor
  pkg/apiserver/openpitrix/attachments.go
  pkg/apiserver/resources/user.go
  pkg/apiserver/tenant/tenant.go
  pkg/kapis/devops/v1alpha2/register.go
  pkg/kapis/resources/v1alpha2/handler.go
  pkg/kapis/resources/v1alpha2/register.go
  pkg/models/iam/am.go
  pkg/models/kubeconfig/kubeconfig.go
  pkg/models/kubectl/kubectl.go
Labels: size/XL

#1923 code refactor
  pkg/kapis/iam/v1alpha2/register.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/models/iam/am.go
  pkg/models/iam/policy/policy.go
  pkg/models/iam/types.go
  pkg/models/iam/utils.go
  pkg/models/tenant/devops.go
  pkg/models/tenant/tenant.go
Labels: size/L
