Repository kubesphere/kubesphere, pull requests merged in 2020-06, with the labels that each got.

#2129 add auditing events search api
  cmd/ks-apiserver/app/options/options.go
  cmd/ks-apiserver/app/options/validation.go
  pkg/api/auditing/v1alpha1/types.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/config/config.go
  pkg/apiserver/config/config_test.go
  pkg/constants/constants.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/models/auditing/events.go
  pkg/models/tenant/tenant.go
  pkg/models/tenant/tenent_test.go
  pkg/simple/client/auditing/elasticsearch/clients.go
  pkg/simple/client/auditing/elasticsearch/elasticsearch.go
  pkg/simple/client/auditing/elasticsearch/elasticsearch_test.go
  pkg/simple/client/auditing/elasticsearch/options.go
  pkg/simple/client/auditing/interface.go
  tools/cmd/doc-gen/main.go
Labels: approved, kind/feature, lgtm, size/XXL

#2144 use kube-apiserver proxy if no kubesphere api endpoint provided
  pkg/api/utils.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/dispatch/dispatch.go
  pkg/controller/cluster/cluster_controller.go
  pkg/kapis/cluster/v1alpha1/handler.go
Labels: approved, kind/feature, size/L

#2137 logging: start_time and end_time are not required params
  pkg/simple/client/logging/elasticsearch/api_body.go
  pkg/simple/client/logging/elasticsearch/api_body_test.go
  pkg/simple/client/logging/elasticsearch/testdata/api_body_7.json
Labels: approved, kind/bug, lgtm, size/M

#2145 fix authorization header stripped by kube-apiserver
  pkg/apiserver/dispatch/dispatch.go
  pkg/apiserver/dispatch/dispatch_test.go
  pkg/apiserver/filters/requestinfo.go
Labels: approved, kind/bug, size/S

#2146 fix proxy bug
  pkg/apiserver/dispatch/dispatch.go
  pkg/kapis/cluster/v1alpha1/handler.go
  pkg/kapis/cluster/v1alpha1/handler_test.go
Labels: approved, kind/bug, size/M

#2148 set devops log level to 8
  pkg/controller/devopscredential/devopscredential_controller.go
  pkg/controller/devopsproject/devopsproject_controller.go
  pkg/controller/pipeline/pipeline_controller.go
Labels: approved, kind/cleanup, lgtm, size/M

#2138 fix: crash if config file not provide
  cmd/ks-apiserver/app/options/options.go
Labels: approved, kind/bug, lgtm, size/S

#2151 fix namespace networkpolicy
  pkg/controller/network/nsnetworkpolicy/controller.go
Labels: approved, kind/bug, lgtm, size/XS

#2154 fix: clusterrolebinding controller bug
  cmd/controller-manager/app/controllers.go
  pkg/controller/clusterrolebinding/clusterrolebinding_controller.go
  pkg/controller/globalrolebinding/globalrolebinding_controller.go
  pkg/kapis/iam/v1alpha2/handler.go
  pkg/kapis/resources/v1alpha2/handler.go
  pkg/models/iam/am/am.go
  pkg/models/kubectl/kubectl.go
Labels: approved, kind/bug, lgtm, size/L

#2157 add snapshot crds
  config/crds/snapshot.storage.k8s.io_volumesnapshot.yaml
Labels: approved, lgtm, size/XS

#2155 add response_code_filter parameter in auditing events search api
  pkg/api/auditing/v1alpha1/types.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/models/auditing/events.go
  pkg/simple/client/auditing/elasticsearch/elasticsearch.go
  pkg/simple/client/auditing/elasticsearch/elasticsearch_test.go
  pkg/simple/client/auditing/elasticsearch/options.go
  pkg/simple/client/auditing/interface.go
Labels: approved, lgtm, size/L

#2165 fix openpitrix return non nil client when enpoint is empty
  cmd/ks-apiserver/app/options/options.go
  pkg/models/monitoring/monitoring.go
  pkg/models/openpitrix/interface.go
  pkg/simple/client/openpitrix/openpitrix.go
Labels: approved, kind/bug, size/M

#2166 fix namespace controller crash when openpitrix is not enabled
  pkg/controller/namespace/namespace_controller.go
Labels: approved, kind/bug, size/XS

#2167 fix namespace controller crash when openpitrix is not enabled
  cmd/controller-manager/app/server.go
  pkg/simple/client/openpitrix/openpitrix.go
Labels: approved, kind/bug, size/M

#2179 rename nsnp controller
  pkg/controller/network/nsnetworkpolicy/nsnetworkpolicy_controller.go
Labels: approved, kind/cleanup, lgtm, size/XS

#2161 fix jenkins basic auth
  pkg/apis/devops/v1alpha3/pipeline_types.go
  pkg/kapis/devops/v1alpha2/register.go
  pkg/kapis/resources/v1alpha2/handler.go
  pkg/models/devops/devops.go
  pkg/simple/client/devops/fake/fakedevops.go
  pkg/simple/client/devops/jenkins/jenkins.go
  pkg/simple/client/devops/jenkins/pipeline.go
  pkg/simple/client/devops/jenkins/pure_request.go
  pkg/simple/client/devops/pipeline.go
Labels: approved, kind/bug, lgtm, size/M

#2115 Fix query credential
  pkg/apiserver/apiserver.go
  pkg/kapis/devops/v1alpha3/handler.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/models/devops/devops.go
Labels: approved, kind/bug, lgtm, size/L

#2168 fix csr controller bug
  pkg/controller/certificatesigningrequest/certificatesigningrequest_controller.go
  pkg/controller/workspace/workspace_controller.go
Labels: approved, lgtm, size/M

#2180 add field for pipeline branch
  pkg/simple/client/devops/pipeline.go
Labels: approved, lgtm, size/XS

#2188 fix cluster status unchanged when cluster agent is already unavailable
  pkg/controller/cluster/cluster_controller.go
Labels: approved, kind/bug, kind/documentation, size/M

#2192 fix cluster status unchanged when cluster agent is already unavailable
  pkg/controller/application/application_controller.go
  pkg/controller/cluster/cluster_controller.go
Labels: approved, size/XS

#2193 fix apiresult
  pkg/kapis/devops/v1alpha3/register.go
  pkg/models/devops/devops.go
Labels: approved, lgtm, size/S

#2191 add tenant resource API
  pkg/kapis/iam/v1alpha2/handler.go
  pkg/kapis/iam/v1alpha2/register.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/models/iam/am/am.go
  pkg/models/tenant/tenant.go
  pkg/models/tenant/tenent_test.go
Labels: approved, kind/api-change, kind/feature, lgtm, size/XXL

#2197 Add option to enable network policy or not
  pkg/apiserver/apiserver.go
  pkg/apiserver/config/config.go
  pkg/apiserver/config/config_test.go
  pkg/simple/client/network/options.go
Labels: approved, kind/feature, lgtm, size/S

#2190 only accept validated CIDR in namespace networkpolicy
  config/crd/bases/network.kubesphere.io_namespacenetworkpolicies.yaml
  config/crds/network.kubesphere.io_namespacenetworkpolicies.yaml
  pkg/controller/network/nsnetworkpolicy/nsnetworkpolicy_controller.go
Labels: approved, kind/bug, lgtm, size/XL

#2187 add audit components
  cmd/ks-apiserver/app/server.go
  hack/generate_client.sh
  pkg/apis/addtoscheme_audting_v1alpha1.go
  pkg/apis/auditing/group.go
  pkg/apis/auditing/v1alpha1/doc.go
  pkg/apis/auditing/v1alpha1/register.go
  pkg/apis/auditing/v1alpha1/rule_types.go
  pkg/apis/auditing/v1alpha1/v1alpha1_suite_test.go
  pkg/apis/auditing/v1alpha1/webhook_types.go
  pkg/apis/auditing/v1alpha1/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/auditing/backend.go
  pkg/apiserver/auditing/types.go
  pkg/apiserver/auditing/types_test.go
  pkg/apiserver/auditing/v1alpha1/event.go
  pkg/apiserver/filters/auditing.go
  pkg/apiserver/request/context.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/auditing/v1alpha1/auditing_client.go
  pkg/client/clientset/versioned/typed/auditing/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/auditing/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/auditing/v1alpha1/fake/fake_auditing_client.go
  pkg/client/clientset/versioned/typed/auditing/v1alpha1/fake/fake_rule.go
  pkg/client/clientset/versioned/typed/auditing/v1alpha1/fake/fake_webhook.go
  pkg/client/clientset/versioned/typed/auditing/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/auditing/v1alpha1/rule.go
  pkg/client/clientset/versioned/typed/auditing/v1alpha1/webhook.go
  pkg/client/informers/externalversions/auditing/interface.go
  pkg/client/informers/externalversions/auditing/v1alpha1/interface.go
  pkg/client/informers/externalversions/auditing/v1alpha1/rule.go
  pkg/client/informers/externalversions/auditing/v1alpha1/webhook.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/auditing/v1alpha1/expansion_generated.go
  pkg/client/listers/auditing/v1alpha1/rule.go
  pkg/client/listers/auditing/v1alpha1/webhook.go
  pkg/simple/client/auditing/elasticsearch/options.go
Labels: approved, kind/feature, lgtm, size/XXL

#2203 Bugfix: UpsertRuntime create wrong runtime_id
  pkg/simple/client/openpitrix/openpitrix.go
Labels: approved, kind/bug, lgtm, size/XS

#2204 create openpitrix runtime when new cluster added
  cmd/controller-manager/app/controllers.go
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/server.go
  pkg/apis/cluster/v1alpha1/cluster_types.go
  pkg/controller/cluster/cluster_controller.go
  test/testdata/certs/tls.crt
  test/testdata/certs/tls.key
Labels: approved, size/L

#2206 fix: label filter
  pkg/controller/namespace/namespace_controller.go
  pkg/controller/workspacetemplate/workspacetemplate_controller.go
  pkg/models/iam/am/am.go
  pkg/models/resources/v1alpha3/interface.go
Labels: approved, kind/bug, lgtm, size/S

#2212 fix: auto create workspace manager rolebinding
  pkg/apis/iam/v1alpha2/types.go
  pkg/controller/workspacetemplate/workspacetemplate_controller.go
Labels: approved, lgtm, size/M

#2216 fix the bug "Cannot read property 'get' of undefined"
  pkg/apiserver/auditing/types.go
  pkg/apiserver/auditing/types_test.go
Labels: approved, lgtm, size/S

#2218 fix: label filter logic
  pkg/models/resources/v1alpha3/interface.go
  pkg/models/resources/v1alpha3/interface_test.go
  pkg/models/resources/v1alpha3/node/nodes.go
Labels: approved, kind/api-change, kind/bug, lgtm, size/L

#2217 fix: workspace cluster authorize
  config/crds/tenant.kubesphere.io_workspacetemplates.yaml
  pkg/apis/tenant/v1alpha2/workspacetemplate_types.go
  pkg/apis/tenant/v1alpha2/zz_generated.deepcopy.go
  pkg/controller/workspacetemplate/workspacetemplate_controller.go
  pkg/models/tenant/tenant.go
Labels: approved, kind/api-change, kind/bug, lgtm, size/L

#2221 fix: controller panic
  pkg/controller/workspace/workspace_controller.go
Labels: approved, kind/bug, lgtm, size/M

#2223 fix cluster import validation bug
  pkg/kapis/cluster/v1alpha1/handler.go
  pkg/kapis/cluster/v1alpha1/handler_test.go
  pkg/kapis/cluster/v1alpha1/register.go
Labels: approved, size/M

#2219 add role patch API
  pkg/kapis/iam/v1alpha2/handler.go
  pkg/kapis/iam/v1alpha2/register.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/models/iam/am/am.go
Labels: approved, kind/feature, lgtm, size/XL

#2225 fix: workspace label missing after update
  pkg/controller/workspacetemplate/workspacetemplate_controller.go
Labels: approved, kind/bug, lgtm, size/S

#2230 fix: multi-cluster proxy authentication
  pkg/apiserver/apiserver.go
  pkg/apiserver/authorization/authorizerfactory/rbac.go
  pkg/apiserver/authorization/proxy/doc.go
  pkg/apiserver/authorization/proxy/proxy.go
  pkg/apiserver/authorization/proxy/proxy_test.go
  pkg/apiserver/request/requestinfo.go
  pkg/controller/workspacetemplate/workspacetemplate_controller.go
Labels: approved, kind/bug, lgtm, size/L

#2231 fix: total in histogram response of events search
  pkg/simple/client/events/elasticsearch/elasticsearch.go
Labels: approved, lgtm, size/XS

#2232 update comment
  pkg/models/monitoring/expressions/prometheus.go
Labels: approved, kind/cleanup, kind/documentation, lgtm, size/XS

#2233 feat: add api list application
  pkg/kapis/openpitrix/v1/register.go
Labels: approved, lgtm, size/S

#2240 fix kubeapiserver proxy rejects all dryRun requests
  pkg/apiserver/apiserver.go
  pkg/apiserver/dispatch/dispatch.go
  pkg/apiserver/filters/requestinfo.go
Labels: approved, kind/bug, size/M

#2241 fix kubeapiserver proxy rejects all dryRun requests
  pkg/apiserver/apiserver.go
  pkg/apiserver/filters/requestinfo.go
Labels: approved, size/M

#2244 Add API for Describe the specified application of the namespace
  pkg/kapis/openpitrix/v1/register.go
Labels: approved, kind/feature, lgtm, size/XS

#2243 fix virtualservice and destinationrule controller
  cmd/controller-manager/app/controllers.go
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/server.go
Labels: approved, size/M

#2245 update metrics
  pkg/simple/client/monitoring/prometheus/promql.go
Labels: approved, kind/cleanup, lgtm, size/S

#2252 fix: federatedworkspace clusterSelector zero value
  pkg/apis/tenant/v1alpha2/workspacetemplate_types.go
  pkg/apis/tenant/v1alpha2/zz_generated.deepcopy.go
Labels: approved, kind/bug, lgtm, size/XS

#2253 fix wrong total audit event number
  pkg/simple/client/auditing/elasticsearch/elasticsearch.go
Labels: approved, lgtm, size/XS

#2254 fix: listIntersectedNamespaces for observability
  pkg/models/tenant/tenant.go
Labels: approved, lgtm, size/M

#2256 logging: update rolebinding check
  pkg/models/tenant/tenant.go
Labels: approved, kind/bug, lgtm, size/XS

#2257 add resourcescope to AttributesRecord when determine whether the user…
  pkg/models/tenant/tenant.go
Labels: approved, lgtm, size/XS

#2227 process audit information for resource creating requests
  pkg/apiserver/auditing/backend.go
  pkg/apiserver/auditing/types.go
  pkg/apiserver/auditing/v1alpha1/event.go
  pkg/apiserver/filters/auditing.go
Labels: approved, lgtm, size/M

#2260 fix bug auditing search error when es index does not exist
  pkg/simple/client/auditing/elasticsearch/elasticsearch.go
Labels: approved, lgtm, size/S

#2273 Centos version and link change in readme
  README.md
Labels: approved, kind/documentation, lgtm, size/XS
