Repository kubesphere/kubesphere, pull requests merged in 2020-04, with the labels that each got.

#1977 fix proxy host bug
  pkg/apiserver/dispatch/dispatch.go
Labels: approved, kind/bug, size/XS

#1980 fix requestinfo bug
  Makefile
  pkg/api/types.go
  pkg/apis/devops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/network/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/servicemesh/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/tenant/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/tower/v1alpha1/zz_generated.deepcopy.go
  pkg/apiserver/request/requestinfo.go
  pkg/apiserver/request/requestinfo_test.go
Labels: approved, size/L

#1981 fix union authorizer bug
  pkg/apiserver/apiserver.go
  pkg/apiserver/authorization/path/path.go
  pkg/apiserver/filters/authorization.go
  pkg/kapis/config/v1alpha2/register.go
Labels: approved, kind/bug, size/M

#1993 add cluster controller
  cmd/controller-manager/app/controllers.go
Labels: approved, kind/api-change, kind/bug, size/XS

#1976 Update README
  README.md
  README_zh.md
Labels: approved, lgtm, size/M

#1996 fix cluster controller
  Makefile
  config/crd/bases/cluster.kubesphere.io_clusters.yaml
  pkg/apis/cluster/v1alpha1/agent_types.go
  pkg/apis/cluster/v1alpha1/cluster_types.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/iam/v1alpha2/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/config/config.go
  pkg/apiserver/dispatch/dispatch.go
  pkg/apiserver/request/requestinfo.go
  pkg/apiserver/request/requestinfo_test.go
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/destinationrule/destinationrule_controller.go
  pkg/controller/virtualservice/virtualservice_controller.go
Labels: approved, kind/api-change, kind/bug, size/L

#1997 Change cluster path
  pkg/apiserver/filters/kubeapiserver.go
Labels: approved, size/XS

#2002 fix proxy bug
  config/crd/bases/cluster.kubesphere.io_agents.yaml
  config/crd/bases/cluster.kubesphere.io_clusters.yaml
  pkg/apis/cluster/v1alpha1/cluster_types.go
  pkg/apis/cluster/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/devops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/iam/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/network/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/servicemesh/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/tenant/v1alpha1/zz_generated.deepcopy.go
  pkg/apiserver/dispatch/dispatch.go
Labels: approved, kind/bug, size/M

#2005 token cache config
  pkg/apiserver/apiserver.go
  pkg/apiserver/authentication/options/authenticate_options.go
  pkg/apiserver/authentication/request/bearertoken/bearertoken.go
  pkg/apiserver/authentication/request/bearertoken/bearertoken_test.go
  pkg/apiserver/authentication/token/jwt.go
  pkg/apiserver/authentication/token/jwt_test.go
  pkg/apiserver/filters/authentication.go
  pkg/apiserver/filters/kubeapiserver.go
Labels: approved, kind/api-change, lgtm, size/L

#2008 fix iam admission webhook
  config/samples/iam_v1alpha2_user.yaml
  config/webhook/iam.yaml
  pkg/apis/iam/v1alpha2/register.go
  pkg/controller/user/user_webhook.go
Labels: size/M

#2015 upgrade monitoring api version
  pkg/kapis/monitoring/v1alpha3/register.go
Labels: kind/api-change, size/XS

#1985 Add network topology APIs
  cmd/ks-apiserver/app/options/options.go
  cmd/ks-apiserver/app/options/validation.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/config/config.go
  pkg/apiserver/config/config_test.go
  pkg/constants/constants.go
  pkg/kapis/network/group.go
  pkg/kapis/network/v1alpha2/handler.go
  pkg/kapis/network/v1alpha2/register.go
  pkg/kapis/network/v1alpha2/swagger-doc.go
  pkg/simple/client/network/options.go
  tools/cmd/doc-gen/main.go
Labels: approved, lgtm, size/L

#2017 Update Makefile header license description
  Makefile
Labels: approved, kind/documentation, lgtm, size/S

#2016 fix isRangeQuery
  pkg/kapis/monitoring/v1alpha3/helper.go
  pkg/kapis/monitoring/v1alpha3/helper_test.go
Labels: approved, kind/bug, lgtm, size/M

#2021 update makefile
  Makefile
  hack/docker_build.sh
Labels: approved, lgtm, size/XS

#2027 monitoring: some bug fix
  pkg/kapis/monitoring/v1alpha3/helper.go
  pkg/kapis/monitoring/v1alpha3/helper_test.go
  pkg/models/monitoring/expressions/prometheus.go
  pkg/models/monitoring/expressions/prometheus_test.go
  pkg/models/monitoring/expressions/registry.go
  pkg/models/monitoring/sort_page_test.go
  pkg/models/monitoring/testdata/null-node-metrics-sorted.json
  pkg/models/monitoring/testdata/null-node-metrics.json
  pkg/simple/client/monitoring/prometheus/prometheus.go
  pkg/simple/client/monitoring/prometheus/prometheus_test.go
  pkg/simple/client/monitoring/prometheus/promql.go
  pkg/simple/client/monitoring/prometheus/promql_test.go
  pkg/simple/client/monitoring/prometheus/testdata/metadata-prom.json
  pkg/simple/client/monitoring/prometheus/testdata/promqls.go
  pkg/simple/client/monitoring/query_options.go
  pkg/simple/client/monitoring/types.go
Labels: approved, lgtm, size/XL

#2032 update makefile
  Makefile
  hack/docker_build.sh
Labels: approved, lgtm, size/S

#2022 Regenerate swagger.json
  api/ks-openapi-spec/swagger.json
Labels: approved, lgtm, size/XL

#1795 devops 3.0 roadmap
  docs/roadmap.md
Labels: area/devops, lgtm, size/XS

#2035 Update OWNERS
  OWNERS
Labels: approved, lgtm, size/XS

#1805 Add storage roadmap for ks 3.0
  docs/roadmap.md
Labels: approved, area/storage, kind/documentation, lgtm, size/XS

#1792 Add v3.0 observability roadmap
  docs/roadmap.md
Labels: approved, kind/documentation, lgtm, size/XS

#1806 multi-tenancy 3.0 roadmap
  docs/roadmap.md
Labels: approved, area/iam, kind/documentation, lgtm, size/XS

#1890 Add patch api header
  pkg/kapis/resources/v1alpha2/register.go
Labels: approved, kind/feature, lgtm, size/XS

#2037 fix multicluster options
  cmd/controller-manager/app/server.go
Labels: approved, kind/bug, size/S

#2042 add cluster proxy gerneration code
  go.mod
  go.sum
  pkg/apiserver/apiserver.go
  pkg/kapis/cluster/v1alpha1/handler.go
  pkg/kapis/cluster/v1alpha1/handler_test.go
  pkg/kapis/cluster/v1alpha1/register.go
  pkg/kapis/config/v1alpha2/register.go
  pkg/simple/client/multicluster/options.go
  vendor/github.com/liggitt/tabwriter/.travis.yml
  vendor/github.com/liggitt/tabwriter/LICENSE
  vendor/github.com/liggitt/tabwriter/README.md
  vendor/github.com/liggitt/tabwriter/tabwriter.go
  vendor/k8s.io/apimachinery/pkg/util/duration/duration.go
  vendor/k8s.io/cli-runtime/LICENSE
  vendor/k8s.io/cli-runtime/pkg/printers/discard.go
  vendor/k8s.io/cli-runtime/pkg/printers/doc.go
  vendor/k8s.io/cli-runtime/pkg/printers/interface.go
  vendor/k8s.io/cli-runtime/pkg/printers/json.go
  vendor/k8s.io/cli-runtime/pkg/printers/jsonpath.go
  vendor/k8s.io/cli-runtime/pkg/printers/name.go
  vendor/k8s.io/cli-runtime/pkg/printers/sourcechecker.go
  vendor/k8s.io/cli-runtime/pkg/printers/tableprinter.go
  vendor/k8s.io/cli-runtime/pkg/printers/tabwriter.go
  vendor/k8s.io/cli-runtime/pkg/printers/template.go
  vendor/k8s.io/cli-runtime/pkg/printers/typesetter.go
  vendor/k8s.io/client-go/third_party/forked/golang/template/exec.go
  vendor/k8s.io/client-go/third_party/forked/golang/template/funcs.go
  vendor/k8s.io/client-go/util/jsonpath/doc.go
  vendor/k8s.io/client-go/util/jsonpath/jsonpath.go
  vendor/k8s.io/client-go/util/jsonpath/node.go
  vendor/k8s.io/client-go/util/jsonpath/parser.go
  vendor/modules.txt
Labels: approved, kind/feature, size/XXL
