Repository kubesphere/kubesphere, pull requests merged in 2020-12, with the labels that each got.

#3131 Add gitlab multi-branch pipeline support
  api/api-rules/violation_exceptions.list
  api/ks-openapi-spec/swagger.json
  config/crds/devops.kubesphere.io_pipelines.yaml
  go.mod
  pkg/apis/devops/v1alpha3/pipeline_types.go
  pkg/apis/devops/v1alpha3/zz_generated.deepcopy.go
  pkg/kapis/devops/v1alpha3/handler.go
  pkg/simple/client/devops/jenkins/internal/gitlab.go
  pkg/simple/client/devops/jenkins/pipeline_internal.go
  pkg/simple/client/devops/jenkins/pipeline_internal_test.go
Labels: approved, area/devops, dco-signoff: yes, kind/feature, lgtm, size/XL

#3148 add group filter for user api
  pkg/apis/iam/v1alpha2/types.go
  pkg/models/resources/v1alpha3/user/users.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, size/XS

#3151 just filter out namespace started with kube-
  cmd/ks-apiserver/app/server.go
Labels: approved, area/microservice, dco-signoff: yes, lgtm, size/XS

#3159 Fix the docker login isseus
  .github/workflows/build.yml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#3168 fix comments
  pkg/controller/destinationrule/destinationrule_controller.go
Labels: approved, area/microservice, dco-signoff: yes, kind/documentation, lgtm, size/XS

#3145 Provide a hunman readable error message instead of the raw
  pkg/simple/client/devops/jenkins/pipeline.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/S

#3163 Improve the process of build docker images.
  hack/docker_build.sh
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#3175 add kubeconfig check
  cmd/ks-apiserver/app/server.go
  pkg/controller/group/group_controller.go
Labels: approved, area/microservice, dco-signoff: yes, kind/failing-test, lgtm, size/S

#3156 Restrict only specific users or admin can approve a pipeline
  go.mod
  pkg/apiserver/apiserver.go
  pkg/kapis/devops/v1alpha2/devops.go
  pkg/kapis/devops/v1alpha2/handler.go
  pkg/kapis/devops/v1alpha2/register.go
  pkg/models/devops/devops.go
  pkg/simple/client/devops/pipeline.go
  pkg/simple/client/devops/pipeline_test.go
  tools/cmd/doc-gen/main.go
Labels: approved, area/devops, dco-signoff: yes, kind/feature, lgtm, size/L

#3165 Fix the inapproprite errors handle with cron expression checking
  pkg/simple/client/devops/jenkins/jenkins.go
  pkg/simple/client/devops/jenkins/pipeline.go
Labels: approved, area/devops, dco-signoff: yes, kind/feature, lgtm, size/M

#3180 Fix pipeline cannot be removed due to finalizers
  pkg/controller/pipeline/pipeline_controller.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/M

#3178 filter groupbinding by user field
  pkg/models/resources/v1alpha3/groupbinding/groupbinding.go
Labels: approved, dco-signoff: yes, kind/api-change, kind/feature, lgtm, size/S

#3161 enable multicluster sync for groups
  cmd/controller-manager/app/controllers.go
  config/crds/types.kubefed.io_federatedgroupbindings.yaml
  config/crds/types.kubefed.io_federatedgroups.yaml
  pkg/apis/types/v1beta1/federatedgroup_types.go
  pkg/apis/types/v1beta1/federatedgroupbinding_types.go
  pkg/apis/types/v1beta1/register.go
  pkg/apis/types/v1beta1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/types/v1beta1/fake/fake_federatedgroup.go
  pkg/client/clientset/versioned/typed/types/v1beta1/fake/fake_federatedgroupbinding.go
  pkg/client/clientset/versioned/typed/types/v1beta1/fake/fake_types_client.go
  pkg/client/clientset/versioned/typed/types/v1beta1/federatedgroup.go
  pkg/client/clientset/versioned/typed/types/v1beta1/federatedgroupbinding.go
  pkg/client/clientset/versioned/typed/types/v1beta1/generated_expansion.go
  pkg/client/clientset/versioned/typed/types/v1beta1/types_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/types/v1beta1/federatedgroup.go
  pkg/client/informers/externalversions/types/v1beta1/federatedgroupbinding.go
  pkg/client/informers/externalversions/types/v1beta1/interface.go
  pkg/client/listers/types/v1beta1/expansion_generated.go
  pkg/client/listers/types/v1beta1/federatedgroup.go
  pkg/client/listers/types/v1beta1/federatedgroupbinding.go
  pkg/controller/group/group_controller.go
  pkg/controller/group/group_controller_test.go
  pkg/controller/groupbinding/groupbinding_controller.go
  pkg/controller/groupbinding/groupbinding_controller_test.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XL

#3186 support for querying pods metrics from the cluster level
  pkg/kapis/monitoring/v1alpha3/register.go
  pkg/simple/client/monitoring/prometheus/promql.go
  pkg/simple/client/monitoring/prometheus/promql_test.go
  pkg/simple/client/monitoring/prometheus/testdata/promqls.go
Labels: approved, area/monitoring, dco-signoff: yes, kind/api-change, lgtm, size/M

#3190 Fix devops artifact cannot be download due to auth checking
  pkg/kapis/devops/v1alpha2/register.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/S

#3193 custom monitoring with cluster level
  pkg/kapis/monitoring/v1alpha3/register.go
  pkg/models/monitoring/monitoring.go
  pkg/simple/client/monitoring/prometheus/prometheus.go
Labels: approved, area/monitoring, dco-signoff: yes, kind/api-change, lgtm, size/M

#3199 fixed: check the cluster has initialized
  pkg/controller/cluster/cluster_controller.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#3204 remove unused package
  Makefile
  pkg/db/Dockerfile
  pkg/db/condition.go
  pkg/db/condition_test.go
  pkg/db/db.go
  pkg/db/ddl/devops.sql
  pkg/db/error.go
  pkg/db/event.go
  pkg/db/schema/devops/V0_1__init.sql
  pkg/db/schema/devops/V0_2__credential.sql
  pkg/db/schema/devops/V0_3__workspace.sql
  pkg/db/scripts/ddl_init.sh
Labels: approved, dco-signoff: yes, kind/cleanup, size/XL

#3149 Mix up the pipeline list between ks and Jenkins
  pkg/kapis/devops/v1alpha2/devops.go
  pkg/kapis/devops/v1alpha3/handler.go
  pkg/models/devops/devops.go
  pkg/simple/client/devops/pipeline.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/M

#3146 using Kiali API directly
  cmd/ks-apiserver/app/server.go
  go.mod
  pkg/kapis/servicemesh/metrics/v1alpha2/handler.go
  pkg/simple/client/servicemesh/options.go
Labels: approved, dco-signoff: yes, kind/api-change, kind/cleanup, lgtm, size/L

#3195 Fix devops project cannot be deleted due to mess up with finalizer control
  pkg/controller/devopsproject/devopsproject_controller.go
  pkg/simple/client/devops/jenkins/project.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/M

#3206 Validate member cluster's workspaces when joining clusters
  pkg/controller/cluster/join.go
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/M

#3217 add group api
  pkg/controller/loginrecord/loginrecord_controller_test.go
  pkg/kapis/iam/v1alpha2/handler.go
  pkg/kapis/iam/v1alpha2/register.go
  pkg/models/iam/am/am.go
  pkg/models/iam/group/group.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, size/L

#3201 fix bug get goroutine for audit timeout
  pkg/apiserver/apiserver.go
  pkg/apiserver/auditing/backend.go
  pkg/apiserver/auditing/types.go
  pkg/simple/client/auditing/elasticsearch/options.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#3203 [BugFix] Fix cluster unjoin federation plane when using proxy connection
  pkg/controller/cluster/cluster_controller.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#3229 fix bug Failed to configure LDAP login, error message: socket hang up
  pkg/apiserver/auditing/types.go
  pkg/apiserver/auditing/types_test.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3228 Add a GitHub action for building nightly images
  .github/workflows/nightly-builds.yml
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M

#3233 fix no informer found
  pkg/apiserver/apiserver.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#3216 add ippool resource api
  api/openapi-spec/swagger.json
  cmd/controller-manager/app/controllers.go
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/server.go
  config/crds/network.kubesphere.io_ippools.yaml
  pkg/apis/network/v1alpha1/ipamblock_types.go
  pkg/apis/network/v1alpha1/ippool_types.go
  pkg/apis/network/v1alpha1/ippool_types_test.go
  pkg/apis/network/v1alpha1/namespacenetworkpolicy_types.go
  pkg/apis/network/v1alpha1/openapi_generated.go
  pkg/apis/network/v1alpha1/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/config/config.go
  pkg/apiserver/config/config_test.go
  pkg/controller/network/ippool/ippool_controller.go
  pkg/controller/network/ippool/ippool_controller_test.go
  pkg/controller/network/nsnetworkpolicy/nsnetworkpolicy_controller.go
  pkg/controller/network/nsnetworkpolicy/provider/ns_k8s.go
  pkg/controller/network/nsnetworkpolicy/webhook.go
  pkg/controller/network/types/types.go
  pkg/controller/network/webhooks/default.go
  pkg/controller/network/webhooks/validator.go
  pkg/models/resources/v1alpha3/ippool/ippools.go
  pkg/models/resources/v1alpha3/ippool/ippools_test.go
  pkg/models/resources/v1alpha3/resource/resource.go
  pkg/simple/client/network/ippool/calico/provider.go
  pkg/simple/client/network/ippool/calico/provider_test.go
  pkg/simple/client/network/ippool/provider.go
  pkg/simple/client/network/ippool/provider_test.go
  pkg/simple/client/network/options.go
  tools/cmd/crd-doc-gen/main.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XXL

#3237 add v3.1 roadmap
  docs/roadmap.md
Labels: approved, dco-signoff: yes, kind/documentation, size/M
