Repository kubesphere/kubesphere, pull requests merged in 2020-07, with the labels that each got.

#2258 fix nsnp webhook to validate all fileds in it
  cmd/controller-manager/app/server.go
  config/webhook/nsnp.yaml
  pkg/controller/network/nsnetworkpolicy/webhook.go
Labels: approved, kind/bug, lgtm, size/L

#2270 fix: synchronize users to LDAP
  cmd/controller-manager/app/controllers.go
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/server.go
  cmd/ks-apiserver/app/options/options.go
  pkg/apiserver/apiserver.go
  pkg/controller/user/user_controller.go
  pkg/controller/user/user_controller_test.go
  pkg/simple/client/ldap/ldap.go
  pkg/simple/client/ldap/simple_ldap.go
Labels: approved, lgtm, size/L

#2288 fix: federated workspace cluster selector
  pkg/models/tenant/tenant.go
Labels: approved, kind/bug, lgtm, size/M

#2291 fix issue #2289 Can't create fed project
  pkg/models/tenant/tenant.go
Labels: approved, size/S

#2290 fix: implicit workspace info in query
  pkg/apiserver/request/requestinfo.go
Labels: approved, kind/bug, lgtm, size/S

#2293 Refactor OpenPitrix API path
  pkg/kapis/openpitrix/v1/handler.go
  pkg/kapis/openpitrix/v1/register.go
Labels: approved, kind/cleanup, lgtm, size/L

#2265 capability for non CSI storage
  cmd/controller-manager/app/controllers.go
  config/crds/storage.kubesphere.io_provisionercapabilities.yaml
  config/crds/storage.kubesphere.io_storageclasscapabilities.yaml
  config/default/provisonercapability/aws-ebs.yaml
  config/default/provisonercapability/azure-disk.yaml
  config/default/provisonercapability/azure-file.yaml
  config/default/provisonercapability/cinder.yaml
  config/default/provisonercapability/gce-pd.yaml
  config/default/provisonercapability/glusterfs.yaml
  config/default/provisonercapability/portworx-volume.yaml
  config/default/provisonercapability/rbd.yaml
  config/samples/storage_v1alpha1_provisionercapability.yaml
  pkg/apis/storage/v1alpha1/capability_types.go
  pkg/apis/storage/v1alpha1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/storage/v1alpha1/fake/fake_provisionercapability.go
  pkg/client/clientset/versioned/typed/storage/v1alpha1/fake/fake_storage_client.go
  pkg/client/clientset/versioned/typed/storage/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/storage/v1alpha1/provisionercapability.go
  pkg/client/clientset/versioned/typed/storage/v1alpha1/storage_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/storage/v1alpha1/interface.go
  pkg/client/informers/externalversions/storage/v1alpha1/provisionercapability.go
  pkg/client/listers/storage/v1alpha1/expansion_generated.go
  pkg/client/listers/storage/v1alpha1/provisionercapability.go
  pkg/controller/storage/capability/capability_controller.go
  pkg/controller/storage/capability/capability_controller_test.go
  pkg/controller/storage/capability/csi_capability_test.go
  pkg/models/resources/v1alpha3/volumesnapshot/volumesnapshot.go
  pkg/models/resources/v1alpha3/volumesnapshot/volumesnapshot_test.go
Labels: kind/feature, lgtm, size/XL

#2318 revert openpitrix API
  pkg/kapis/openpitrix/v1/handler.go
  pkg/kapis/openpitrix/v1/register.go
  pkg/models/openpitrix/apps.go
Labels: approved, lgtm, size/L

#2264 fix: password modify
  pkg/api/auth/types.go
  pkg/api/iam/types.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/authentication/options/authenticate_options.go
  pkg/apiserver/authentication/token/jwt.go
  pkg/apiserver/config/config_test.go
  pkg/apiserver/filters/authentication.go
  pkg/controller/namespace/namespace_controller.go
  pkg/kapis/iam/v1alpha2/handler.go
  pkg/kapis/iam/v1alpha2/register.go
  pkg/kapis/oauth/handler.go
  pkg/kapis/oauth/register.go
  pkg/models/iam/im/im.go
  pkg/models/iam/im/ldap_operator.go
  pkg/models/types.go
Labels: approved, kind/bug, lgtm, size/XL

#2322 fix: DaemonSet status search returns wrong result
  pkg/models/resources/v1alpha2/daemonset/daemonsets.go
Labels: approved, kind/bug, lgtm, size/XS

#2324 make the ResponseCapture implements CloseNotify interface
  pkg/apiserver/auditing/types.go
Labels: approved, lgtm, size/XS

#2280 fix: resource scope
  pkg/apiserver/apiserver.go
  pkg/apiserver/authorization/authorizerfactory/rbac.go
  pkg/apiserver/request/requestinfo.go
  pkg/kapis/resources/v1alpha3/register.go
  pkg/kapis/tenant/v1alpha2/register.go
Labels: approved, kind/bug, lgtm, size/M

#2354 Add host cluster
  .github/workflows/build.yml
  Makefile
  build/ks-apiserver/Dockerfile
  build/ks-controller-manager/Dockerfile
  cmd/controller-manager/app/server.go
  cmd/ks-apiserver/app/options/options.go
  cmd/ks-apiserver/app/server.go
  hack/docker_build.sh
  hack/gobuild.sh
  hack/install_kubebuilder.sh
  hack/lib/golang.sh
  hack/lib/init.sh
  hack/lib/version.sh
  pkg/apis/cluster/v1alpha1/cluster_types.go
  pkg/apiserver/dispatch/dispatch.go
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/cluster/helper.go
  pkg/version/version.go
Labels: approved, kind/feature, size/L

#2355 fix typo
  .github/workflows/build.yml
Labels: approved, kind/bug, size/XS

#2353 Add /workspaces/{workspace}/apps/{app}
  pkg/kapis/openpitrix/v1/handler.go
  pkg/kapis/openpitrix/v1/register.go
Labels: approved, kind/feature, lgtm, size/M

#2372 change error message when there is no proxy address
  pkg/kapis/cluster/v1alpha1/handler.go
Labels: approved, kind/bug, size/S

#2370 fix sync kubeconfig bug
  pkg/apis/devops/v1alpha3/credential_types.go
  pkg/simple/client/devops/jenkins/credential_test.go
Labels: approved, lgtm, size/XS

#2373 fix: forbidden update user
  pkg/controller/user/user_controller_test.go
  pkg/kapis/iam/v1alpha2/handler.go
Labels: approved, lgtm, size/S

#2364 use more specific and user-friendly error messages
  pkg/apiserver/dispatch/dispatch.go
  pkg/kapis/cluster/v1alpha1/handler.go
  pkg/kapis/cluster/v1alpha1/handler_test.go
  pkg/kapis/cluster/v1alpha1/register.go
Labels: approved, kind/bug, size/M

#2333 fix: resource lifecycle
  cmd/controller-manager/app/controllers.go
  pkg/controller/globalrolebinding/globalrolebinding_controller.go
  pkg/controller/namespace/namespace_controller.go
  pkg/controller/user/user_controller.go
  pkg/controller/user/user_controller_test.go
  pkg/controller/workspacerole/workspacerole.go
  pkg/controller/workspacerolebinding/workspacerolebinding_controller.go
  pkg/controller/workspacetemplate/workspacetemplate_controller.go
  pkg/utils/k8sutil/k8sutil.go
Labels: approved, kind/bug, lgtm, size/L

#2408 modify the field networkIsolate in workspace
  pkg/apis/tenant/v1alpha1/workspace_types.go
  pkg/apis/tenant/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/tenant/v1alpha2/zz_generated.deepcopy.go
  pkg/controller/network/nsnetworkpolicy/nsnetworkpolicy_controller.go
  pkg/controller/network/nsnetworkpolicy/nsnetworkpolicy_test.go
Labels: approved, kind/bug, lgtm, size/M

#2404 fix: cannot sort in ascending order
  pkg/kapis/monitoring/v1alpha3/helper.go
Labels: approved, kind/bug, lgtm, size/XS

#2287 lazy initializing es client
  pkg/simple/client/logging/elasticsearch/elasticsearch.go
  pkg/simple/client/logging/elasticsearch/elasticsearch_test.go
  pkg/simple/client/logging/elasticsearch/versions/v5/v5.go
  pkg/simple/client/logging/elasticsearch/versions/v6/v6.go
  pkg/simple/client/logging/elasticsearch/versions/v7/v7.go
Labels: approved, lgtm, size/L

#2415 fix: empty server host
  pkg/models/kubeconfig/kubeconfig.go
Labels: approved, kind/bug, lgtm, size/XS

#2423 significantly improve log search performance
  pkg/simple/client/logging/elasticsearch/elasticsearch.go
  pkg/simple/client/logging/elasticsearch/elasticsearch_test.go
  pkg/simple/client/logging/elasticsearch/versions/v5/v5.go
  pkg/simple/client/logging/elasticsearch/versions/v6/v6.go
  pkg/simple/client/logging/elasticsearch/versions/v7/v7.go
  pkg/utils/esutil/esutil.go
  pkg/utils/esutil/esutil_test.go
Labels: approved, lgtm, size/L

#2416 fix "Failed to list *v1beta1.VolumeSnapshotClass" on k8s 1.16
  pkg/controller/storage/capability/capability_controller.go
Labels: approved, dco-signoff: no, lgtm, size/S

#2439 fix: node status filter
  pkg/models/resources/v1alpha3/node/nodes.go
  pkg/models/resources/v1alpha3/node/nodes_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#2419 lazy initializing es client of auditing
  pkg/simple/client/auditing/elasticsearch/elasticsearch.go
Labels: approved, kind/api-change, lgtm, size/L

#2368 using /v1alpha2/jenkins replace /jenkins.kubesphere.io api
  pkg/apiserver/apiserver.go
  pkg/kapis/devops/v1alpha2/register.go
  pkg/simple/client/devops/jenkins/pure_request.go
  pkg/simple/client/devops/jenkins/request.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, size/M

#2449 use non root user for building image
  build/ks-apiserver/Dockerfile
  build/ks-controller-manager/Dockerfile
Labels: approved, dco-signoff: yes, kind/feature, size/S

#2458 Use 8443 for webhook
  .gitignore
  build/ks-apiserver/Dockerfile
  build/ks-controller-manager/Dockerfile
  cmd/controller-manager/app/server.go
Labels: approved, dco-signoff: yes, kind/feature, size/S

#2392 add interface for iam
  cmd/controller-manager/app/controllers.go
  pkg/controller/globalrolebinding/globalrolebinding_controller.go
  pkg/models/devops/common.go
  pkg/simple/client/devops/fake/fakedevops.go
  pkg/simple/client/devops/interface.go
  pkg/simple/client/devops/jenkins/jenkins.go
  pkg/simple/client/devops/jenkins/role.go
  pkg/simple/client/devops/role.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XL

#2446 fix: migration some resource API to v1alpha3
  pkg/models/resources/v1alpha3/daemonset/daemonset.go
  pkg/models/resources/v1alpha3/daemonset/daemonset_test.go
  pkg/models/resources/v1alpha3/resource/resource.go
  pkg/models/resources/v1alpha3/service/services.go
  pkg/models/resources/v1alpha3/service/services_test.go
  pkg/models/resources/v1alpha3/statefulset/statefulsets.go
  pkg/models/resources/v1alpha3/statefulset/statefulsets_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XL

#2479 fix host cluster reconcile bug
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/cluster/helper.go
  pkg/controller/cluster/unjoin.go
  pkg/models/resources/v1alpha3/customresourcedefinition/customresourcedefinitions.go
  pkg/models/resources/v1alpha3/customresourcedefinition/customresourcedefinitions_test.go
Labels: approved, dco-signoff: yes, kind/bug, size/L

#2480 fix: Change user role failed
  pkg/kapis/iam/v1alpha2/handler.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#2482 change crd version to v1beta1
  pkg/apiserver/apiserver.go
Labels: approved, dco-signoff: yes, kind/bug, size/XS

#2487 Fix controller manager docker permission denied
  build/ks-apiserver/Dockerfile
  build/ks-controller-manager/Dockerfile
Labels: approved, dco-signoff: yes, kind/bug, size/M

#2427 ignore dryRun k8s request when auditing
  pkg/apiserver/auditing/types.go
  pkg/apiserver/auditing/types_test.go
  pkg/apiserver/filters/auditing.go
  pkg/apiserver/request/context.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#2441 lazy init events client and optimize events search
  pkg/simple/client/events/elasticsearch/clients.go
  pkg/simple/client/events/elasticsearch/elasticsearch.go
Labels: approved, kind/bug, kind/cleanup, lgtm, size/M

#2466 reuse package esutil to improve auditing log search performance
  pkg/simple/client/auditing/elasticsearch/clients.go
  pkg/simple/client/auditing/elasticsearch/elasticsearch.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, size/S

#2505 use root for controller manager cause we need to access csi plugins sock
  build/ks-controller-manager/Dockerfile
Labels: approved, dco-signoff: yes, kind/bug, size/S

#2526 fix: exit without error log
  cmd/controller-manager/app/server.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#2517 add total num for runs
  pkg/simple/client/devops/jenkins/pipeline.go
  pkg/simple/client/devops/pipeline.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#2533 fix pvc count of sc
  pkg/models/resources/v1alpha2/storageclass/storageclasses.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2498 add tenant federated namespaces API
  hack/generate_client.sh
  pkg/apis/types/v1beta1/doc.go
  pkg/apis/types/v1beta1/register.go
  pkg/apis/types/v1beta1/types.go
  pkg/apis/types/v1beta1/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/types/v1beta1/doc.go
  pkg/client/clientset/versioned/typed/types/v1beta1/fake/doc.go
  pkg/client/clientset/versioned/typed/types/v1beta1/fake/fake_federatednamespace.go
  pkg/client/clientset/versioned/typed/types/v1beta1/fake/fake_types_client.go
  pkg/client/clientset/versioned/typed/types/v1beta1/federatednamespace.go
  pkg/client/clientset/versioned/typed/types/v1beta1/generated_expansion.go
  pkg/client/clientset/versioned/typed/types/v1beta1/types_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/types/interface.go
  pkg/client/informers/externalversions/types/v1beta1/federatednamespace.go
  pkg/client/informers/externalversions/types/v1beta1/interface.go
  pkg/client/listers/types/v1beta1/expansion_generated.go
  pkg/client/listers/types/v1beta1/federatednamespace.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/models/resources/v1alpha3/federatednamespace/federatednamespaces.go
  pkg/models/resources/v1alpha3/federatednamespace/federatednamespaces_test.go
  pkg/models/resources/v1alpha3/resource/resource.go
  pkg/models/tenant/tenant.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#2541 fix cronjob sort bug, daemonsets status bug, add ingress to v1alpha3
  pkg/models/resources/v1alpha2/cronjob/cronjobs.go
  pkg/models/resources/v1alpha2/interface.go
  pkg/models/resources/v1alpha3/daemonset/daemonset.go
  pkg/models/resources/v1alpha3/deployment/deployments.go
  pkg/models/resources/v1alpha3/ingress/ingresses.go
  pkg/models/resources/v1alpha3/ingress/ingresses_test.go
  pkg/models/resources/v1alpha3/resource/resource.go
Labels: approved, dco-signoff: yes, kind/api-change, kind/bug, kind/feature, kind/flake, size/L

#2542 Bugfix: list repos
  pkg/kapis/openpitrix/v1/handler.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#2543 fix federatednamespace resource scope
  pkg/apis/types/v1beta1/types.go
  pkg/client/clientset/versioned/typed/types/v1beta1/fake/fake_federatednamespace.go
  pkg/client/clientset/versioned/typed/types/v1beta1/fake/fake_types_client.go
  pkg/client/clientset/versioned/typed/types/v1beta1/federatednamespace.go
  pkg/client/clientset/versioned/typed/types/v1beta1/types_client.go
  pkg/client/informers/externalversions/types/v1beta1/federatednamespace.go
  pkg/client/informers/externalversions/types/v1beta1/interface.go
  pkg/client/listers/types/v1beta1/expansion_generated.go
  pkg/client/listers/types/v1beta1/federatednamespace.go
  pkg/models/resources/v1alpha3/federatednamespace/federatednamespaces.go
  pkg/models/tenant/tenant.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#2532 fix events search bug when no events
  pkg/simple/client/events/elasticsearch/clients.go
  pkg/simple/client/events/elasticsearch/elasticsearch.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#2544 conflict status code
  pkg/kapis/iam/v1alpha2/handler.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2334 Configuring kubectl image from command line
  cmd/controller-manager/app/controllers.go
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/server.go
  pkg/apiserver/authentication/options/authenticate_options.go
  pkg/controller/clusterrolebinding/clusterrolebinding_controller.go
  pkg/kapis/resources/v1alpha2/handler.go
  pkg/models/kubectl/kubectl.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/L

#2567 Bugfix: create repo have no workspace
  pkg/kapis/openpitrix/v1/handler.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#2572 Fix create failed login records
  pkg/apiserver/filters/authentication.go
  pkg/models/iam/im/authenticator.go
  pkg/models/iam/im/login_recoder.go
Labels: approved, dco-signoff: yes, kind/bug, size/S

#2584 fix login with email
  pkg/models/iam/im/login_recoder.go
Labels: approved, dco-signoff: yes, size/XS

#2585 fix query parameters
  pkg/simple/client/devops/jenkins/pipeline.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#2609 fix RBAC authorizer
  pkg/apiserver/authorization/authorizerfactory/rbac.go
  pkg/models/iam/am/am.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#2613 add host local time to kubectl from toolbox
  pkg/models/kubectl/kubectl.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/S

#2596 fix bug multi tenant auditing, logging and event is incorrect
  pkg/models/tenant/tenant.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#2634 Bugfix: the count of uncategory apps is incorrect
  pkg/kapis/openpitrix/v1/handler.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#2639 fix: auth failed response
  pkg/controller/user/user_controller.go
  pkg/kapis/oauth/handler.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#2629 Reorder request filters
  pkg/apiserver/apiserver.go
  pkg/apiserver/authorization/proxy/doc.go
  pkg/apiserver/authorization/proxy/proxy.go
  pkg/apiserver/authorization/proxy/proxy_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#2661 fix: devops IAM bugs
  cmd/controller-manager/app/controllers.go
  pkg/apiserver/authorization/authorizer/interfaces.go
  pkg/apiserver/authorization/authorizerfactory/rbac.go
  pkg/apiserver/filters/authorization.go
  pkg/apiserver/request/requestinfo.go
  pkg/controller/devopsproject/devopsproject_controller.go
  pkg/controller/devopsproject/devopsproject_controller_test.go
  pkg/controller/globalrolebinding/globalrolebinding_controller.go
  pkg/kapis/iam/v1alpha2/handler.go
  pkg/kapis/oauth/handler.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/models/iam/am/am.go
  pkg/models/tenant/devops.go
  pkg/models/tenant/tenant.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#2668 get storage capapbility from provioner capability first
  pkg/controller/storage/capability/capability_controller.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2599 add new parameters allowedIngressNamespaces for user customization
  cmd/controller-manager/app/controllers.go
  cmd/controller-manager/app/server.go
  pkg/apiserver/config/config_test.go
  pkg/controller/network/nsnetworkpolicy/nsnetworkpolicy_controller.go
  pkg/controller/network/nsnetworkpolicy/nsnetworkpolicy_test.go
  pkg/simple/client/network/options.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#2676 fix panic
  pkg/models/tenant/devops.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2679 add last login time for user
  cmd/controller-manager/app/controllers.go
  config/crds/iam.kubesphere.io_federatedusers.yaml
  config/crds/iam.kubesphere.io_users.yaml
  hack/generate_certs.sh
  pkg/apis/iam/v1alpha2/types.go
  pkg/apis/iam/v1alpha2/zz_generated.deepcopy.go
  pkg/apiserver/authentication/options/authenticate_options.go
  pkg/controller/user/loginrecord_controller.go
  pkg/controller/user/user_controller.go
Labels: approved, dco-signoff: yes, kind/feature, size/L

#2694 fix incorrect error log
  pkg/controller/user/user_controller.go
Labels: approved, dco-signoff: yes, kind/cleanup, size/XS

#2705 fix websocket lost query string bug
  pkg/apiserver/dispatch/dispatch.go
  pkg/apiserver/filters/requestinfo.go
Labels: approved, dco-signoff: yes, kind/bug, size/M

#2688 Allow global admins to view deleted namespace logs
  pkg/api/logging/v1alpha2/types.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/models/tenant/tenant.go
  pkg/simple/client/logging/elasticsearch/api_body.go
  pkg/simple/client/logging/elasticsearch/api_body_test.go
  pkg/simple/client/logging/elasticsearch/testdata/api_body_8.json
  pkg/simple/client/logging/interface.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#2703 add parameter for to_json
  pkg/simple/client/devops/pipeline.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2706 fix request info resource scope
  pkg/apiserver/request/requestinfo.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#2708 fix tenant resource list API
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/kapis/tenant/v1alpha2/register.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#2672 make ws admin can be aware of anything happened in its workspace.
  pkg/apiserver/apiserver.go
  pkg/apiserver/auditing/types.go
  pkg/apiserver/auditing/types_test.go
  pkg/models/auditing/events.go
  pkg/models/tenant/tenant.go
  pkg/simple/client/auditing/elasticsearch/elasticsearch.go
  pkg/simple/client/auditing/interface.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#2712 sanitizer error message to avoid emitting xss error message
  pkg/api/utils.go
Labels: approved, dco-signoff: yes, kind/bug, size/S

#2685 legacy API compatibility
  pkg/controller/devopsproject/devopsproject_controller.go
  pkg/controller/devopsproject/devopsproject_controller_test.go
  pkg/kapis/devops/v1alpha3/handler.go
  pkg/kapis/iam/v1alpha2/handler.go
  pkg/models/devops/devops.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2718 fix bug auditing can't search anything using keyword with '-' for fuzzy
  pkg/simple/client/auditing/elasticsearch/elasticsearch.go
  pkg/simple/client/auditing/elasticsearch/elasticsearch_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2728 add missing federated resources
  pkg/models/resources/v1alpha3/federatedingress/federatedingresses.go
  pkg/models/resources/v1alpha3/federatedstatefulset/federatedstatefulsets.go
  pkg/models/resources/v1alpha3/networkpolicy/networkpolicies.go
  pkg/models/resources/v1alpha3/node/nodes.go
  pkg/models/resources/v1alpha3/resource/resource.go
Labels: approved, dco-signoff: yes, kind/bug, size/M

#2727 add more details info for jenkins api
  pkg/simple/client/devops/jenkins/pipeline.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S
