Repository kubesphere/kubesphere, pull requests merged in 2020-01, with the labels that each got.

#1677 devops dev guides
  docs/en/concepts-and-designs/README.md
  docs/en/concepts-and-designs/devops-pipeline-overview.md
  docs/en/guides/Kubesphere-code-layout.md
  docs/en/guides/README.md
  docs/images/devops-api.png
Labels: approved, area/devops, lgtm, size/L

#1750 refactor resources API
  pkg/apiserver/devops/member.go
  pkg/apiserver/iam/am.go
  pkg/apiserver/iam/im.go
  pkg/apiserver/iam/workspaces.go
  pkg/apiserver/openpitrix/applications.go
  pkg/apiserver/openpitrix/apps.go
  pkg/apiserver/openpitrix/categories.go
  pkg/apiserver/openpitrix/repos.go
  pkg/apiserver/resources/resources.go
  pkg/apiserver/tenant/tenant.go
  pkg/models/openpitrix/applications.go
  pkg/models/openpitrix/apps.go
  pkg/models/openpitrix/categories.go
  pkg/models/openpitrix/repos.go
  pkg/models/openpitrix/types.go
  pkg/models/resources/appplications.go
  pkg/models/resources/clusterroles.go
  pkg/models/resources/configmaps.go
  pkg/models/resources/cronjobs.go
  pkg/models/resources/daemonsets.go
  pkg/models/resources/deployments.go
  pkg/models/resources/horizontalpodautoscalers.go
  pkg/models/resources/ingresses.go
  pkg/models/resources/jobs.go
  pkg/models/resources/namespaces.go
  pkg/models/resources/nodes.go
  pkg/models/resources/persistentvolumeclaims.go
  pkg/models/resources/pods.go
  pkg/models/resources/resources.go
  pkg/models/resources/roles.go
  pkg/models/resources/s2ibuilder.go
  pkg/models/resources/s2ibuildertemplate.go
  pkg/models/resources/s2irun.go
  pkg/models/resources/secrets.go
  pkg/models/resources/services.go
  pkg/models/resources/statefulsets.go
  pkg/models/resources/storageclasses.go
  pkg/models/resources/workspaces.go
  pkg/models/tenant/workspaces.go
  pkg/server/params/params.go
Labels: approved, kind/bug, lgtm, size/XXL

#1753 refine readme guide, remove R icon in logo
  README.md
  README_zh.md
  docs/images/kubesphere-logo.png
  docs/roadmap.md
Labels: approved, kind/documentation, lgtm, size/L

#1771 Update .travis.yml
  .travis.yml
Labels: approved, size/XS

#1757 Add API for setting default storage class
  pkg/apiserver/resources/storage.go
  pkg/kapis/resources/v1alpha2/register.go
  pkg/models/storage/storage.go
Labels: kind/feature, size/M

#1766 fix typo in roadmap.md, add new diagram, refine README
  README.md
  README_zh.md
  docs/images/architecture-zh.png
  docs/images/kubesphere-platform-overview.png
  docs/roadmap.md
Labels: size/M

#1767 filter out metrics with empty resource_name when sorting
  pkg/models/metrics/util.go
  pkg/models/metrics/util_test.go
Labels: approved, kind/bug, lgtm, size/L

#1772 Add API for setting default storage class (#1757)
  pkg/apis/resources/v1alpha2/register.go
  pkg/apiserver/resources/storage.go
  pkg/models/storage/storage.go
Labels: approved, kind/feature, lgtm, size/M

#1761 fix choice param parse
  pkg/models/devops/project_pipeline.go
  pkg/models/devops/project_pipeline_test.go
Labels: approved, area/devops, kind/bug, lgtm, size/L

#1763 use CSR to generate user client certificate
  go.mod
  pkg/models/kubeconfig/internal/pki_helpers.go
  pkg/models/kubeconfig/kubeconfig.go
Labels: approved, kind/bug, lgtm, size/L

#1628 remove schema if required and add check SSL
  pkg/apiserver/registries/registries.go
  pkg/models/registries/image.go
  pkg/models/registries/image_test.go
  pkg/models/registries/manifest_test.go
  pkg/models/registries/registry_client.go
  pkg/models/registries/registry_client_test.go
  pkg/models/registries/token_test.go
Labels: approved, lgtm, size/L

#1774 Fix/image
  pkg/apiserver/registries/registries.go
  pkg/models/registries/image.go
  pkg/models/registries/image_test.go
  pkg/models/registries/manifest_test.go
  pkg/models/registries/registry_client.go
  pkg/models/registries/registry_client_test.go
  pkg/models/registries/token_test.go
Labels: approved, lgtm, size/L

#1781 [release-2.1] Cherry pick from master branch
  pkg/models/routers/routers.go
Labels: approved, kind/bug, size/M
