Repository kubesphere/kubesphere, pull requests merged in 2020-03, with the labels that each got.

#1934 refine readme, update download url to 2.1.1
  README.md
  README_zh.md
  docs/en/guides/Development-workflow.md
Labels: approved, kind/documentation, lgtm, size/L

#1794 [WIP] logging refactor
  cmd/ks-apiserver/app/options/options.go
  hack/generate_client.sh
  pkg/api/logging/v1alpha2/types.go
  pkg/apis/addtoscheme_logging_v1alpha2.go
  pkg/apis/logging/group.go
  pkg/apis/logging/v1alpha2/doc.go
  pkg/apis/logging/v1alpha2/fluentbit_types.go
  pkg/apis/logging/v1alpha2/fluentbit_types_test.go
  pkg/apis/logging/v1alpha2/register.go
  pkg/apis/logging/v1alpha2/v1alpha2_suite_test.go
  pkg/apis/logging/v1alpha2/zz_generated.deepcopy.go
  pkg/apiserver/logging/logging.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/logging/v1alpha2/doc.go
  pkg/client/clientset/versioned/typed/logging/v1alpha2/fake/doc.go
  pkg/client/clientset/versioned/typed/logging/v1alpha2/fake/fake_fluentbit.go
  pkg/client/clientset/versioned/typed/logging/v1alpha2/fake/fake_logging_client.go
  pkg/client/clientset/versioned/typed/logging/v1alpha2/fluentbit.go
  pkg/client/clientset/versioned/typed/logging/v1alpha2/generated_expansion.go
  pkg/client/clientset/versioned/typed/logging/v1alpha2/logging_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/logging/interface.go
  pkg/client/informers/externalversions/logging/v1alpha2/fluentbit.go
  pkg/client/informers/externalversions/logging/v1alpha2/interface.go
  pkg/client/listers/logging/v1alpha2/expansion_generated.go
  pkg/client/listers/logging/v1alpha2/fluentbit.go
  pkg/constants/constants.go
  pkg/kapis/kapis.go
  pkg/kapis/logging/install/install.go
  pkg/kapis/logging/v1alpha2/handler.go
  pkg/kapis/logging/v1alpha2/helper.go
  pkg/kapis/logging/v1alpha2/register.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/models/log/constants.go
  pkg/models/log/logcollector.go
  pkg/models/log/logcrd.go
  pkg/models/log/types.go
  pkg/models/logging/logging.go
  pkg/server/config/config.go
  pkg/server/config/config_test.go
  pkg/simple/client/elasticsearch/esclient.go
  pkg/simple/client/elasticsearch/interface.go
  pkg/simple/client/factory.go
  pkg/simple/client/logging/elasticsearch/api_body.go
  pkg/simple/client/logging/elasticsearch/api_body_test.go
  pkg/simple/client/logging/elasticsearch/api_body_types.go
  pkg/simple/client/logging/elasticsearch/elasticsearch.go
  pkg/simple/client/logging/elasticsearch/elasticsearch_test.go
  pkg/simple/client/logging/elasticsearch/options.go
  pkg/simple/client/logging/elasticsearch/versions/v5/v5.go
  pkg/simple/client/logging/elasticsearch/versions/v6/v6.go
  pkg/simple/client/logging/elasticsearch/versions/v7/v7.go
  pkg/simple/client/logging/interface.go
  pkg/simple/client/logging/logging.go
  pkg/simple/client/logging/query.go
Labels: do-not-merge/work-in-progress, kind/api-change, kind/cleanup, size/XXL

#1751 [WIP] monitoring refactor
  cmd/ks-apiserver/app/options/options.go
  pkg/api/monitoring/v1alpha2/types.go
  pkg/apiserver/monitoring/monitoring.go
  pkg/kapis/kapis.go
  pkg/kapis/monitoring/install/install.go
  pkg/kapis/monitoring/v1alpha2/handler.go
  pkg/kapis/monitoring/v1alpha2/helper.go
  pkg/kapis/monitoring/v1alpha2/register.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/models/metrics/constants.go
  pkg/models/metrics/metrics.go
  pkg/models/metrics/namespaces.go
  pkg/models/metrics/types.go
  pkg/models/metrics/util.go
  pkg/models/monitoring/monitoring.go
  pkg/models/monitoring/namespaces.go
  pkg/models/monitoring/sort_page.go
  pkg/server/config/config.go
  pkg/server/config/config_test.go
  pkg/simple/client/factory.go
  pkg/simple/client/monitoring/interface.go
  pkg/simple/client/monitoring/named_metrics.go
  pkg/simple/client/monitoring/prometheus.go
  pkg/simple/client/monitoring/prometheus/prometheus.go
  pkg/simple/client/monitoring/prometheus/prometheus_options.go
  pkg/simple/client/monitoring/prometheus/promql_templates.go
  pkg/simple/client/monitoring/prometheus_options.go
  pkg/simple/client/monitoring/prometheus_test.go
  pkg/simple/client/monitoring/query_options.go
  pkg/simple/client/prometheus/prometheus.go
Labels: do-not-merge/work-in-progress, kind/api-change, size/XXL

#1940 Fix little year typo in the README
  README.md
Labels: approved, kind/documentation, lgtm, size/XS

#1944 Openapi gen tools
  Makefile
  api/api-rules/violation_exceptions.list
  api/openapi-spec/swagger.json
  pkg/apis/devops/v1alpha1/openapi_generated.go
  pkg/apis/network/v1alpha1/openapi_generated.go
Labels: kind/cleanup, size/XXL

#1948 move apigateway into apiserver
  cmd/ks-apiserver/app/options/options.go
  cmd/ks-apiserver/app/server.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/authentication/token_authenticator.go
  pkg/apiserver/dispatch/dispatch.go
  pkg/apiserver/filters/authentication.go
  pkg/apiserver/filters/authorization.go
  pkg/apiserver/filters/dispatch.go
  pkg/apiserver/filters/kubeapiserver.go
  pkg/apiserver/filters/requestinfo.go
  pkg/apiserver/request/requestinfo.go
  pkg/apiserver/server/handler.go
  pkg/apiserver/servicemesh/metrics/handlers.go
  pkg/apiserver/servicemesh/tracing/handlers.go
  pkg/kapis/resources/v1alpha3/register.go
  pkg/kapis/servicemesh/metrics/v1alpha2/handler.go
  pkg/kapis/servicemesh/metrics/v1alpha2/register.go
  pkg/models/resources/v1alpha2/resource/resources.go
  pkg/models/routers/routers.go
  pkg/server/filter/logging.go
  pkg/server/server.go
  vendor/github.com/mxk/go-flowrate/LICENSE
  vendor/github.com/mxk/go-flowrate/flowrate/flowrate.go
  vendor/github.com/mxk/go-flowrate/flowrate/io.go
  vendor/github.com/mxk/go-flowrate/flowrate/util.go
  vendor/k8s.io/apimachinery/pkg/util/proxy/dial.go
  vendor/k8s.io/apimachinery/pkg/util/proxy/doc.go
  vendor/k8s.io/apimachinery/pkg/util/proxy/transport.go
  vendor/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
  vendor/modules.txt
Labels: approved, kind/api-change, kind/cleanup, size/XXL

#1949 Add more tests
  cmd/ks-apiserver/app/options/options.go
  pkg/apiserver/authentication/token_authenticator.go
  pkg/apiserver/config/config.go
  pkg/apiserver/dispatch/dispatch.go
  pkg/apiserver/filters/authentication.go
  pkg/informers/informers.go
  pkg/simple/client/cache/cache.go
  pkg/simple/client/cache/simple_cache.go
  pkg/simple/client/cache/simple_cache_test.go
  pkg/simple/client/ldap/interface.go
  pkg/simple/client/ldap/ldap.go
  pkg/simple/client/ldap/simple_ldap.go
  pkg/simple/client/ldap/simple_ldap_test.go
Labels: approved, kind/api-change, kind/bug, kind/documentation, size/L

#1950 refactor authentication
  .travis.yml
  cmd/ks-apiserver/app/options/options.go
  hack/docker_build.sh
  pkg/api/iam/authenticate.go
  pkg/api/iam/token/issuer.go
  pkg/api/iam/token/jwt.go
  pkg/api/iam/token/jwt_test.go
  pkg/api/iam/token/user.go
  pkg/api/iam/user.go
  pkg/api/utils.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/authentication/authenticators/jwttoken/jwt_token.go
  pkg/apiserver/authentication/request/anonymous.go
  pkg/apiserver/authentication/token/token.go
  pkg/apiserver/authentication/token_authenticator.go
  pkg/kapis/devops/v1alpha2/member.go
  pkg/kapis/devops/v1alpha2/pipeline_sonar.go
  pkg/kapis/devops/v1alpha2/project.go
  pkg/kapis/devops/v1alpha2/project_credential.go
  pkg/kapis/devops/v1alpha2/project_pipeline.go
  pkg/kapis/devops/v1alpha2/s2ibinary.go
  pkg/kapis/iam/v1alpha2/handler.go
  pkg/kapis/logging/v1alpha2/handler.go
  pkg/kapis/monitoring/v1alpha2/handler.go
  pkg/kapis/openpitrix/v1/handler.go
  pkg/kapis/resources/v1alpha2/handler.go
  pkg/kapis/resources/v1alpha3/handler.go
  pkg/kapis/servicemesh/metrics/v1alpha2/handler.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/models/iam/im.go
  pkg/simple/client/ldap/simple_ldap.go
  pkg/utils/jwtutil/jwt.go
Labels: approved, kind/api-change, kind/cleanup, kind/design, size/XL

#1951 refactor authentication
  cmd/ks-apiserver/app/options/options.go
  cmd/ks-apiserver/app/server.go
  pkg/api/iam/authenticate.go
  pkg/apigateway/caddy-plugin/authenticate/auto_load.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/config/config.go
  pkg/apiserver/config/config_test.go
  pkg/models/iam/im.go
  pkg/simple/client/cache/options.go
  pkg/simple/client/cache/redis.go
  pkg/simple/client/ldap/options.go
Labels: approved, size/L

#1965 move to github actions
  .github/workflows/build.yml
  .travis.yml
  hack/docker_build.sh
Labels: approved, kind/feature, size/L

#1967 refine readme, remove the out-of-date docs
  CONTRIBUTING.md
  README.md
  README_zh.md
  docs/cla.md
  docs/en/concepts-and-designs/README.md
  docs/en/concepts-and-designs/devops-pipeline-overview.md
  docs/en/concepts-and-designs/kubesphere-logging.md
  docs/en/concepts-and-designs/kubesphere-monitoring.md
  docs/en/concepts-and-designs/overview.md
  docs/en/concepts-and-designs/s2i_b2i_overview.md
  docs/en/guides/Development-workflow.md
  docs/en/guides/How-to-build.md
  docs/en/guides/How-to-connect-remote-service.md
  docs/en/guides/How-to-run-KubeSphere-core.md
  docs/en/guides/Kubesphere-code-layout.md
  docs/en/guides/README.md
  docs/en/guides/code-of-conduct.md
  docs/en/guides/kubesphere-logging-devlopment-guide.md
  docs/en/guides/kubesphere-monitoring-development-guide.md
  docs/en/guides/pull-requests.md
  docs/en/guides/screenshots.md
  docs/images/app-store.png
  docs/images/architecture.png
  docs/images/cicd.png
  docs/images/console.png
  docs/images/kubesphere-platform-overview.png
  docs/images/project.png
Labels: approved, kind/documentation, lgtm, size/XXL

#1972 add workflow to dev branch
  .github/workflows/build.yml
Labels: approved, size/M

#1974 move agent crd to kubesphere
  hack/generate_client.sh
  pkg/apis/addtoscheme_tower_v1alpha1.go
  pkg/apis/tower/group.go
  pkg/apis/tower/v1alpha1/agent_types.go
  pkg/apis/tower/v1alpha1/doc.go
  pkg/apis/tower/v1alpha1/register.go
  pkg/apis/tower/v1alpha1/zz_generated.deepcopy.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/dispatch/dispatch.go
  pkg/apiserver/filters/dispatch.go
  pkg/apiserver/request/requestinfo.go
  pkg/apiserver/request/requestinfo_test.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/tower/v1alpha1/agent.go
  pkg/client/clientset/versioned/typed/tower/v1alpha1/doc.go
  pkg/client/clientset/versioned/typed/tower/v1alpha1/fake/doc.go
  pkg/client/clientset/versioned/typed/tower/v1alpha1/fake/fake_agent.go
  pkg/client/clientset/versioned/typed/tower/v1alpha1/fake/fake_tower_client.go
  pkg/client/clientset/versioned/typed/tower/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/tower/v1alpha1/tower_client.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/tower/interface.go
  pkg/client/informers/externalversions/tower/v1alpha1/agent.go
  pkg/client/informers/externalversions/tower/v1alpha1/interface.go
  pkg/client/listers/tower/v1alpha1/agent.go
  pkg/client/listers/tower/v1alpha1/expansion_generated.go
Labels: approved, kind/documentation, kind/feature, size/L

#1975 Update README.md
  README.md
Labels: approved, kind/documentation, lgtm, size/M
