Repository kubesphere/kubesphere, pull requests merged in 2020-09, with the labels that each got.

#2968 Update build.yml
  .github/workflows/build.yml
Labels: approved, dco-signoff: no, size/XS

#2967 [release-3.0] Backport 2931 2934 from master branch
  pkg/apis/devops/v1alpha3/credential_types.go
  pkg/controller/devopscredential/devopscredential_controller.go
  pkg/models/devops/devops.go
  pkg/simple/client/devops/jenkins/credential_test.go
  pkg/simple/client/devops/pipeline.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#2971 update readme to v3.0.0.
  README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/L

#2972 update Readme-zh to v3.0.0
  README.md
  README_zh.md
Labels: dco-signoff: yes, size/L

#2976 fix: add nil check for storage class name
  pkg/models/resources/v1alpha2/storageclass/storageclasses.go
  pkg/models/resources/v1alpha2/storageclass/storageclasses_test.go
Labels: dco-signoff: yes, kind/bug, lgtm, size/L

#2984 optimize docker build
  .dockerignore
  build/ks-controller-manager/Dockerfile
Labels: approved, lgtm, size/XS

#2987 Add OpenPitrix API in swagger file
  api/ks-openapi-spec/swagger.json
  pkg/kapis/openpitrix/v1/register.go
  tools/cmd/doc-gen/main.go
Labels: approved, kind/documentation, lgtm, size/XXL

#2992 add stone as reviewer
  OWNERS
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS
