Repository kubesphere/kubesphere, pull requests merged in 2020-05, with the labels that each got.

#2043 fix generation bug
  pkg/controller/cluster/cluster_controller.go
  pkg/kapis/cluster/v1alpha1/handler.go
  pkg/kapis/cluster/v1alpha1/handler_test.go
Labels: approved, kind/bug, size/M

#2041 add k8s networkpolicy resource
  pkg/apiserver/apiserver.go
  pkg/models/resources/v1alpha3/networkpolicy/networkpolicies.go
  pkg/models/resources/v1alpha3/networkpolicy/networkpolicies_test.go
  pkg/models/resources/v1alpha3/resource/resource.go
Labels: approved, lgtm, size/L

#2047 fix generation bug
  pkg/kapis/cluster/v1alpha1/handler.go
  pkg/kapis/cluster/v1alpha1/handler_test.go
Labels: approved, kind/bug, size/M

#2045 fuzzy matching name by default
  pkg/kapis/resources/v1alpha3/handler.go
Labels: approved, kind/api-change, lgtm, size/XS

#2048 fix generation bug
  pkg/simple/client/multicluster/options.go
Labels: approved, kind/bug, size/XS

#2049 fix cluster controller bug
  pkg/controller/cluster/cluster_controller.go
Labels: approved, kind/bug, size/XS

#2051 fix list namespaces
  pkg/apiserver/filters/kubeapiserver.go
  pkg/models/iam/am/am.go
  pkg/models/resources/v1alpha3/interface.go
  pkg/models/tenant/tenant.go
  pkg/models/tenant/tenent_test.go
Labels: approved, kind/bug, lgtm, size/L

#2058 fix websocket bug
  pkg/apiserver/filters/kubeapiserver.go
  pkg/models/tenant/tenent_test.go
Labels: approved, kind/bug, size/M

#2066 add notification apis
  pkg/apiserver/apiserver.go
  pkg/apiserver/config/config_test.go
  pkg/kapis/alerting/v1/register.go
  pkg/kapis/generic/generic.go
  pkg/kapis/generic/generic_test.go
  pkg/kapis/notification/v1/register.go
Labels: approved, kind/api-change, kind/feature, size/L

#2070 fix proxy bug
  pkg/kapis/generic/generic.go
Labels: approved, kind/bug

#2068 init opClient
  cmd/ks-apiserver/app/options/options.go
  pkg/kapis/openpitrix/v1/register.go
Labels: approved, lgtm, size/S

#2065 fix devops create and delete bug
  pkg/controller/devopsproject/devopsproject_controller.go
  pkg/controller/devopsproject/devopsproject_controller_test.go
Labels: approved, area/devops, kind/bug, lgtm, size/S

#2071 add pipeline api
  pkg/apis/devops/v1alpha3/pipeline_types.go
Labels: approved, kind/feature, lgtm, size/XS

#2074 monitoring: update builtin metrics
  pkg/models/monitoring/sort_page.go
  pkg/simple/client/monitoring/prometheus/promql.go
  pkg/simple/client/monitoring/prometheus/testdata/promqls.go
Labels: approved, kind/bug, lgtm, size/L

#2078 Add requests to nodes
  go.mod
  pkg/kapis/resources/v1alpha3/register.go
  pkg/models/resources/v1alpha3/node/nodes.go
  pkg/models/resources/v1alpha3/node/nodes_test.go
  pkg/models/resources/v1alpha3/resource/resource.go
  vendor/k8s.io/kubectl/LICENSE
  vendor/k8s.io/kubectl/pkg/util/resource/resource.go
  vendor/modules.txt
Labels: approved, kind/feature, size/XL

#2069 add events search apis
  api/ks-openapi-spec/swagger.json
  cmd/ks-apiserver/app/options/options.go
  cmd/ks-apiserver/app/options/validation.go
  pkg/api/events/v1alpha1/types.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/config/config.go
  pkg/apiserver/config/config_test.go
  pkg/constants/constants.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/models/events/events.go
  pkg/models/tenant/tenant.go
  pkg/models/tenant/tenent_test.go
  pkg/simple/client/events/elasticsearch/clients.go
  pkg/simple/client/events/elasticsearch/elasticsearch.go
  pkg/simple/client/events/elasticsearch/elasticsearch_test.go
  pkg/simple/client/events/elasticsearch/options.go
  pkg/simple/client/events/interface.go
  tools/cmd/doc-gen/main.go
Labels: approved, kind/feature, lgtm, size/XXL

#2076 api: list metric labels and values
  pkg/kapis/monitoring/v1alpha3/handler.go
  pkg/kapis/monitoring/v1alpha3/helper.go
  pkg/kapis/monitoring/v1alpha3/register.go
  pkg/models/monitoring/monitoring.go
  pkg/models/monitoring/types.go
  pkg/simple/client/monitoring/interface.go
  pkg/simple/client/monitoring/prometheus/prometheus.go
  pkg/simple/client/monitoring/prometheus/prometheus_test.go
  pkg/simple/client/monitoring/prometheus/testdata/labels-error-prom.json
  pkg/simple/client/monitoring/prometheus/testdata/labels-error-res.json
  pkg/simple/client/monitoring/prometheus/testdata/labels-prom.json
  pkg/simple/client/monitoring/prometheus/testdata/labels-res.json
Labels: approved, kind/feature, lgtm, size/L

#2079 monitoring: update node_pod_quota
  pkg/kapis/monitoring/v1alpha3/register.go
  pkg/simple/client/monitoring/prometheus/promql.go
  pkg/simple/client/monitoring/prometheus/promql_test.go
  pkg/simple/client/monitoring/prometheus/testdata/promqls.go
Labels: approved, kind/bug, lgtm, size/S

#2084 remove specific version of generic proxy server
  pkg/kapis/alerting/v1/register.go
  pkg/kapis/notification/v1/register.go
Labels: approved, kind/bug, size/XS

#2085 add unit test for job controller
  pkg/controller/job/job_controller_test.go
  pkg/controller/s2ibinary/s2ibinary_controller_test.go
Labels: approved, kind/bug, lgtm, size/L

#2089 typo fix
  README_zh.md
Labels: approved, kind/documentation, lgtm, size/XS

#2080 fix namespace networkpolicy
  pkg/controller/network/nsnetworkpolicy/controller.go
  pkg/controller/network/nsnetworkpolicy/nsnetworkpolicy_test.go
  pkg/controller/network/provider/ns_k8s.go
  pkg/controller/network/types.go
Labels: approved, kind/bug, kind/feature, lgtm, size/L

#2093 params key error: app -> app_id
  pkg/models/openpitrix/apps.go
Labels: approved, lgtm, size/XS

#2097 bump kiali version
  go.mod
  go.sum
  vendor/github.com/kiali/kiali/business/workloads.go
  vendor/github.com/kiali/kiali/kubernetes/cache.go
  vendor/github.com/kiali/kiali/kubernetes/client.go
  vendor/github.com/kiali/kiali/kubernetes/kubernetes_service.go
  vendor/github.com/kiali/kiali/kubernetes/kubetest/mock.go
  vendor/github.com/kiali/kiali/models/workload.go
  vendor/modules.txt
Labels: approved, size/XXL

#2096 Fix grammer errors in code comments
  build/hypersphere/Dockerfile
  build/ks-apiserver/Dockerfile
  build/ks-controller-manager/Dockerfile
  cmd/controller-manager/app/helper.go
  cmd/ks-apiserver/app/server.go
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  docs/powered-by-kubesphere.md
  docs/roadmap.md
  hack/docker_build.sh
  hack/generate_client.sh
Labels: approved, lgtm, size/M

#2099 fix namespace networkpolicy
  pkg/controller/network/nsnetworkpolicy/controller.go
  pkg/controller/network/provider/ns_k8s.go
Labels: approved, kind/bug, lgtm, size/M

#2072 fix pipeline bugs
  pkg/apis/devops/v1alpha3/credential_types.go
  pkg/apiserver/apiserver.go
  pkg/controller/devopscredential/devopscredential_controller.go
  pkg/controller/devopscredential/devopscredential_controller_test.go
  pkg/controller/pipeline/pipeline_controller.go
  pkg/controller/s2ibinary/s2ibinary_controller_test.go
  pkg/kapis/devops/v1alpha2/handler.go
  pkg/kapis/devops/v1alpha3/handler.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/models/devops/devops.go
  pkg/models/devops/devops_test.go
  pkg/models/resources/v1alpha3/node/nodes_test.go
  pkg/simple/client/devops/jenkins/credential.go
  pkg/simple/client/devops/jenkins/jenkins.go
  pkg/simple/client/devops/jenkins/pipeline.go
  pkg/simple/client/devops/pipeline.go
Labels: approved, area/devops, lgtm, size/XL

#2104 monitor: add platform metrics
  pkg/apiserver/apiserver.go
  pkg/constants/constants.go
  pkg/kapis/monitoring/v1alpha3/handler.go
  pkg/kapis/monitoring/v1alpha3/helper_test.go
  pkg/kapis/monitoring/v1alpha3/register.go
  pkg/models/monitoring/monitoring.go
  pkg/models/monitoring/named_metrics.go
  tools/cmd/doc-gen/main.go
Labels: approved, lgtm, size/L

#2107 add .git to .dockerfileignore
  .dockerignore
Labels: approved, kind/optimization, lgtm, size/XS

#2110 fix registry public hub search
  pkg/models/registries/registries.go
Labels: approved, kind/bug, size/S

#2108 fix project info
  pkg/apis/devops/OWNERS
  pkg/models/devops/OWNERS
  pkg/simple/client/devops/OWNERS
Labels: approved, kind/documentation, lgtm, size/XS

#2106 fix user's resource lifecycle
  cmd/controller-manager/app/controllers.go
  pkg/constants/constants.go
  pkg/controller/certificatesigningrequest/certificatesigningrequest_controller.go
  pkg/controller/clusterrolebinding/clusterrolebinding_controller.go
  pkg/kapis/resources/v1alpha2/handler.go
  pkg/models/kubeconfig/kubeconfig.go
  pkg/models/kubectl/kubectl.go
Labels: approved, lgtm, size/L

#2100 logging: integrate new IAM
  pkg/api/logging/v1alpha2/types.go
  pkg/apiserver/apiserver.go
  pkg/kapis/logging/group.go
  pkg/kapis/logging/v1alpha2/handler.go
  pkg/kapis/logging/v1alpha2/helper.go
  pkg/kapis/logging/v1alpha2/register.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/models/tenant/tenant.go
  pkg/models/tenant/tenent_test.go
  pkg/simple/client/logging/elasticsearch/api_body.go
  pkg/simple/client/logging/elasticsearch/api_body_test.go
  pkg/simple/client/logging/elasticsearch/elasticsearch.go
  pkg/simple/client/logging/elasticsearch/elasticsearch_test.go
  pkg/simple/client/logging/elasticsearch/testdata/api_body_1.json
  pkg/simple/client/logging/elasticsearch/testdata/api_body_2.json
  pkg/simple/client/logging/elasticsearch/testdata/api_body_3.json
  pkg/simple/client/logging/elasticsearch/testdata/api_body_4.json
  pkg/simple/client/logging/elasticsearch/testdata/api_body_5.json
  pkg/simple/client/logging/elasticsearch/testdata/api_body_6.json
  pkg/simple/client/logging/elasticsearch/testdata/es6_detect_version_major_200.json
  pkg/simple/client/logging/elasticsearch/testdata/es6_get_current_stats_200.json
  pkg/simple/client/logging/elasticsearch/testdata/es6_get_current_stats_404.json
  pkg/simple/client/logging/elasticsearch/testdata/es7_count_logs_by_interval_200.json
  pkg/simple/client/logging/elasticsearch/testdata/es7_count_logs_by_interval_400.json
  pkg/simple/client/logging/elasticsearch/testdata/es7_count_logs_by_interval_404.json
  pkg/simple/client/logging/elasticsearch/testdata/es7_detect_version_major_200.json
  pkg/simple/client/logging/elasticsearch/testdata/es7_get_current_stats_200.json
  pkg/simple/client/logging/elasticsearch/testdata/es7_get_current_stats_404.json
  pkg/simple/client/logging/elasticsearch/testdata/es7_search_logs_200.json
  pkg/simple/client/logging/elasticsearch/testdata/es7_search_logs_200_result.json
  pkg/simple/client/logging/elasticsearch/versions/v5/v5.go
  pkg/simple/client/logging/elasticsearch/versions/v6/v6.go
  pkg/simple/client/logging/elasticsearch/versions/v7/v7.go
  pkg/simple/client/logging/interface.go
  tools/cmd/doc-gen/main.go
Labels: approved, kind/cleanup, kind/feature, lgtm, size/XXL

#2119 add license for devops
  pkg/apis/devops/crdinstall/install.go
  pkg/apis/devops/group.go
  pkg/apis/devops/v1alpha1/doc.go
  pkg/apis/devops/v1alpha1/openapi_generated.go
  pkg/apis/devops/v1alpha1/register.go
  pkg/apis/devops/v1alpha1/s2ibinary_types.go
  pkg/apis/devops/v1alpha1/s2ibinary_types_test.go
  pkg/apis/devops/v1alpha1/s2ibuilder_types.go
  pkg/apis/devops/v1alpha1/s2ibuilder_types_test.go
  pkg/apis/devops/v1alpha1/s2ibuildertemplate_types.go
  pkg/apis/devops/v1alpha1/s2ibuildertemplate_types_test.go
  pkg/apis/devops/v1alpha1/s2irun_types.go
  pkg/apis/devops/v1alpha1/s2irun_types_test.go
  pkg/apis/devops/v1alpha1/v1alpha1_suite_test.go
  pkg/apis/devops/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/devops/v1alpha3/credential_types.go
  pkg/apis/devops/v1alpha3/devopsproject_types.go
  pkg/apis/devops/v1alpha3/devopsproject_types_test.go
  pkg/apis/devops/v1alpha3/doc.go
  pkg/apis/devops/v1alpha3/openapi_generated.go
  pkg/apis/devops/v1alpha3/pipeline_types.go
  pkg/apis/devops/v1alpha3/pipeline_types_test.go
  pkg/apis/devops/v1alpha3/register.go
  pkg/apis/devops/v1alpha3/v1alpha3_suite_test.go
  pkg/apis/devops/v1alpha3/zz_generated.deepcopy.go
  pkg/kapis/devops/group.go
  pkg/kapis/devops/v1alpha2/devops.go
  pkg/kapis/devops/v1alpha2/handler.go
  pkg/kapis/devops/v1alpha2/pipeline_sonar.go
  pkg/kapis/devops/v1alpha2/register.go
  pkg/kapis/devops/v1alpha2/s2ibinary.go
  pkg/kapis/devops/v1alpha3/handler.go
  pkg/models/devops/common.go
  pkg/models/devops/devops.go
  pkg/models/devops/devops_test.go
  pkg/models/devops/jkerror.go
  pkg/models/devops/project.go
  pkg/models/devops/project_credential_handler.go
  pkg/models/devops/project_pipeline_sonar_handler.go
  pkg/models/devops/s2ibinary_handler.go
  pkg/models/devops/s2ibinary_handler_test.go
  pkg/models/git/OWNERS
  pkg/models/git/git.go
  pkg/models/git/git_test.go
Labels: approved, kind/cleanup, lgtm, size/L

#2120 remove consumes and produces on root webservice
  pkg/apiserver/runtime/runtime.go
Labels: approved, kind/bug, size/XS

#2118 Add license info in code file as a sample for devops compoment
  pkg/api/devops/v1alpha2/types.go
Labels: approved, kind/cleanup, lgtm, size/S

#2112 fix SecretRef nil
  pkg/kapis/resources/v1alpha2/handler.go
Labels: approved, kind/bug, lgtm, size/XS

#2114 monitor: fix platform-level statistics
  pkg/models/monitoring/monitoring.go
Labels: approved, kind/bug, lgtm, size/S

#2127 add version api
  .dockerignore
  build/ks-apiserver/Dockerfile
  go.mod
  pkg/apiserver/apiserver.go
  pkg/controller/cluster/cluster_controller.go
  pkg/kapis/cluster/v1alpha1/handler.go
  pkg/kapis/cluster/v1alpha1/handler_test.go
  pkg/kapis/cluster/v1alpha1/register.go
  pkg/kapis/version/register.go
  pkg/simple/client/k8s/kubernetes.go
  pkg/version/version.go
Labels: approved, size/L

#2126 fix events search
  pkg/models/tenant/tenant.go
  pkg/simple/client/events/elasticsearch/elasticsearch.go
Labels: approved, kind/bug, lgtm, size/M

#2117 modify devops api for tenant
  pkg/kapis/devops/v1alpha3/handler.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/models/devops/devops.go
Labels: approved, lgtm, size/L

#2135 add configmap default suffix
  pkg/models/routers/routers.go
Labels: approved, lgtm, size/XS

#2140 fix jaeger api endpoint bug
  cmd/ks-apiserver/app/server.go
  pkg/kapis/servicemesh/metrics/v1alpha2/handler.go
Labels: approved, kind/bug, size/S

#2134 config: remove prometheus secondary-endpoint flag
  pkg/apiserver/config/config.go
  pkg/apiserver/config/config_test.go
  pkg/simple/client/monitoring/prometheus/prometheus_options.go
Labels: approved, kind/cleanup, lgtm, size/S
