Repository kubesphere/kubesphere, pull requests merged in 2020-08, with the labels that each got.

#2719 initial role differentiation of DevOps project and namespace
  pkg/apis/iam/v1alpha2/types.go
  pkg/controller/namespace/namespace_controller.go
  pkg/models/resources/v1alpha3/role/roles.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#2729 add query parameter for devops credential
  pkg/kapis/devops/v1alpha3/handler.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/models/devops/devops.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#2733 fix missing cache federatedapplication
  pkg/apiserver/apiserver.go
Labels: approved, dco-signoff: yes, kind/bug, size/XS

#2730 remove LastAppliedConfig annotation after password encrypted
  pkg/controller/user/user_controller.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2751 fix some bugs
  build/ks-apiserver/Dockerfile
  pkg/apis/types/v1beta1/register.go
Labels: approved, dco-signoff: yes, kind/bug, size/S

#2753 rename stale bot configuration file name
  .github/stale.yaml
Labels: dco-signoff: yes, kind/bug

#2759 fix role patch API
  pkg/models/iam/am/am.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#2760 fix labelSelector not working
  pkg/models/tenant/tenant.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#2766 fix kubectl pod owner reference
  pkg/controller/clusterrolebinding/clusterrolebinding_controller.go
  pkg/models/kubectl/kubectl.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#2771 fix kubectl pod creation failed
  config/crds/iam.kubesphere.io_federatedrolebindings.yaml
  config/crds/iam.kubesphere.io_federatedroles.yaml
  config/crds/iam.kubesphere.io_federatedusers.yaml
  config/crds/tenant.kubesphere.io_federatedworkspaces.yaml
  config/crds/types.kubefed.io_federatednamespaces.yaml
  config/crds/types.kubefed.io_namespacetemplates.yaml
  pkg/models/kubectl/kubectl.go
Labels: dco-signoff: yes, kind/bug, size/XS

#2776 fix generated kubeconfig bug
  pkg/models/kubeconfig/kubeconfig.go
Labels: approved, dco-signoff: yes, kind/bug, size/XS

#2770 fix workspacetemplate patch API not working
  cmd/controller-manager/app/controllers.go
  pkg/apis/tenant/v1alpha2/workspacetemplate_types.go
  pkg/apis/tenant/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/types/v1beta1/federatedworkspace_types.go
  pkg/apis/types/v1beta1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/types/v1beta1/fake/fake_federatedworkspace.go
  pkg/client/clientset/versioned/typed/types/v1beta1/fake/fake_types_client.go
  pkg/client/clientset/versioned/typed/types/v1beta1/federatedworkspace.go
  pkg/client/clientset/versioned/typed/types/v1beta1/types_client.go
  pkg/client/informers/externalversions/types/v1beta1/federatedworkspace.go
  pkg/client/informers/externalversions/types/v1beta1/interface.go
  pkg/client/listers/types/v1beta1/expansion_generated.go
  pkg/client/listers/types/v1beta1/federatedworkspace.go
  pkg/controller/globalrole/globalrole_controller.go
  pkg/controller/namespace/namespace_controller.go
  pkg/controller/workspacerole/workspacerole.go
  pkg/controller/workspacetemplate/workspacetemplate_controller.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/models/tenant/tenant.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#2782 fix mistakenly caching federatedworkspace in non multicluster env
  pkg/controller/workspacetemplate/workspacetemplate_controller.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#2796 fix password modify logic
  pkg/kapis/iam/v1alpha2/handler.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#2821 fix member detail API
  pkg/kapis/iam/v1alpha2/handler.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#2798 fix: calulating days between two timestamps
  pkg/utils/esutil/esutil.go
  pkg/utils/esutil/esutil_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#2830 fix unable to setup webhook server under leader election
  cmd/controller-manager/app/server.go
  pkg/controller/storage/capability/capability_controller.go
Labels: approved, dco-signoff: yes, kind/bug, size/L

#2840 fix job search bug
  pkg/models/resources/v1alpha3/job/jobs.go
  pkg/models/resources/v1alpha3/resource/resource.go
Labels: approved, dco-signoff: yes, kind/bug, size/L

#2827 Bugfix: catch error from ParseConditions and refactor ParseConditions
  pkg/kapis/openpitrix/v1/handler.go
  pkg/server/params/params.go
  pkg/server/params/params_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#2839 fix: resources_filter not working for workload metric query
  pkg/simple/client/monitoring/prometheus/promql.go
  pkg/simple/client/monitoring/prometheus/testdata/promqls.go
Labels: approved, dco-signoff: yes, lgtm, size/XS

#2846 fix: exported logs are incomplete
  pkg/simple/client/logging/elasticsearch/elasticsearch.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#2852 fix: can't list pipeline if no global role assigned
  cmd/controller-manager/app/controllers.go
  pkg/controller/globalrolebinding/globalrolebinding_controller.go
  pkg/controller/user/user_controller.go
  pkg/controller/user/user_controller_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#2869 fix some swagger json errors
  Makefile
  api/api-rules/violation_exceptions.list
  api/ks-openapi-spec/swagger.json
  api/openapi-spec/swagger.json
  pkg/apis/cluster/v1alpha1/openapi_generated.go
  pkg/apis/devops/v1alpha1/openapi_generated.go
  pkg/apis/devops/v1alpha3/openapi_generated.go
  pkg/apis/network/v1alpha1/openapi_generated.go
  pkg/apis/servicemesh/v1alpha2/openapi_generated.go
  pkg/apis/tenant/v1alpha1/openapi_generated.go
  pkg/informers/null_informers.go
  pkg/kapis/devops/v1alpha2/register.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/kapis/iam/v1alpha2/register.go
  pkg/kapis/monitoring/v1alpha3/register.go
  pkg/kapis/servicemesh/metrics/v1alpha2/register.go
  pkg/kapis/servicemesh/metrics/v1alpha2/swagger-doc.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/kapis/terminal/v1alpha2/register.go
  tools/cmd/doc-gen/main.go
Labels: approved, dco-signoff: yes, kind/documentation, size/XXL

#2870 fix servicemesh controller nil pointer exception
  pkg/controller/storage/capability/capability_controller.go
  pkg/controller/virtualservice/util/util.go
Labels: approved, dco-signoff: yes, kind/bug, size/XS

#2871 fix: time skew in monitoring responses
  pkg/kapis/monitoring/v1alpha3/helper.go
  pkg/kapis/monitoring/v1alpha3/helper_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#2877 fix node resources requests not returned bug
  pkg/models/resources/v1alpha3/node/nodes.go
Labels: approved, dco-signoff: yes, kind/bug, size/M

#2892 fix servicemesh strategy not applied bug
  pkg/controller/virtualservice/virtualservice_controller.go
Labels: approved, dco-signoff: yes, kind/bug, size/S

#2898 fix jenkins download
  pkg/kapis/devops/v1alpha2/register.go
Labels: area/devops, dco-signoff: yes, size/XS

#2902 fix search node with invalid name bug
  pkg/models/resources/v1alpha3/node/nodes.go
Labels: approved, dco-signoff: yes, kind/bug, kind/cleanup, size/XS

#2907 fix: missing role template after upgrade
  pkg/controller/namespace/namespace_controller.go
  pkg/controller/workspacerole/workspacerole.go
  pkg/simple/client/k8s/options.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#2930 fix unauthorized if using token kubeconfig
  pkg/apiserver/dispatch/dispatch.go
Labels: approved, dco-signoff: yes, kind/bug, size/XS

#2931 fix crendential sync
  pkg/apis/devops/v1alpha3/credential_types.go
  pkg/controller/devopscredential/devopscredential_controller.go
  pkg/models/devops/devops.go
  pkg/simple/client/devops/jenkins/credential_test.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/S

#2934 fix: scm choices
  pkg/simple/client/devops/pipeline.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS
