Repository kubesphere/kubesphere, pull requests merged in 2021-07, with the labels that each got.

#4033 fix .dockerignore file ignores .git dir bug
  .dockerignore
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#4034 Fix failed to push docker images with a specified tag
  .github/workflows/build-multiarch.yaml
  .github/workflows/build.yml
Labels: approved, dco-signoff: yes, kind/flake, lgtm, size/XS

#4042 Change helm path
  pkg/simple/client/openpitrix/helmwrapper/helm_wrapper_linux.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#4044 Fix typo in kubesphere gateway template and bookstore sample
  config/ks-core/templates/ks-router-config.tpl
  config/ks-core/templates/sample-bookinfo-configmap.yaml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#4050 Update kind-action to v1.2.0
  .github/workflows/e2e-test.yml
Labels: approved, dco-signoff: yes, kind/bug, kind/failing-test, lgtm, size/XS

#4063 fix gofmt typo and spelling typo and shellcheck typo to pass the prow ci
  config/crds/devops.kubesphere.io_s2ibuilders.yaml
  docs/roadmap.md
  hack/build-scripts/get-etcd.sh
  hack/build-scripts/get-helm.sh
  hack/build-scripts/get-kubernetes.sh
  hack/build-scripts/get-kustomize.sh
  hack/build_e2e.sh
  hack/deploy-kubesphere.sh
  hack/docker_build.sh
  hack/docker_build_multiarch.sh
  hack/generate_certs.sh
  hack/generate_group.sh
  hack/gobuild.sh
  hack/init_env.sh
  hack/lib/version.sh
  hack/verify-shellcheck.sh
  pkg/controller/loginrecord/loginrecord_controller_test.go
  pkg/controller/namespace/namespace_controller_test.go
  pkg/controller/serviceaccount/serviceaccount_controller_test.go
  pkg/controller/storage/capability/capability_controller.go
  pkg/controller/workspace/workspace_controller_test.go
  pkg/controller/workspacerole/workspacerole_controller_test.go
  pkg/controller/workspacerolebinding/workspacerolebinding_controller_test.go
  pkg/controller/workspacetemplate/workspacetemplate_controller_test.go
  pkg/kapis/devops/v1alpha2/devops.go
  pkg/kapis/monitoring/v1alpha3/helper.go
  pkg/kapis/monitoring/v1alpha3/meter.go
  pkg/models/alerting/rules/utils_test.go
  pkg/models/devops/devops.go
  pkg/models/monitoring/monitoring.go
  pkg/models/monitoring/utils.go
  pkg/models/openpitrix/applications_test.go
  pkg/models/tenant/metering.go
  pkg/server/params/params.go
  pkg/simple/client/devops/jenkins/pipeline.go
  pkg/simple/client/devops/pipeline.go
  pkg/simple/client/monitoring/metricsserver/metricsserver.go
  pkg/simple/client/monitoring/metricsserver/metricsserver_test.go
  pkg/simple/client/network/ippool/ipam/ipam.go
  pkg/simple/client/openpitrix/helmwrapper/helm_wrapper.go
  staging/src/kubesphere.io/api/devops/v1alpha1/openapi_generated.go
  staging/src/kubesphere.io/api/devops/v1alpha1/s2ibuilder_types.go
  test/network/test.sh
Labels: approved, lgtm, release-note-none, size/L

#4073 fix make cross target failed
  hack/docker_build_multiarch.sh
Labels: approved, kind/failing-test, lgtm, release-note-none, size/XS

#4048 Add kiali client with authentication supports
  cmd/ks-apiserver/app/server.go
  pkg/apiserver/apiserver.go
  pkg/kapis/servicemesh/metrics/install/install.go
  pkg/kapis/servicemesh/metrics/v1alpha2/handler.go
  pkg/kapis/servicemesh/metrics/v1alpha2/register.go
  pkg/simple/client/kiali/client.go
  pkg/simple/client/kiali/client_test.go
  tools/cmd/doc-gen/main.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XL

#4095 go build with vendor by default
  Makefile
  hack/verify-spelling.sh
Labels: approved, kind/feature-request, lgtm, release-note-none, size/XS
