Repository kubesphere/kubesphere, pull requests merged in 2021-06, with the labels that each got.

#3902 fix servicemesh traffic governance
  config/crds/servicemesh.kubesphere.io_servicepolicies.yaml
  config/crds/servicemesh.kubesphere.io_strategies.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3919 change controller-gen crds source path
  Makefile
  config/crds/auditing.kubesphere.io_rules.yaml
  config/crds/auditing.kubesphere.io_webhooks.yaml
  config/crds/crd.projectcalico.org_blockaffinities.yaml
  config/crds/crd.projectcalico.org_ipamblocks.yaml
  config/crds/crd.projectcalico.org_ippools.yaml
  config/crds/istio-crds.yaml
  config/crds/istio_v1alpha3_destinationrule.yaml
  config/crds/istio_v1alpha3_gateway.yaml
  config/crds/istio_v1alpha3_virtualservice.yaml
  config/crds/monitoring.kubesphere.io_clusterdashboards.yaml
  config/crds/monitoring.kubesphere.io_dashboards.yaml
  config/crds/notification.kubesphere.io_configs.yaml
  config/crds/notification.kubesphere.io_notificationmanagers.yaml
  config/crds/notification.kubesphere.io_receivers.yaml
  config/crds/snapshot.storage.k8s.io_volumesnapshot.yaml
  config/crds/types.kubefed.io_federatedapplications.yaml
  config/crds/types.kubefed.io_federatedclusterrolebindings.yaml
  config/crds/types.kubefed.io_federatedclusterroles.yaml
  config/crds/types.kubefed.io_federatedconfigmaps.yaml
  config/crds/types.kubefed.io_federateddeployments.yaml
  config/crds/types.kubefed.io_federatedgroupbindings.yaml
  config/crds/types.kubefed.io_federatedgroups.yaml
  config/crds/types.kubefed.io_federatedingresses.yaml
  config/crds/types.kubefed.io_federatedjobs.yaml
  config/crds/types.kubefed.io_federatedlimitranges.yaml
  config/crds/types.kubefed.io_federatednamespaces.yaml
  config/crds/types.kubefed.io_federatednotificationconfigs.yaml
  config/crds/types.kubefed.io_federatednotificationreceivers.yaml
  config/crds/types.kubefed.io_federatedpersistentvolumeclaims.yaml
  config/crds/types.kubefed.io_federatedresourcequota.yaml
  config/crds/types.kubefed.io_federatedsecrets.yaml
  config/crds/types.kubefed.io_federatedservices.yaml
  config/crds/types.kubefed.io_federatedstatefulsets.yaml
  config/crds/types.kubefed.io_federatedusers.yaml
  config/crds/types.kubefed.io_federatedworkspacerolebindings.yaml
  config/crds/types.kubefed.io_federatedworkspaceroles.yaml
  config/crds/types.kubefed.io_federatedworkspaces.yaml
  config/crds/types.kubefed.io_genericfederatedresources.yaml
  config/crds/types.kubefed.io_genericoverrides.yaml
  config/crds/types.kubefed.io_genericplacements.yaml
  config/crds/types.kubefed.io_persistentvolumeclaimtemplates.yaml
  config/crds/types.kubefed.io_servicetemplates.yaml
  config/crds/types.kubefed.io_statefulsettemplates.yaml
  pkg/controller/notification/notification_controller_suite_test.go
  pkg/controller/notification/notification_controller_test.go
  pkg/models/resources/v1alpha3/clusterdashboard/clusterdashboard.go
  pkg/models/resources/v1alpha3/clusterdashboard/clusterdashboard_test.go
  pkg/models/resources/v1alpha3/dashboard/dashboard.go
  pkg/models/resources/v1alpha3/dashboard/dashboard_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#3894 Fix: nil pointer when enable HTTPS
  cmd/ks-apiserver/app/options/options.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#3896 create helm chart for ks-core
  Makefile
  config/ks-core/.helmignore
  config/ks-core/Chart.yaml
  config/ks-core/crds/.gitkeep
  config/ks-core/templates/NOTES.txt
  config/ks-core/templates/_helpers.tpl
  config/ks-core/templates/account.yaml
  config/ks-core/templates/ks-apiserver.yml
  config/ks-core/templates/ks-console-config.yml
  config/ks-core/templates/ks-console.yml
  config/ks-core/templates/ks-controller-manager.yaml
  config/ks-core/templates/ks-router-cm.yaml
  config/ks-core/templates/ks-router-config.tpl
  config/ks-core/templates/kubesphere-config.yaml
  config/ks-core/templates/kubesphere-controls-system.yaml
  config/ks-core/templates/sample-bookinfo-configmap.yaml
  config/ks-core/templates/serviceaccount.yaml
  config/ks-core/templates/webhook.yaml
  config/ks-core/values.yaml
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XXL

#3924 Add cherry_pick_pull.sh
  hack/cherry_pick_pull.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#3929 Fix the wrong version output of controller-manager
  cmd/controller-manager/app/server.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#3923 Automated cherry pick of #3796: Fix SelectorFromSet ignore errors and select everything
  pkg/controller/group/group_controller.go
  pkg/controller/user/user_controller.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3931 Feature: support installing kubesphere-core with helm
  Makefile
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/S

#3947 remove storage capability auto detection
  cmd/controller-manager/app/controllers.go
  config/default/provisonercapability/disk-csi-qingcloud-com.yaml
  config/default/provisonercapability/neonsan-csi-qingstor-com.yaml
  config/ks-core/templates/ks-controller-manager.yaml
  go.mod
  pkg/controller/storage/capability/capability_controller.go
  pkg/controller/storage/capability/capability_controller_test.go
  pkg/controller/storage/capability/csi_capability.go
  pkg/controller/storage/capability/csi_capability_test.go
Labels: approved, area/storage, dco-signoff: yes, kind/bug, lgtm, size/XL

#3946 Moving to a fork for jwt-go
  go.mod
  go.sum
  pkg/apiserver/authentication/identityprovider/oidc/oidc.go
  pkg/apiserver/authentication/identityprovider/oidc/oidc_test.go
  pkg/apiserver/authentication/token/jwt.go
  pkg/simple/client/devops/jenkins/request.go
  staging/src/kubesphere.io/api/go.sum
  staging/src/kubesphere.io/client-go/go.sum
  vendor/github.com/form3tech-oss/jwt-go/.gitignore
  vendor/github.com/form3tech-oss/jwt-go/.travis.yml
  vendor/github.com/form3tech-oss/jwt-go/LICENSE
  vendor/github.com/form3tech-oss/jwt-go/MIGRATION_GUIDE.md
  vendor/github.com/form3tech-oss/jwt-go/README.md
  vendor/github.com/form3tech-oss/jwt-go/VERSION_HISTORY.md
  vendor/github.com/form3tech-oss/jwt-go/claims.go
  vendor/github.com/form3tech-oss/jwt-go/doc.go
  vendor/github.com/form3tech-oss/jwt-go/ecdsa.go
  vendor/github.com/form3tech-oss/jwt-go/ecdsa_utils.go
  vendor/github.com/form3tech-oss/jwt-go/errors.go
  vendor/github.com/form3tech-oss/jwt-go/hmac.go
  vendor/github.com/form3tech-oss/jwt-go/map_claims.go
  vendor/github.com/form3tech-oss/jwt-go/none.go
  vendor/github.com/form3tech-oss/jwt-go/parser.go
  vendor/github.com/form3tech-oss/jwt-go/rsa.go
  vendor/github.com/form3tech-oss/jwt-go/rsa_pss.go
  vendor/github.com/form3tech-oss/jwt-go/rsa_utils.go
  vendor/github.com/form3tech-oss/jwt-go/signing_method.go
  vendor/github.com/form3tech-oss/jwt-go/token.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/L

#3964 add approvers and reviewers
  OWNERS
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#3965 Improve the s3 uploader for better performance.
  pkg/models/devops/s2ibinary_handler.go
  pkg/models/openpitrix/applications.go
  pkg/models/openpitrix/applicationversions.go
  pkg/models/openpitrix/attachments.go
  pkg/simple/client/s3/fake/fakes3.go
  pkg/simple/client/s3/fake/fakes3_test.go
  pkg/simple/client/s3/interface.go
  pkg/simple/client/s3/s3.go
  pkg/simple/client/s3/s3_test.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/M

#3944 update protobuf to v1.3.2
  go.mod
  go.sum
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/github.com/gogo/protobuf/types/any.pb.go
  vendor/github.com/gogo/protobuf/types/api.pb.go
  vendor/github.com/gogo/protobuf/types/duration.pb.go
  vendor/github.com/gogo/protobuf/types/empty.pb.go
  vendor/github.com/gogo/protobuf/types/field_mask.pb.go
  vendor/github.com/gogo/protobuf/types/source_context.pb.go
  vendor/github.com/gogo/protobuf/types/struct.pb.go
  vendor/github.com/gogo/protobuf/types/timestamp.pb.go
  vendor/github.com/gogo/protobuf/types/type.pb.go
  vendor/github.com/gogo/protobuf/types/wrappers.pb.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#3960 Fix kubesphere_app_template_count always be 0 when GetKubeSphereStats
  pkg/apiserver/apiserver.go
  pkg/kapis/metering/v1alpha1/handler.go
  pkg/kapis/metering/v1alpha1/register.go
  pkg/kapis/monitoring/v1alpha3/handler.go
  pkg/kapis/monitoring/v1alpha3/helper_test.go
  pkg/kapis/monitoring/v1alpha3/register.go
  pkg/models/monitoring/monitoring.go
  pkg/models/tenant/tenant.go
  tools/cmd/doc-gen/main.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#3974 Automated cherry pick of #3944: update protobuf to v1.3.2
  go.mod
  go.sum
  vendor/github.com/gogo/protobuf/proto/text_parser.go
  vendor/github.com/gogo/protobuf/types/any.pb.go
  vendor/github.com/gogo/protobuf/types/api.pb.go
  vendor/github.com/gogo/protobuf/types/duration.pb.go
  vendor/github.com/gogo/protobuf/types/empty.pb.go
  vendor/github.com/gogo/protobuf/types/field_mask.pb.go
  vendor/github.com/gogo/protobuf/types/source_context.pb.go
  vendor/github.com/gogo/protobuf/types/struct.pb.go
  vendor/github.com/gogo/protobuf/types/timestamp.pb.go
  vendor/github.com/gogo/protobuf/types/type.pb.go
  vendor/github.com/gogo/protobuf/types/wrappers.pb.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#3967 update pull request template
  .github/PULL_REQUEST_TEMPLATE.md
  pkg/models/openpitrix/attachments.go
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#3979 Automated cherry pick of #3947: remove storage capability auto detection
  cmd/controller-manager/app/controllers.go
  config/default/provisonercapability/disk-csi-qingcloud-com.yaml
  config/default/provisonercapability/neonsan-csi-qingstor-com.yaml
  go.mod
  pkg/controller/storage/capability/capability_controller.go
  pkg/controller/storage/capability/capability_controller_test.go
  pkg/controller/storage/capability/csi_capability.go
  pkg/controller/storage/capability/csi_capability_test.go
Labels: approved, dco-signoff: yes, lgtm, size/XL

#3978 apiserver: remove redundant GroupVersionResource
  pkg/apiserver/apiserver.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#3991 Automated cherry pick of #3946: moving jwt-go from github.com/dgrijalva/jwt-go v3.2.0 to
  go.mod
  go.sum
  pkg/apiserver/authentication/identityprovider/oidc/oidc.go
  pkg/apiserver/authentication/identityprovider/oidc/oidc_test.go
  pkg/apiserver/authentication/token/jwt.go
  pkg/simple/client/devops/jenkins/request.go
  staging/src/kubesphere.io/client-go/go.sum
  vendor/github.com/form3tech-oss/jwt-go/.gitignore
  vendor/github.com/form3tech-oss/jwt-go/.travis.yml
  vendor/github.com/form3tech-oss/jwt-go/LICENSE
  vendor/github.com/form3tech-oss/jwt-go/MIGRATION_GUIDE.md
  vendor/github.com/form3tech-oss/jwt-go/README.md
  vendor/github.com/form3tech-oss/jwt-go/VERSION_HISTORY.md
  vendor/github.com/form3tech-oss/jwt-go/claims.go
  vendor/github.com/form3tech-oss/jwt-go/doc.go
  vendor/github.com/form3tech-oss/jwt-go/ecdsa.go
  vendor/github.com/form3tech-oss/jwt-go/ecdsa_utils.go
  vendor/github.com/form3tech-oss/jwt-go/errors.go
  vendor/github.com/form3tech-oss/jwt-go/hmac.go
  vendor/github.com/form3tech-oss/jwt-go/map_claims.go
  vendor/github.com/form3tech-oss/jwt-go/none.go
  vendor/github.com/form3tech-oss/jwt-go/parser.go
  vendor/github.com/form3tech-oss/jwt-go/rsa.go
  vendor/github.com/form3tech-oss/jwt-go/rsa_pss.go
  vendor/github.com/form3tech-oss/jwt-go/rsa_utils.go
  vendor/github.com/form3tech-oss/jwt-go/signing_method.go
  vendor/github.com/form3tech-oss/jwt-go/token.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#3956 Verify the permission of create pods exec before creating terminal WebSocket connection
  pkg/apiserver/apiserver.go
  pkg/kapis/terminal/v1alpha2/handler.go
  pkg/kapis/terminal/v1alpha2/register.go
  tools/cmd/doc-gen/main.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#3936 Remove useless federated resources(users, roles, rolebindings) CRD files from config/crds
  config/crds/iam.kubesphere.io_federatedrolebindings.yaml
  config/crds/iam.kubesphere.io_federatedroles.yaml
  config/crds/iam.kubesphere.io_federatedusers.yaml
  staging/src/kubesphere.io/api/iam/v1alpha2/federated_types.go
  staging/src/kubesphere.io/api/iam/v1alpha2/register.go
  staging/src/kubesphere.io/api/iam/v1alpha2/types.go
  staging/src/kubesphere.io/api/iam/v1alpha2/zz_generated.deepcopy.go
  staging/src/kubesphere.io/api/quota/v1alpha2/types.go
  staging/src/kubesphere.io/api/types/v1beta1/register.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M

#3990 Add development verify scripts and refactor Dockerfile
  .github/workflows/build-multiarch.yaml
  .github/workflows/build.yml
  Makefile
  build/Dockerfile
  build/ks-apiserver/Dockerfile
  build/ks-controller-manager/Dockerfile
  hack/.spelling_failures
  hack/docker_build.sh
  hack/docker_build_multiarch.sh
  hack/gobuild.sh
  hack/tools/.gitignore
  hack/tools/Makefile
  hack/tools/README.md
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/update-gofmt.sh
  hack/verify-all.sh
  hack/verify-gofmt.sh
  hack/verify-golangci-lint.sh
  hack/verify-shellcheck.sh
  hack/verify-spelling.sh
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XXL

#4000 fix wrong target in Dockerfile
  hack/docker_build.sh
  hack/docker_build_multiarch.sh
Labels: approved, dco-signoff: yes, kind/failing-test, kind/flake, lgtm, size/XS

#3871 Fix: parse openpitrix resources, so that these resources will be included in billing.
  pkg/models/tenant/metering.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#4003 Fix panic due to nil pointer exception
  pkg/kapis/terminal/v1alpha2/handler.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#4014 Automated cherry pick of #3990 upstream release 3.1
  .github/workflows/build-multiarch.yaml
  .github/workflows/build.yml
  Makefile
  build/ks-apiserver/Dockerfile
  build/ks-controller-manager/Dockerfile
  hack/.spelling_failures
  hack/docker_build.sh
  hack/docker_build_multiarch.sh
  hack/gobuild.sh
  hack/tools/.gitignore
  hack/tools/Makefile
  hack/tools/README.md
  hack/tools/go.mod
  hack/tools/go.sum
  hack/tools/tools.go
  hack/update-gofmt.sh
  hack/verify-all.sh
  hack/verify-gofmt.sh
  hack/verify-golangci-lint.sh
  hack/verify-shellcheck.sh
  hack/verify-spelling.sh
Labels: approved, dco-signoff: yes, kind/api-change, kind/bug, kind/cleanup, kind/design, kind/documentation, kind/failing-test, kind/feature, kind/flake, lgtm, size/XXL

#4013 Fix merge conflict
  pkg/apiserver/authentication/identityprovider/oidc/oidc.go
  pkg/apiserver/authentication/identityprovider/oidc/oidc_test.go
  pkg/apiserver/authentication/token/jwt.go
  pkg/simple/client/devops/jenkins/request.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#4020 fix .dockerignore file ignores all files bug
  .dockerignore
Labels: approved, dco-signoff: yes, kind/api-change, kind/bug, kind/cleanup, kind/design, kind/documentation, kind/failing-test, kind/feature, kind/flake, lgtm, size/XS

#4019 fix wrong Makefile usage in nightly build workflow
  .github/workflows/nightly-builds.yml
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS
