Repository kubesphere/kubesphere, pull requests merged in 2021-04, with the labels that each got.

#3654 Fix owner reference conflict
  pkg/controller/namespace/namespace_controller.go
  pkg/controller/workspace/workspace_controller.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#3659 Renew kubeconfig certificate
  pkg/models/kubeconfig/kubeconfig.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#3667 Fix workspace controller manager
  pkg/controller/workspace/workspace_controller.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/client.go
  vendor/sigs.k8s.io/controller-runtime/pkg/client/fake/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/objectutil/filter.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#3663 ignore pkg/apis dir when running make goimports
  hack/verify-goimports.sh
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XS

#3662 fix:group was updated continuously in member cluster
  pkg/controller/group/group_controller.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#3674 fix case-insensitive keyword query and consistent state for alerting
  pkg/api/alerting/v2alpha1/types.go
  pkg/models/alerting/rules/utils.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#3643 Intergate OpenPitrix metrics into metering.
  pkg/api/metering/v1alpha1/types.go
  pkg/kapis/metering/v1alpha1/handler.go
  pkg/kapis/metering/v1alpha1/register.go
  pkg/kapis/monitoring/v1alpha3/handler.go
  pkg/kapis/monitoring/v1alpha3/helper.go
  pkg/kapis/monitoring/v1alpha3/helper_test.go
  pkg/kapis/monitoring/v1alpha3/meter.go
  pkg/kapis/tenant/v1alpha2/metering.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/models/metering/type.go
  pkg/models/monitoring/utils.go
  pkg/models/monitoring/utils_test.go
  pkg/models/tenant/metering.go
  pkg/models/tenant/metering_test.go
  pkg/models/tenant/tenant.go
  pkg/simple/client/monitoring/prometheus/prometheus.go
  pkg/simple/client/monitoring/query_options.go
  pkg/simple/client/monitoring/types.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XXL

#3680 Cascade deleting groups when workspace is deleted
  pkg/controller/group/group_controller.go
  pkg/controller/group/group_controller_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#3635 Let ks-apiserver optionally support authentication enabled and es without authentication enabled;
  pkg/simple/client/auditing/elasticsearch/elasticsearch.go
  pkg/simple/client/auditing/options.go
  pkg/simple/client/es/client.go
  pkg/simple/client/es/client_test.go
  pkg/simple/client/es/versions/v5/v5.go
  pkg/simple/client/es/versions/v6/v6.go
  pkg/simple/client/es/versions/v7/v7.go
  pkg/simple/client/events/elasticsearch/elasticsearch.go
  pkg/simple/client/events/options.go
  pkg/simple/client/logging/elasticsearch/elasticsearch.go
  pkg/simple/client/logging/options.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/L

#3687 add version sub command
  cmd/controller-manager/app/server.go
  cmd/ks-apiserver/app/server.go
  pkg/version/version.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/M

#3547 Fix: the panic caused by parsing requestinfo slice access out of bounds
  pkg/apiserver/request/requestinfo.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#3690 upgrade kubefed client to v0.6.1
  go.mod
  go.sum
  vendor/modules.txt
  vendor/sigs.k8s.io/kubefed/pkg/apis/core/v1beta1/federatedtypeconfig_types.go
  vendor/sigs.k8s.io/kubefed/pkg/apis/core/v1beta1/kubefedconfig_types.go
  vendor/sigs.k8s.io/kubefed/pkg/apis/scheduling/v1alpha1/replicaschedulingpreference_types.go
  vendor/sigs.k8s.io/kubefed/pkg/controller/util/controllerconfig.go
  vendor/sigs.k8s.io/kubefed/pkg/controller/util/federated_informer.go
  vendor/sigs.k8s.io/kubefed/pkg/controller/util/meta.go
  vendor/sigs.k8s.io/kubefed/pkg/controller/util/overrides.go
  vendor/sigs.k8s.io/kubefed/pkg/controller/util/worker.go
  vendor/sigs.k8s.io/kubefed/pkg/kubefedctl/options/options.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/L

#3691 add kubesphereversion field for cluser.status
  config/crds/cluster.kubesphere.io_clusters.yaml
  pkg/apis/cluster/v1alpha1/cluster_types.go
  pkg/controller/cluster/cluster_controller.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/M

#3688 feat: optional cascade delete resources when deleting workspace
  pkg/controller/namespace/namespace_controller.go
  pkg/controller/workspacetemplate/workspacetemplate_controller.go
  pkg/controller/workspacetemplate/workspacetemplate_controller_suite_test.go
  pkg/controller/workspacetemplate/workspacetemplate_controller_test.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/models/tenant/tenant.go
  pkg/utils/k8sutil/k8sutil.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/L

#3692 Add namespacedResourcesFilter field back in reqParams struct.
  pkg/kapis/monitoring/v1alpha3/helper.go
  pkg/kapis/monitoring/v1alpha3/helper_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#3699 set fetch depth of checkout action to fetch all history and tags
  .github/workflows/build.yml
Labels: approved, dco-signoff: yes, kind/bug, size/XS

#3696 fix bug member cluster can not view the notification channels
  pkg/controller/notification/notification_controller.go
  pkg/controller/notification/notification_controller_suite_test.go
  pkg/controller/notification/notification_controller_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#3706 fix notification triggering again after alerting rule changes
  pkg/models/alerting/alerting.go
  pkg/models/alerting/rules/ruler.go
  pkg/models/alerting/rules/utils.go
Labels: approved, area/alerting, dco-signoff: yes, kind/bug, lgtm, size/M

#3703 Fix: update chart data & sort by time of release list
  pkg/kapis/openpitrix/v1/handler.go
  pkg/models/openpitrix/applicationversions.go
  pkg/models/openpitrix/types.go
  pkg/models/openpitrix/utils.go
Labels: approved, dco-signoff: yes, kind/bug, kind/flake, lgtm, size/L

#3712 Fix: update time of charts
  pkg/models/openpitrix/utils.go
Labels: approved, area/app-management, dco-signoff: yes, kind/bug, lgtm, size/XS

#3694 check release resources status
  cmd/controller-manager/app/server.go
  config/crds/application.kubesphere.io_helmreleases.yaml
  pkg/apis/application/v1alpha1/constants.go
  pkg/apis/application/v1alpha1/helmrelease_types.go
  pkg/apiserver/config/config_test.go
  pkg/controller/openpitrix/helmrelease/helm_release_controller.go
  pkg/models/openpitrix/release.go
  pkg/models/openpitrix/utils.go
  pkg/simple/client/openpitrix/helmwrapper/helm_wrapper.go
  pkg/simple/client/openpitrix/helmwrapper/helm_wrapper_test.go
  pkg/simple/client/openpitrix/options.go
Labels: approved, area/app-management, dco-signoff: yes, kind/feature, lgtm, size/L

#3709 Fix the broken link of 'what-is-kubesphere'
  README_zh.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#3711 upgrade crd to apiextensions/v1
  pkg/apiserver/apiserver.go
  pkg/models/resources/v1alpha3/customresourcedefinition/customresourcedefinitions.go
  pkg/models/resources/v1alpha3/customresourcedefinition/customresourcedefinitions_test.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/S

#3717 fix nightly build version
  .github/workflows/nightly-builds.yml
Labels: approved, dco-signoff: yes, kind/bug, size/XS

#3721 Fix: filter app by app_id
  pkg/kapis/openpitrix/v1/handler.go
  pkg/models/openpitrix/utils.go
Labels: approved, area/app-management, dco-signoff: yes, kind/bug, lgtm, size/S

#3715 fix bug for node metrics on overview page
  pkg/kapis/monitoring/v1alpha3/helper.go
  pkg/kapis/monitoring/v1alpha3/register.go
  pkg/models/monitoring/monitoring.go
  pkg/simple/client/monitoring/query_options.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#3728 Fix: add kubeconfig when check release status
  pkg/simple/client/openpitrix/helmwrapper/helm_wrapper.go
Labels: approved, area/app-management, dco-signoff: yes, kind/bug, lgtm, size/XS

#3733 fix bug that edge metrcis test run failed
  pkg/simple/client/monitoring/metricsserver/metricsserver_test.go
Labels: approved, dco-signoff: yes, lgtm, size/S

#3741 Fix search bugs in app template page
  pkg/models/openpitrix/applicationversions.go
  pkg/models/openpitrix/repos.go
  pkg/models/openpitrix/utils.go
Labels: approved, dco-signoff: yes, kind/bug, kind/flake, lgtm, size/S

#3731 Update host cluster desc
  pkg/controller/cluster/cluster_controller.go
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#3750 Fix user status change after update
  pkg/models/iam/im/im.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#3753 Keep 3 decimal places for metering fee value.
  pkg/models/monitoring/utils.go
  pkg/models/monitoring/utils_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#3743 Fix: return all items when limit=-1
  pkg/kapis/openpitrix/v1/handler.go
  pkg/kapis/openpitrix/v1/register.go
  pkg/kapis/openpitrix/v2alpha1/handler.go
  pkg/kapis/openpitrix/v2alpha1/register.go
  pkg/models/openpitrix/applications.go
  pkg/models/openpitrix/applicationversions.go
  pkg/models/openpitrix/categories.go
  pkg/models/openpitrix/release.go
  pkg/models/openpitrix/repos.go
  pkg/simple/client/openpitrix/helmwrapper/helm_wrapper.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/L

#3770 Remove metering ConfigMap dependency.
  pkg/apiserver/apiserver.go
  pkg/apiserver/config/config.go
  pkg/apiserver/config/config_test.go
  pkg/kapis/metering/v1alpha1/handler.go
  pkg/kapis/metering/v1alpha1/register.go
  pkg/kapis/monitoring/v1alpha3/handler.go
  pkg/kapis/monitoring/v1alpha3/helper_test.go
  pkg/kapis/monitoring/v1alpha3/meter.go
  pkg/kapis/monitoring/v1alpha3/register.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/kapis/tenant/v1alpha2/metering.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/models/metering/type.go
  pkg/models/monitoring/monitoring.go
  pkg/models/monitoring/utils.go
  pkg/models/monitoring/utils_test.go
  pkg/models/tenant/metering.go
  pkg/models/tenant/metering_test.go
  pkg/models/tenant/tenant.go
  pkg/simple/client/metering/options.go
  pkg/simple/client/monitoring/interface.go
  tools/cmd/doc-gen/main.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XL

#3773 Fix the error caused by the wrong filter parse
  pkg/kapis/devops/v1alpha2/devops.go
  pkg/kapis/devops/v1alpha2/devops_test.go
  pkg/models/devops/devops.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/L

#3768 Fix issue with case-sensitive username
  pkg/apiserver/authentication/identityprovider/ldap/ldap.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#3779 remove trailing dollar char of namespacedResourcesFilter for monitoring api
  pkg/kapis/monitoring/v1alpha3/helper.go
Labels: approved, area/monitoring, dco-signoff: yes, kind/bug, lgtm, size/XS

#3776 Support RP-Initiated Logout
  pkg/apiserver/authentication/identityprovider/oidc/oidc.go
  pkg/apiserver/authentication/identityprovider/oidc/oidc_test.go
  pkg/kapis/oauth/handler.go
  pkg/kapis/oauth/register.go
  pkg/models/auth/token.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/M

#3781 fix crd upgrade error
  config/crds/network.kubesphere.io_namespacenetworkpolicies.yaml
  config/crds/storage.kubesphere.io_provisionercapabilities.yaml
  config/crds/storage.kubesphere.io_storageclasscapabilities.yaml
  pkg/apis/storage/v1alpha1/capability_types.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#3791 Update roadmap for o11y & edge
  docs/roadmap.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#3790 Mark all DevOps roadmap item as complete
  docs/roadmap.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XS

#3792 Update roadmap for multitenancy & IAM
  docs/roadmap.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#3798 update roadmap
  docs/roadmap.md
Labels: dco-signoff: yes, size/XS

#3799 Update the status of DevOps roadmap for upgrade section and the 3.0 section
  docs/roadmap.md
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#3806 Fix metering chart display error when switched into network flows consumption.
  pkg/simple/client/monitoring/prometheus/promql_meter.go
Labels: approved, area/metering, dco-signoff: yes, kind/bug, lgtm, size/XS

#3797 allow notification to slact when e2e failed
  .github/workflows/e2e-test.yml
  .github/workflows/nightly-builds.yml
Labels: approved, dco-signoff: yes, lgtm, size/S

#3823 multi arch build error
  .github/workflows/build-multiarch.yaml
  hack/docker_build.sh
  hack/docker_build_multiarch.sh
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3796 Fix SelectorFromSet ignore errors and select everything
  pkg/controller/group/group_controller.go
  pkg/controller/user/user_controller.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#3838 sync release-3.1 branch
  staging/publishing/rules.yaml
Labels: approved, dco-signoff: yes, kind/flake, lgtm, size/S
