Repository kubesphere/kubesphere, pull requests merged in 2021-03, with the labels that each got.

#3403 support selective application reconcilation
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/server.go
  go.mod
  go.sum
  pkg/apis/iam/v1alpha2/zz_generated.deepcopy.go
  pkg/apis/servicemesh/v1alpha2/strategy_types.go
  pkg/controller/application/application_controller.go
  pkg/controller/application/application_controller_test.go
  pkg/controller/application/application_suit_test.go
  pkg/controller/application/condition.go
  pkg/controller/application/status.go
  vendor/kubesphere.io/client-go
  vendor/modules.txt
  vendor/sigs.k8s.io/application/controllers/application_controller.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XL

#3416 fix code format issues
  pkg/controller/application/application_controller_test.go
  pkg/controller/application/application_suit_test.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#3424 fix: pipeline sync annotations
  pkg/kapis/devops/v1alpha2/devops.go
Labels: approved, area/devops, dco-signoff: yes, lgtm, size/XS

#3423 Fix update-vendor.sh script
  hack/update-vendor.sh
  vendor/kubesphere.io/client-go
Labels: approved, dco-signoff: yes, kind/flake, lgtm, size/XS

#3412 update roadmap for multi-cluster
  docs/roadmap.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#3429 Update staging repo sync rules
  staging/README.md
  staging/publishing/rules.yaml
Labels: approved, dco-signoff: yes, kind/flake, lgtm, size/M

#3410 fix ippool status statistics
  cmd/controller-manager/app/controllers.go
  pkg/controller/network/ippool/ippool_controller.go
  pkg/controller/network/ippool/ippool_controller_test.go
  pkg/simple/client/network/ippool/calico/provider.go
  pkg/simple/client/network/ippool/ipam/ipam.go
  pkg/simple/client/network/ippool/provider.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XL

#3431 Fix unmarshal bool into Go struct due to the boolean parameter
  pkg/simple/client/devops/pipeline.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/S

#3018 Add metering api
  go.mod
  go.sum
  pkg/api/metering/v1alpha1/types.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/request/requestinfo.go
  pkg/constants/constants.go
  pkg/kapis/metering/group.go
  pkg/kapis/metering/v1alpha1/handler.go
  pkg/kapis/metering/v1alpha1/register.go
  pkg/kapis/monitoring/v1alpha3/handler.go
  pkg/kapis/monitoring/v1alpha3/helper.go
  pkg/kapis/monitoring/v1alpha3/helper_test.go
  pkg/kapis/monitoring/v1alpha3/meter.go
  pkg/kapis/monitoring/v1alpha3/register.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/kapis/tenant/v1alpha2/metering.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/models/metering/type.go
  pkg/models/monitoring/monitoring.go
  pkg/models/monitoring/named_metrics.go
  pkg/models/monitoring/sort_page.go
  pkg/models/monitoring/types.go
  pkg/models/monitoring/utils.go
  pkg/models/tenant/metering.go
  pkg/models/tenant/tenant.go
  pkg/models/tenant/tenent_test.go
  pkg/simple/client/monitoring/interface.go
  pkg/simple/client/monitoring/metricsserver/metricsserver.go
  pkg/simple/client/monitoring/prometheus/prometheus.go
  pkg/simple/client/monitoring/prometheus/promql_meter.go
  pkg/simple/client/monitoring/query_options.go
  pkg/simple/client/monitoring/types.go
  tools/cmd/doc-gen/main.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XXL

#3409 add alerting rule bulk api
  pkg/api/alerting/v2alpha1/types.go
  pkg/kapis/alerting/v2alpha1/handler.go
  pkg/kapis/alerting/v2alpha1/register.go
  pkg/models/alerting/alerting.go
  pkg/models/alerting/rules/cache.go
  pkg/models/alerting/rules/rule.go
  pkg/models/alerting/rules/ruler.go
  pkg/models/alerting/rules/utils.go
  pkg/models/alerting/rules/utils_test.go
  tools/cmd/doc-gen/main.go
Labels: approved, dco-signoff: yes, kind/flake, lgtm, size/XXL

#3433 limit login record entries
  cmd/controller-manager/app/controllers.go
  go.mod
  pkg/apiserver/apiserver.go
  pkg/apiserver/authentication/identityprovider/ldap/ldap.go
  pkg/apiserver/authentication/options/authenticate_options.go
  pkg/controller/loginrecord/loginrecord_controller.go
  pkg/controller/loginrecord/loginrecord_controller_test.go
  pkg/controller/serviceaccount/serviceaccount_controller_suite_test.go
  pkg/kapis/oauth/handler.go
  pkg/kapis/oauth/register.go
  pkg/models/auth/authenticator.go
  pkg/models/auth/login_recoder.go
  vendor/k8s.io/client-go/metadata/metadatainformer/informer.go
  vendor/k8s.io/client-go/metadata/metadatainformer/interface.go
  vendor/k8s.io/client-go/metadata/metadatalister/interface.go
  vendor/k8s.io/client-go/metadata/metadatalister/lister.go
  vendor/k8s.io/client-go/metadata/metadatalister/shim.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/XL

#3432 Fix the issues caused by the differences XML structure between the simple pipline and the multi-branch pipeline
  pkg/simple/client/devops/jenkins/pipeline_internal.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/S

#3427 Add kubeedge API
  pkg/apiserver/apiserver.go
  pkg/apiserver/config/config.go
  pkg/apiserver/config/config_test.go
  pkg/kapis/kubeedge/v1alpha1/register.go
  pkg/simple/client/kubeedge/options.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/M

#3436 Fix a typo of Amazon and the doc link of GKE
  README.md
  README_zh.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#3437 support virtualservice multi port
  pkg/controller/utils/servicemesh/application.go
  pkg/controller/utils/servicemesh/application_test.go
  pkg/controller/virtualservice/virtualservice_controller.go
  pkg/controller/virtualservice/virtualservice_controller_test.go
Labels: approved, area/microservice, dco-signoff: yes, lgtm, size/L

#3440 fix alerts not retriggered when updating rule
  pkg/models/alerting/rules/ruler.go
Labels: approved, area/alerting, dco-signoff: yes, kind/bug, lgtm, size/M

#3447 fix bug can not search auditing logs with nil namespace
  pkg/simple/client/auditing/elasticsearch/elasticsearch.go
  pkg/simple/client/auditing/elasticsearch/elasticsearch_test.go
  pkg/simple/client/es/response.go
  pkg/simple/client/events/elasticsearch/elasticsearch.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#3458 Fix nil pointer and missing router
  cmd/controller-manager/app/server.go
  pkg/apiserver/config/config.go
  pkg/kapis/openpitrix/v1/register.go
  pkg/simple/client/openpitrix/options.go
Labels: approved, area/app-management, dco-signoff: yes, kind/bug, lgtm, size/M

#3442 add extra annotations and labels to helm release
  build/ks-apiserver/Dockerfile
  build/ks-controller-manager/Dockerfile
  go.mod
  pkg/controller/openpitrix/helmrelease/helm_release_controller.go
  pkg/simple/client/openpitrix/helmwrapper/helm_wrapper.go
  pkg/simple/client/openpitrix/helmwrapper/helm_wrapper_darwin.go
  pkg/simple/client/openpitrix/helmwrapper/helm_wrapper_linux.go
  pkg/simple/client/openpitrix/helmwrapper/helm_wrapper_test.go
Labels: approved, area/app-management, dco-signoff: yes, kind/bug, lgtm, size/L

#3461 fix unauthorized resource access
  pkg/kapis/resources/v1alpha3/handler.go
  pkg/models/resources/v1alpha2/resource/resources.go
  pkg/models/resources/v1alpha3/resource/resource.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#3467 Refine group e2e test
  go.mod
  go.sum
  staging/src/kubesphere.io/client-go/go.mod
  staging/src/kubesphere.io/client-go/go.sum
  staging/src/kubesphere.io/client-go/restclient/restclient.go
  staging/src/kubesphere.io/client-go/restclient/versioned/iam/v1alpha2/group.go
  staging/src/kubesphere.io/client-go/restclient/versioned/iam/v1alpha2/iam_client.go
  staging/src/kubesphere.io/client-go/restclient/versioned/iam/v1alpha2/rolebindings.go
  test/e2e/constant/constants.go
  test/e2e/framework/framework.go
  test/e2e/framework/iam/fixtures.go
  test/e2e/framework/iam/utils.go
  test/e2e/framework/resource/fixtures.go
  test/e2e/framework/test_context.go
  test/e2e/groups.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XL

#3491 modify ippool api resource to namespace scope
  pkg/controller/network/ippool/ippool_controller.go
  pkg/models/resources/v1alpha3/resource/resource.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#3465 Fix nil pointer and delete helmRelease
  cmd/controller-manager/app/server.go
  config/crds/application.kubesphere.io_helmrepos.yaml
  pkg/apis/application/v1alpha1/helmrepo_types.go
  pkg/apiserver/config/config.go
  pkg/controller/openpitrix/helmrelease/get_chart_data.go
  pkg/controller/openpitrix/helmrelease/helm_release_controller.go
  pkg/kapis/openpitrix/v1/handler.go
  pkg/models/openpitrix/applications.go
  pkg/models/openpitrix/applicationversions.go
  pkg/models/openpitrix/attachments.go
  pkg/models/openpitrix/categories.go
  pkg/models/openpitrix/release.go
  pkg/models/openpitrix/repos.go
  pkg/models/openpitrix/utils.go
  pkg/simple/client/openpitrix/helmrepoindex/repo_index.go
  pkg/simple/client/openpitrix/helmwrapper/helm_wrapper.go
  pkg/simple/client/openpitrix/helmwrapper/helm_wrapper_test.go
Labels: approved, area/app-management, dco-signoff: yes, kind/bug, lgtm, size/XL

#3505 Fix Pipeline input failed in multi-branch mode
  go.mod
  go.sum
  pkg/controller/pipeline/pipeline_controller.go
  pkg/kapis/devops/v1alpha2/devops.go
  pkg/simple/client/devops/jenkins/pipeline.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/S

#3490 change kubesphere-monitoring-federated to system namespace
  pkg/constants/constants.go
  pkg/controller/notification/notification_controller.go
  pkg/controller/notification/notification_controller_test.go
  pkg/models/notification/notification.go
  pkg/models/notification/notification_test.go
Labels: approved, dco-signoff: yes, lgtm, size/L

#3529 fix concurrent map writes on node
  pkg/models/resources/v1alpha3/node/nodes.go
  pkg/models/resources/v1alpha3/node/nodes_test.go
Labels: approved, dco-signoff: yes, kind/bug, size/M

#3524 Set default value of weatherScore to 100
  pkg/simple/client/devops/jenkins/pipeline.go
  pkg/simple/client/devops/pipeline.go
  pkg/simple/client/devops/pipeline_test.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/M

#3527 fix bug can not delete notification secret
  pkg/models/notification/notification.go
  pkg/models/notification/notification_test.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#3550 Fix the BitBucket endpoint URL redundant checking
  pkg/kapis/devops/v1alpha2/register.go
  pkg/models/devops/devops.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/XS

#3548 fix import error
  pkg/tools.go
  tools/tools.go
  vendor/github.com/MakeNowJust/heredoc/README.md
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/L

#3577 fix unit test timeout
  go.mod
  pkg/controller/loginrecord/loginrecord_controller_test.go
Labels: approved, dco-signoff: yes, kind/failing-test, lgtm, size/L

#3575 fix ut timeout issue example
  pkg/controller/serviceaccount/serviceaccount_controller_suite_test.go
  pkg/controller/serviceaccount/serviceaccount_controller_test.go
Labels: approved, dco-signoff: yes, kind/flake, lgtm, size/L

#3574 Fix: handle invalid semver
  pkg/controller/openpitrix/helmapplication/helm_application_controller.go
  pkg/controller/openpitrix/helmapplication/helm_application_version_controller.go
  pkg/models/openpitrix/utils.go
Labels: approved, area/app-management, dco-signoff: yes, kind/bug, lgtm, size/M

#3576 Update powered-by-kubesphere.md
  docs/powered-by-kubesphere.md
Labels: dco-signoff: no, kind/documentation, size/XS

#3589 fix 502 error when joining the same cluster with a different name
  pkg/controller/cluster/cluster_controller.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#3600 change http response code to 400 when the cluster is not ready
  pkg/apiserver/dispatch/dispatch.go
Labels: approved, dco-signoff: yes, kind/design, lgtm, size/S

#3594 Request edge metrics only if prometheus metrics data is empty
  pkg/models/monitoring/monitoring.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/M

#3584 Remove useless log output
  pkg/apiserver/authentication/authenticators/jwttoken/jwt_token.go
  pkg/apiserver/authentication/token/jwt.go
  pkg/apiserver/authorization/rbac/rbac.go
  pkg/models/auth/token.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/S

#3595 Fix that devops admin users cannot approve a Pipeline input
  pkg/apiserver/authorization/authorizer/interfaces.go
  pkg/kapis/devops/v1alpha2/devops.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/XS

#3486 update vendor directory
  go.mod
  vendor/github.com/go-resty/resty/v2/.gitignore
  vendor/github.com/go-resty/resty/v2/.travis.yml
  vendor/github.com/go-resty/resty/v2/BUILD.bazel
  vendor/github.com/go-resty/resty/v2/LICENSE
  vendor/github.com/go-resty/resty/v2/README.md
  vendor/github.com/go-resty/resty/v2/WORKSPACE
  vendor/github.com/go-resty/resty/v2/client.go
  vendor/github.com/go-resty/resty/v2/go.mod
  vendor/github.com/go-resty/resty/v2/go.sum
  vendor/github.com/go-resty/resty/v2/middleware.go
  vendor/github.com/go-resty/resty/v2/redirect.go
  vendor/github.com/go-resty/resty/v2/request.go
  vendor/github.com/go-resty/resty/v2/response.go
  vendor/github.com/go-resty/resty/v2/resty.go
  vendor/github.com/go-resty/resty/v2/retry.go
  vendor/github.com/go-resty/resty/v2/trace.go
  vendor/github.com/go-resty/resty/v2/transport.go
  vendor/github.com/go-resty/resty/v2/transport112.go
  vendor/github.com/go-resty/resty/v2/util.go
  vendor/golang.org/x/net/publicsuffix/list.go
  vendor/golang.org/x/net/publicsuffix/table.go
  vendor/helm.sh/helm/v3/pkg/release/hook.go
  vendor/helm.sh/helm/v3/pkg/release/info.go
  vendor/helm.sh/helm/v3/pkg/release/mock.go
  vendor/helm.sh/helm/v3/pkg/release/release.go
  vendor/helm.sh/helm/v3/pkg/release/responses.go
  vendor/helm.sh/helm/v3/pkg/release/status.go
  vendor/helm.sh/helm/v3/pkg/time/time.go
  vendor/kubesphere.io/client-go
  vendor/kubesphere.io/client-go/LICENSE
  vendor/kubesphere.io/client-go/client/clientCache.go
  vendor/kubesphere.io/client-go/client/codec.go
  vendor/kubesphere.io/client-go/client/generic/genericclient.go
  vendor/kubesphere.io/client-go/client/generic/typedClient.go
  vendor/kubesphere.io/client-go/client/generic/unstructuredClient.go
  vendor/kubesphere.io/client-go/client/interface.go
  vendor/kubesphere.io/client-go/client/options.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XXL

#3590 Fix: remove checks when delete release
  pkg/apis/application/v1alpha1/helmapplication_types.go
  pkg/controller/openpitrix/helmapplication/helm_application_controller.go
  pkg/kapis/openpitrix/v1/handler.go
  pkg/models/openpitrix/applications.go
  pkg/models/openpitrix/applicationversions.go
  pkg/models/openpitrix/release.go
  pkg/models/openpitrix/repos.go
  pkg/models/openpitrix/types.go
  pkg/models/openpitrix/utils.go
Labels: approved, dco-signoff: yes, kind/bug, kind/flake, lgtm, size/L

#3588 Fix fields missing when convert Jenkinsfile to JSON
  pkg/kapis/devops/v1alpha2/register.go
  pkg/models/devops/devops.go
  pkg/simple/client/devops/fake/fakedevops.go
  pkg/simple/client/devops/jenkins/jenkins.go
  pkg/simple/client/devops/jenkins/pipeline.go
  pkg/simple/client/devops/pipeline.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/M

#3441 Update metering csv export format and intergrate metering module.
  pkg/apiserver/apiserver.go
  pkg/apiserver/config/config.go
  pkg/apiserver/config/config_test.go
  pkg/kapis/metering/v1alpha1/handler.go
  pkg/kapis/metering/v1alpha1/register.go
  pkg/kapis/monitoring/v1alpha3/handler.go
  pkg/kapis/monitoring/v1alpha3/helper.go
  pkg/kapis/monitoring/v1alpha3/helper_test.go
  pkg/kapis/monitoring/v1alpha3/meter.go
  pkg/kapis/monitoring/v1alpha3/register.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/kapis/tenant/v1alpha2/metering.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/models/metering/type.go
  pkg/models/monitoring/monitoring.go
  pkg/models/monitoring/utils.go
  pkg/models/tenant/metering.go
  pkg/models/tenant/tenant.go
  pkg/simple/client/alerting/rule_client.go
  pkg/simple/client/metering/options.go
  pkg/simple/client/monitoring/query_options.go
  pkg/simple/client/monitoring/types.go
  tools/cmd/doc-gen/main.go
Labels: approved, dco-signoff: yes, kind/api-change, lgtm, size/XXL

#3638 Add Bitbucket organization field "key"
  pkg/simple/client/devops/pipeline.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/XS

#3658 upgrade kubefed to v0.7.0
  go.mod
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/cluster/join.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/S

#3651 Fix: fix app repo and helm app bugs
  pkg/controller/openpitrix/helmapplication/helm_application_controller.go
  pkg/kapis/openpitrix/v1/handler.go
  pkg/models/openpitrix/applications.go
  pkg/models/openpitrix/applicationversions.go
  pkg/models/openpitrix/repos.go
  pkg/models/openpitrix/types.go
  pkg/models/openpitrix/utils.go
Labels: approved, dco-signoff: yes, kind/bug, kind/flake, lgtm, size/M
