Repository kubesphere/kubesphere, pull requests merged in 2021-05, with the labels that each got.

#3767 Fix: validate repo when modify url
  pkg/kapis/openpitrix/v1/handler.go
  pkg/models/openpitrix/repos.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#3795 add RawExtension type annotation
  config/crds/iam.kubesphere.io_rolebases.yaml
  config/crds/tenant.kubesphere.io_workspacetemplates.yaml
  staging/src/kubesphere.io/api/iam/v1alpha2/types.go
  staging/src/kubesphere.io/api/types/v1beta1/types.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#3855 Remove useless e2e test
  test/e2e/help_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3864 fix dead links and update versions in README
  README.md
  README_zh.md
  staging/src/kubesphere.io/client-go/README.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#3848 fix servicemesh crd
  config/crds/servicemesh.kubesphere.io_strategies.yaml
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3859 Fixed namespace resource filter.
  pkg/models/tenant/metering.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#3868 Fix client typo
  pkg/controller/devopscredential/devopscredential_controller.go
Labels: approved, dco-signoff: yes, kind/flake, lgtm, size/XS

#3897 Query workspacerolebindings by rolename
  pkg/models/resources/v1alpha3/workspacerolebinding/workspacerolebindings.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#3886 Fix: parse chart data by loader.LoadArchive
  pkg/models/openpitrix/applicationversions.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M
