Repository kubesphere/kubesphere, pull requests merged in 2021-11, with the labels that each got.

#4406 Fix sonarqube scan results
  pkg/models/openpitrix/repos.go
  pkg/models/resources/v1alpha3/federatedingress/federatedingresses.go
  pkg/models/resources/v1alpha3/ingress/ingresses.go
  pkg/models/tenant/metering.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#4401 add kubesphere icon animation and katacoda scenario
  README.md
  README_zh.md
  docs/images/kubesphere-icon.gif
Labels: approved, lgtm, size/S, kind/documentation, release-note

#4418 Allows to override nginx ingress controller image in kubesphere config
  cmd/controller-manager/app/server.go
  config/gateway/values.yaml
  pkg/controller/helm/helm_controller.go
  pkg/controller/helm/helm_controller_test.go
  pkg/simple/client/gateway/options.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#4419 Update the download version to 3.2.0
  README.md
  README_zh.md
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#4434 Support query pods by status
  pkg/models/resources/v1alpha3/pod/pods.go
  pkg/models/resources/v1alpha3/pod/pods_test.go
Labels: kind/feature, approved, lgtm, size/M, release-note

#4436 fix: users can't login with ldap provider
  pkg/models/auth/password.go
  pkg/models/auth/password_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#4457 Namespace should not be filterd for Cluster Gateway
  pkg/simple/client/monitoring/prometheus/promql.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#4443 fix : modify the version of ks core components
  Makefile
  config/ks-core/Chart.yaml
Labels: kind/bug, approved, size/XS, lgtm, needs-ok-to-test, release-note-none

#4402 Typo fixing in the README_zh.md file
  README_zh.md
Labels: approved, size/XS, lgtm, needs-ok-to-test, do-not-merge/release-note-label-needed

#4463 remove obsolete package pkg/simple/client/mysql
  pkg/simple/client/mysql/OWNERS
  pkg/simple/client/mysql/condition.go
  pkg/simple/client/mysql/condition_test.go
  pkg/simple/client/mysql/db.go
  pkg/simple/client/mysql/error.go
  pkg/simple/client/mysql/event.go
  pkg/simple/client/mysql/mysql.go
  pkg/simple/client/mysql/options.go
Labels: ok-to-test, approved, lgtm, kind/cleanup, size/XL, release-note-none

#4455 fix hyperlink format in README_zh.md
  README_zh.md
Labels: approved, size/XS, lgtm, needs-ok-to-test, kind/documentation, release-note

#4471 fix groupbinding controller unittest
  pkg/controller/groupbinding/groupbinding_controller_test.go
Labels: approved, lgtm, size/M, kind/failing-test, release-note-none

#4481 fix: Account password settings can have no capital letters
  config/crds/iam.kubesphere.io_users.yaml
  staging/src/kubesphere.io/api/iam/v1alpha2/types.go
Labels: kind/bug, ok-to-test, approved, lgtm, size/S, release-note
