Repository kubesphere/kubesphere, pull requests merged in 2021-09, with the labels that each got.

#4188 Removed hack/install_kubebuilder.sh
  .github/workflows/build.yml
  hack/install_kubebuilder.sh
Labels: ok-to-test, approved, lgtm, size/M, kind/cleanup, release-note-none

#4199 Fix CertificateSigningRequest create failed after upgrade to certificates.k8s.io/v1
  pkg/controller/certificatesigningrequest/certificatesigningrequest_controller.go
  pkg/controller/user/user_controller.go
  pkg/kapis/resources/v1alpha2/handler.go
  pkg/models/kubeconfig/kubeconfig.go
  pkg/models/kubeconfig/kubeconfig_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#4203 fix API specification for #4194
  pkg/kapis/monitoring/v1alpha3/dashboard_template_test.sh
  pkg/kapis/monitoring/v1alpha3/handler.go
  pkg/kapis/monitoring/v1alpha3/register.go
  pkg/simple/client/monitoring/types.go
Labels: kind/design, area/monitoring, area/console, approved, lgtm, size/S, kind/feature-request, area/observability, release-note-none

#4206 fix deadlock for node getter
  pkg/models/resources/v1alpha3/node/nodes.go
Labels: kind/bug, ok-to-test, approved, size/XS, lgtm, release-note-none

#4204 helm: allows ks-core to mount extra volumes
  config/ks-core/templates/ks-apiserver.yml
  config/ks-core/templates/ks-console.yml
  config/ks-core/templates/ks-controller-manager.yaml
  config/ks-core/values.yaml
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#4212 Fix the nightly build failed due to rely on a missing file
  .github/workflows/nightly-builds.yml
Labels: approved, size/XS, lgtm, kind/cleanup, release-note-none

#4211 feature: support setting host cluster name
  cmd/controller-manager/app/controllers.go
  pkg/controller/cluster/cluster_controller.go
  pkg/simple/client/multicluster/options.go
Labels: kind/feature, approved, lgtm, size/M, release-note

#4209 Manage pv in console
  pkg/apiserver/apiserver.go
  pkg/models/resources/v1alpha3/persistentvolume/persistentvolume.go
  pkg/models/resources/v1alpha3/persistentvolume/persistentvolume_test.go
  pkg/models/resources/v1alpha3/resource/resource.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#4215 Move scope-misplaced resource getters to the right place
  pkg/kapis/resources/v1alpha3/handler_test.go
  pkg/models/resources/v1alpha3/resource/resource.go
Labels: approved, size/XS, lgtm, kind/cleanup, release-note-none

#4208 feat: package gateway helm chart into docker image
  build/ks-controller-manager/Dockerfile
  config/watches.yaml
Labels: kind/feature, approved, lgtm, size/S, release-note-none

#4128 clean up app when workspace is deleted
  pkg/constants/constants.go
  pkg/controller/openpitrix/helmapplication/helm_application_controller.go
  pkg/controller/openpitrix/helmapplication/helm_application_controller_suite_test.go
  pkg/controller/openpitrix/helmapplication/helm_application_controller_test.go
  pkg/controller/workspacetemplate/workspacetemplate_controller.go
  pkg/models/openpitrix/utils.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#4222 upgrade ValidatingWebhookConfiguration to v1
  config/ks-core/templates/webhook.yaml
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#4223 add etcd_server_is_leader metric to query
  pkg/models/monitoring/named_metrics.go
  pkg/simple/client/monitoring/prometheus/promql.go
Labels: area/monitoring, approved, size/XS, lgtm, kind/optimization, release-note-none

#4220 support setting cluster name under single cluster scenario
  config/ks-core/templates/ks-console-config.yml
  config/ks-core/values.yaml
Labels: kind/feature, approved, size/XS, lgtm, release-note

#4230 feat: upgrade gateway with all legacy settings
  pkg/models/gateway/gateway.go
  pkg/models/gateway/gateway_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#4224 add validation for host cluster name
  cmd/controller-manager/app/options/options.go
  pkg/simple/client/multicluster/options.go
Labels: kind/feature, approved, lgtm, size/S, release-note-none

#4216 Add notification setting validation API
  config/ks-core/templates/kubesphere-config.yaml
  config/ks-core/values.yaml
  pkg/apiserver/apiserver.go
  pkg/kapis/notification/v2beta2/handler.go
  pkg/kapis/notification/v2beta2/register.go
  staging/src/kubesphere.io/api/notification/v2beta2/config_types.go
  staging/src/kubesphere.io/api/notification/v2beta2/doc.go
  staging/src/kubesphere.io/api/notification/v2beta2/notificationmanager_types.go
  staging/src/kubesphere.io/api/notification/v2beta2/receiver_types.go
  staging/src/kubesphere.io/api/notification/v2beta2/register.go
  staging/src/kubesphere.io/api/notification/v2beta2/types.go
  staging/src/kubesphere.io/api/notification/v2beta2/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm, release-note

#4227 feat: ingress metrics query apis
  pkg/constants/constants.go
  pkg/kapis/monitoring/v1alpha3/handler.go
  pkg/kapis/monitoring/v1alpha3/helper.go
  pkg/kapis/monitoring/v1alpha3/helper_test.go
  pkg/kapis/monitoring/v1alpha3/register.go
  pkg/models/monitoring/named_metrics.go
  pkg/models/monitoring/sort_page.go
  pkg/simple/client/monitoring/prometheus/promql.go
  pkg/simple/client/monitoring/prometheus/promql_test.go
  pkg/simple/client/monitoring/prometheus/testdata/promqls.go
  pkg/simple/client/monitoring/query_options.go
Labels: kind/feature, approved, lgtm, size/L, kind/api-change, release-note-none

#4243 feat: get gateway's workload and status
  pkg/apiserver/apiserver.go
  pkg/kapis/gateway/v1alpha1/handler.go
  pkg/kapis/gateway/v1alpha1/register.go
  pkg/models/gateway/gateway.go
  pkg/models/gateway/gateway_test.go
  pkg/utils/conversions/core/v1/conversion.go
Labels: kind/feature, approved, lgtm, size/XL, release-note-none

#4238 Support skip information reconfirm when using external IDP
  pkg/apiserver/authentication/oauth/oauth_options.go
  pkg/apiserver/authentication/oauth/oauth_options_test.go
  pkg/controller/user/user_webhook.go
  pkg/models/auth/authenticator.go
Labels: kind/feature, approved, lgtm, size/M, release-note

#4228 Fix inconsistent user status in member cluster
  cmd/controller-manager/app/controllers.go
  cmd/controller-manager/app/server.go
  pkg/controller/user/user_controller.go
  pkg/controller/user/user_controller_test.go
  staging/src/kubesphere.io/api/types/v1beta1/federateduser_types.go
Labels: kind/bug, approved, lgtm, size/XL, release-note-none

#3525 support OIDC protocol
  cmd/controller-manager/app/controllers.go
  cmd/controller-manager/app/options/options.go
  cmd/ks-apiserver/app/options/options.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/authentication/authenticators/basic/basic.go
  pkg/apiserver/authentication/authenticators/jwt/jwt.go
  pkg/apiserver/authentication/identityprovider/aliyunidaas/idaas.go
  pkg/apiserver/authentication/identityprovider/aliyunidaas/idaas_test.go
  pkg/apiserver/authentication/identityprovider/cas/cas.go
  pkg/apiserver/authentication/identityprovider/github/github.go
  pkg/apiserver/authentication/identityprovider/github/github_test.go
  pkg/apiserver/authentication/identityprovider/identity_provider.go
  pkg/apiserver/authentication/identityprovider/identity_provider_test.go
  pkg/apiserver/authentication/identityprovider/oauth_provider.go
  pkg/apiserver/authentication/identityprovider/oidc/oidc.go
  pkg/apiserver/authentication/identityprovider/oidc/oidc_test.go
  pkg/apiserver/authentication/oauth/error.go
  pkg/apiserver/authentication/oauth/oidc.go
  pkg/apiserver/authentication/oauth/oidc_test.go
  pkg/apiserver/authentication/oauth/options.go
  pkg/apiserver/authentication/oauth/options_test.go
  pkg/apiserver/authentication/options.go
  pkg/apiserver/authentication/token/issuer.go
  pkg/apiserver/authentication/token/issuer_test.go
  pkg/apiserver/authentication/token/jwt.go
  pkg/apiserver/authentication/token/jwt_test.go
  pkg/apiserver/authorization/options.go
  pkg/apiserver/authorization/options/authorization_options.go
  pkg/apiserver/config/config.go
  pkg/apiserver/config/config_test.go
  pkg/controller/user/user_controller.go
  pkg/controller/user/user_controller_test.go
  pkg/kapis/oauth/handler.go
  pkg/kapis/oauth/register.go
  pkg/models/auth/authenticator.go
  pkg/models/auth/oauth.go
  pkg/models/auth/oauth_test.go
  pkg/models/auth/password.go
  pkg/models/auth/password_test.go
  pkg/models/auth/token.go
  pkg/models/iam/im/im.go
Labels: kind/feature, approved, size/XXL, lgtm, dco-signoff: yes, release-note

#4264 feat: add default gateway pod affinity
  config/gateway/templates/nginx-ingress.yaml
Labels: kind/feature, approved, lgtm, size/M, release-note-none

#4254 fix regression bug failed to create federateduser
  pkg/controller/user/user_controller.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#4273 fix: duplicated items show in the list api
  pkg/models/gateway/gateway.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#4271 Fix the devopsProjectLister is nil
  pkg/apiserver/apiserver.go
  pkg/apiserver/authorization/rbac/rbac_test.go
  pkg/models/iam/am/am.go
Labels: kind/bug, area/devops, approved, lgtm, size/S, release-note-none

#4284 update ingress version in ks-core chart
  config/ks-core/templates/ks-apiserver.yml
  config/ks-core/templates/ks-console.yml
  config/ks-core/templates/ks-controller-manager.yaml
  config/ks-core/templates/sample-bookinfo-configmap.yaml
Labels: kind/bug, approved, lgtm, size/S, kind/flake, release-note-none

#4286 Search gateway logs with ES
  pkg/apiserver/apiserver.go
  pkg/kapis/gateway/v1alpha1/handler.go
  pkg/kapis/gateway/v1alpha1/register.go
Labels: kind/feature, approved, lgtm, size/M, release-note-none

#4299 simply github workflow since we migrate most of CI steps to prow
  .github/workflows/build-multiarch.yaml
  .github/workflows/build.yml
  .github/workflows/nightly-builds.yml
Labels: approved, size/M, kind/cleanup, release-note-none

#4301 Fix workflow build syntax error
  .github/workflows/build-multiarch.yaml
Labels: kind/bug, approved, size/XS, release-note-none

#4290 update capability_controller.go, make sure that annotations is genera…
  pkg/controller/storage/capability/capability_controller.go
  pkg/controller/storage/capability/capability_controller_test.go
Labels: kind/feature, approved, lgtm, size/M, area/storage, release-note-none

#4302 Add scheduling parameters for ks-core chart
  config/ks-core/templates/ks-apiserver.yml
  config/ks-core/templates/ks-console.yml
  config/ks-core/templates/ks-controller-manager.yaml
  config/ks-core/values.yaml
Labels: approved, lgtm, size/M, kind/cleanup, release-note-none

#4250 Dynamically load helm app into app-store
  pkg/constants/constants.go
  pkg/controller/openpitrix/helmrepo/helm_repo_controller.go
  pkg/kapis/openpitrix/v1/handler.go
  pkg/models/openpitrix/applications.go
  pkg/models/openpitrix/applicationversions.go
  pkg/models/openpitrix/categories.go
  pkg/models/openpitrix/category_test.go
  pkg/models/openpitrix/interface.go
  pkg/models/openpitrix/repos.go
  pkg/models/openpitrix/types.go
  pkg/models/openpitrix/utils.go
  pkg/simple/client/openpitrix/helmrepoindex/interface.go
  pkg/simple/client/openpitrix/helmrepoindex/load_package.go
  pkg/simple/client/openpitrix/helmrepoindex/repo_index.go
  pkg/utils/reposcache/repo_cahes.go
  staging/src/kubesphere.io/api/application/v1alpha1/constants.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#4304 add kind-e2e to Makefile
  .github/workflows/e2e-test.yml
  .github/workflows/nightly-builds.yml
  Makefile
  hack/deploy-kubesphere.sh
  hack/kind_e2e.sh
  test/e2e/kind.yaml
Labels: approved, size/L, kind/cleanup, release-note-none

#4308 fix missing constants
  vendor/kubesphere.io/api/application/v1alpha1/constants.go
Labels: kind/bug, approved, size/XS, release-note-none
