Repository kubesphere/kubesphere, pull requests merged in 2021-12, with the labels that each got.

#4476 fix: generate manifests
  Makefile
  hack/generate_manifests.sh
Labels: kind/bug, approved, lgtm, size/M, needs-ok-to-test, release-note-none

#4528 feat: add ExternalKubeAPIEnabled to cluster
  config/crds/cluster.kubesphere.io_clusters.yaml
  staging/src/kubesphere.io/api/cluster/v1alpha1/cluster_types.go
Labels: kind/feature, approved, lgtm, size/S, kind/api-change, release-note

#4512 add --controllers option in ks-controller-manager
  cmd/controller-manager/app/controllers.go
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/options/options_test.go
  cmd/controller-manager/app/server.go
  pkg/controller/openpitrix/helmcategory/helm_category_controller.go
  pkg/controller/openpitrix/helmcategory/helm_category_controller_suite_test.go
  pkg/controller/openpitrix/helmrepo/helm_repo_controller.go
  pkg/controller/openpitrix/helmrepo/helm_repo_controller_suite_test.go
  pkg/controller/quota/resourcequota_controller.go
Labels: kind/feature, ok-to-test, approved, lgtm, size/XL, release-note

#4572 fix: spell mistake: hostClusterNmae -> hostClusterName
  pkg/controller/cluster/cluster_controller.go
Labels: approved, size/XS, lgtm, needs-ok-to-test, kind/cleanup, release-note-none

#4560 fix: All ports should be added to VitrualService
  pkg/controller/virtualservice/virtualservice_controller.go
  pkg/controller/virtualservice/virtualservice_controller_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#4562 Add update cluster kubeconfig API
  pkg/api/cluster/v1alpha1/types.go
  pkg/apiserver/apiserver.go
  pkg/kapis/cluster/v1alpha1/handler.go
  pkg/kapis/cluster/v1alpha1/handler_test.go
  pkg/kapis/cluster/v1alpha1/register.go
  tools/cmd/doc-gen/main.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#4551 upgrade ingress nginx version
  build/ks-controller-manager/Dockerfile
  config/gateway/templates/nginx-ingress.yaml
  config/gateway/values.yaml
  pkg/controller/helm/helm_controller.go
Labels: kind/bug, ok-to-test, approved, lgtm, size/S, release-note-none
