Repository kubesphere/kubesphere, pull requests merged in 2021-08, with the labels that each got.

#4103 feat: load configuration from Environment variables
  config/ks-core/templates/ks-apiserver.yml
  config/ks-core/templates/ks-controller-manager.yaml
  config/ks-core/values.yaml
  pkg/apiserver/config/config.go
  pkg/apiserver/config/config_test.go
Labels: approved, kind/feature, kind/flake, lgtm, release-note-none, size/S

#4112 modify comments in pkg/apiserver/authentication/identityprovider/identity_provider.go
  pkg/apiserver/authentication/identityprovider/identity_provider.go
Labels: approved, lgtm, ok-to-test, release-note-none, size/XS

#4116 upgrade kustomize to v4.2.0
  build/ks-controller-manager/Dockerfile
Labels: approved, kind/bug, lgtm, release-note-none, size/XS

#4129 Add proxy devops APIs request to ks-devops
  api/api-rules/violation_exceptions.list
  api/ks-openapi-spec/swagger.json
  api/openapi-spec/swagger.json
  cmd/controller-manager/app/controllers.go
  pkg/apiserver/apiserver.go
  pkg/controller/devopscredential/devopscredential_controller.go
  pkg/controller/devopscredential/devopscredential_controller_test.go
  pkg/controller/devopsproject/devopsproject_controller.go
  pkg/controller/devopsproject/devopsproject_controller_test.go
  pkg/controller/pipeline/pipeline_controller.go
  pkg/controller/pipeline/pipeline_controller_test.go
  pkg/controller/s2ibinary/OWNERS
  pkg/controller/s2ibinary/s2ibinary_controller.go
  pkg/controller/s2ibinary/s2ibinary_controller_test.go
  pkg/controller/s2irun/OWNERS
  pkg/controller/s2irun/s2irun_controller.go
  pkg/controller/s2irun/s2irun_controller_test.go
  pkg/kapis/devops/v1alpha2/devops.go
  pkg/kapis/devops/v1alpha2/devops_test.go
  pkg/kapis/devops/v1alpha2/handler.go
  pkg/kapis/devops/v1alpha2/pipeline_sonar.go
  pkg/kapis/devops/v1alpha2/register.go
  pkg/kapis/devops/v1alpha2/s2ibinary.go
  pkg/kapis/devops/v1alpha3/handler.go
  pkg/kapis/devops/v1alpha3/register.go
  pkg/simple/client/devops/jenkins/options.go
  tools/cmd/doc-gen/main.go
Labels: area/devops, approved, size/XXL, lgtm, release-note

#4144 Support make help
  Makefile
Labels: kind/feature, ok-to-test, approved, lgtm, size/M, release-note-none

#4161 fix `go mod tidy` error
  staging/src/kubesphere.io/api/go.mod
  staging/src/kubesphere.io/api/go.sum
Labels: approved, lgtm

#4159 remove config/webhook config/samples config/servicemesh config/rbac config/default dir
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_image_patch.yaml
  config/default/manager_prometheus_metrics_patch.yaml
  config/default/provisonercapability/aws-ebs.yaml
  config/default/provisonercapability/azure-disk.yaml
  config/default/provisonercapability/azure-file.yaml
  config/default/provisonercapability/cinder.yaml
  config/default/provisonercapability/disk-csi-qingcloud-com.yaml
  config/default/provisonercapability/gce-pd.yaml
  config/default/provisonercapability/glusterfs.yaml
  config/default/provisonercapability/neonsan-csi-qingstor-com.yaml
  config/default/provisonercapability/portworx-volume.yaml
  config/default/provisonercapability/rbd.yaml
  config/manager/manager.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/rbac_role.yaml
  config/rbac/rbac_role_binding.yaml
  config/rbac/role.yaml
  config/samples/devops_v1alpha1_s2ibinary.yaml
  config/samples/devops_v1alpha3_devopsproject.yaml
  config/samples/devops_v1alpha3_pipeline.yaml
  config/samples/iam_v1alpha2_globalrole.yaml
  config/samples/iam_v1alpha2_globalrolebinding.yaml
  config/samples/iam_v1alpha2_group.yaml
  config/samples/iam_v1alpha2_groupbinding.yaml
  config/samples/iam_v1alpha2_rolebindings.yaml
  config/samples/iam_v1alpha2_user.yaml
  config/samples/network_v1alpha1_namespacenetworkpolicy.yaml
  config/samples/servicemesh_v1alpha2_servicepolicy.yaml
  config/samples/servicemesh_v1alpha2_strategy.yaml
  config/samples/storage_v1alpha1_provisionercapability.yaml
  config/samples/storage_v1alpha1_storageclasscapability.yaml
  config/samples/tenant_v1alpha1_workspace.yaml
  config/webhook/iam.yaml
  config/webhook/ks-controller-manager.yaml
  config/webhook/manifests.yaml
  config/webhook/network.yaml
  config/webhook/quota.yaml
Labels: approved, lgtm, kind/cleanup, size/XL, do-not-merge/release-note-label-needed

#4164 Upgrade ingress api version to networking.k8s.io/v1
  pkg/api/types.go
  pkg/apiserver/apiserver.go
  pkg/models/quotas/quotas.go
  pkg/models/resources/v1alpha2/ingress/ingresses.go
  pkg/models/resources/v1alpha3/ingress/ingresses.go
  pkg/models/resources/v1alpha3/ingress/ingresses_test.go
  pkg/models/resources/v1alpha3/resource/resource.go
  staging/src/kubesphere.io/api/types/v1beta1/federatedingress_types.go
Labels: kind/feature, ok-to-test, approved, lgtm, size/M, kind/api-change, release-note-none

#4162 Fix the ks-apiserver panic due to the devopsprojects CRD missing
  pkg/apiserver/apiserver.go
  pkg/models/iam/am/am.go
  pkg/models/tenant/tenent_test.go
Labels: kind/bug, area/devops, approved, lgtm, size/S, release-note-none

#4166 fix: kubesphere/api package UT failed
  Makefile
  staging/src/kubesphere.io/api/go.mod
  staging/src/kubesphere.io/api/go.sum
  staging/src/kubesphere.io/client-go/go.mod
  staging/src/kubesphere.io/client-go/go.sum
Labels: approved, lgtm, size/XL, kind/failing-test, release-note-none

#4174 Update kubesphere/api sync rule
  staging/publishing/rules.yaml
  staging/src/kubesphere.io/api/notification/v2beta1/v2beta1_suite_test.go
Labels: approved, lgtm, size/M, kind/failing-test, release-note-none

#4175 fix duplicate args generated when creating more than one ingress-controllers
  pkg/models/routers/routers.go
Labels: ok-to-test, approved, size/XS, lgtm, release-note-none

#4183 update the outdated information in README
  README.md
Labels: approved, lgtm, size/L, release-note-none

#4190 patch: bump CertificateSigningRequest version from v1beta1 to v1
  pkg/controller/certificatesigningrequest/certificatesigningrequest_controller.go
  pkg/models/kubeconfig/kubeconfig.go
Labels: kind/bug, approved, size/XS, lgtm, do-not-merge/release-note-label-needed

#4186 upgrade kubebuilder envtest to v3
  .gitignore
  Makefile
  hack/setup-kubebuilder-env.sh
Labels: kind/bug, approved, lgtm, size/S, kind/failing-test, release-note

#4181 bump Ingress version from v1beta1 to v1
  pkg/controller/application/application_controller.go
Labels: kind/bug, approved, size/XS, lgtm, do-not-merge/release-note-label-needed
