Repository kubesphere/kubesphere, pull requests merged in 2021-01, with the labels that each got.

#3238 Updates roadmap
  docs/roadmap.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/XS

#3247 Cascading deletion of children groups
  pkg/controller/group/group_controller.go
  pkg/controller/group/group_controller_test.go
  pkg/kapis/iam/v1alpha2/register.go
  pkg/models/iam/am/am.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/M

#3240 update roadmap
  docs/roadmap.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#3249 feature: add devops roadmap
  docs/roadmap.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#3250 support pass customized repo
  hack/docker_build.sh
Labels: approved, dco-signoff: yes, kind/flake, lgtm, size/S

#3224 fix metrics query bug for pods with duplicate name in one node
  pkg/kapis/monitoring/v1alpha3/helper.go
  pkg/kapis/monitoring/v1alpha3/register.go
  pkg/simple/client/monitoring/prometheus/prometheus.go
  pkg/simple/client/monitoring/prometheus/promql.go
  pkg/simple/client/monitoring/prometheus/promql_test.go
  pkg/simple/client/monitoring/prometheus/testdata/promqls.go
  pkg/simple/client/monitoring/query_options.go
Labels: approved, area/monitoring, dco-signoff: yes, kind/bug, lgtm, size/L

#3256 Add network.topology into conf.ToMap()
  pkg/apiserver/config/config.go
  pkg/simple/client/network/options.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/S

#3235 Fix the pipeline do not sync with Jenkins
  go.mod
  go.sum
  pkg/apis/devops/v1alpha3/pipeline_types.go
  pkg/controller/pipeline/pipeline_controller.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/M

#3255 Add roadmap for O11y and Edge
  docs/roadmap.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/M

#3243 Add AppStore/Network/Metering Roadmap in v3.1
  docs/roadmap.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#3220 add metrics
  cmd/controller-manager/app/server.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/metric.go
  pkg/controller/workspace/metrics.go
  pkg/controller/workspace/workspace_controller.go
  pkg/models/openpitrix/apps.go
  pkg/models/openpitrix/metric.go
  pkg/utils/metrics/metrics.go
Labels: approved, area/apiserver, dco-signoff: yes, kind/feature, lgtm, size/L

#3239 add roadmap for multi-cluster
  docs/roadmap.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#3212 add a es client for auditing, events, and logging
  cmd/ks-apiserver/app/options/options.go
  pkg/api/auditing/v1alpha1/types.go
  pkg/api/events/v1alpha1/types.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/auditing/backend.go
  pkg/apiserver/auditing/types.go
  pkg/apiserver/config/config.go
  pkg/apiserver/config/config_test.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/models/logging/logging.go
  pkg/models/tenant/tenant.go
  pkg/simple/client/auditing/elasticsearch/clients.go
  pkg/simple/client/auditing/elasticsearch/elasticsearch.go
  pkg/simple/client/auditing/elasticsearch/elasticsearch_test.go
  pkg/simple/client/auditing/interface.go
  pkg/simple/client/auditing/options.go
  pkg/simple/client/es/client.go
  pkg/simple/client/es/client_test.go
  pkg/simple/client/es/query/builder.go
  pkg/simple/client/es/response.go
  pkg/simple/client/es/testdata/es6_detect_version_major_200.json
  pkg/simple/client/es/testdata/es7_detect_version_major_200.json
  pkg/simple/client/es/testdata/es7_search_200.json
  pkg/simple/client/es/testdata/es7_search_200_result.json
  pkg/simple/client/es/versions/interface.go
  pkg/simple/client/es/versions/v5/v5.go
  pkg/simple/client/es/versions/v6/v6.go
  pkg/simple/client/es/versions/v7/v7.go
  pkg/simple/client/events/elasticsearch/clients.go
  pkg/simple/client/events/elasticsearch/elasticsearch.go
  pkg/simple/client/events/elasticsearch/elasticsearch_test.go
  pkg/simple/client/events/interface.go
  pkg/simple/client/events/options.go
  pkg/simple/client/logging/elasticsearch/api_body.go
  pkg/simple/client/logging/elasticsearch/api_body_test.go
  pkg/simple/client/logging/elasticsearch/api_body_types.go
  pkg/simple/client/logging/elasticsearch/elasticsearch.go
  pkg/simple/client/logging/elasticsearch/elasticsearch_test.go
  pkg/simple/client/logging/elasticsearch/testdata/es6_get_current_stats_200.json
  pkg/simple/client/logging/elasticsearch/testdata/es7_count_logs_by_interval_200.json
  pkg/simple/client/logging/elasticsearch/testdata/es7_get_current_stats_200.json
  pkg/simple/client/logging/interface.go
  pkg/simple/client/logging/options.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XXL

#3242 add microservice roadmap
  docs/roadmap.md
Labels: approved, dco-signoff: yes, lgtm, size/S

#3267 fix application reconcile
  pkg/controller/application/application_controller.go
  pkg/controller/destinationrule/destinationrule_controller.go
  pkg/controller/destinationrule/destinationrule_controller_test.go
  pkg/controller/utils/servicemesh/application.go
  pkg/controller/virtualservice/virtualservice_controller.go
  pkg/controller/virtualservice/virtualservice_controller_test.go
  pkg/models/resources/v1alpha3/application/applications.go
  pkg/models/resources/v1alpha3/application/applications_test.go
  pkg/models/servicemesh/application.go
  pkg/models/servicemesh/metrics/handlers.go
Labels: approved, area/microservice, dco-signoff: yes, kind/bug, lgtm, size/L

#3268 Feat ServiceAccount management
  cmd/controller-manager/app/server.go
  pkg/api/types.go
  pkg/apis/iam/v1alpha2/types.go
  pkg/apiserver/apiserver.go
  pkg/controller/serviceaccount/serviceaccount_controller.go
  pkg/controller/serviceaccount/serviceaccount_controller_suite_test.go
  pkg/controller/serviceaccount/serviceaccount_controller_test.go
  pkg/controller/utils/controller/basecontroller.go
  pkg/models/resources/v1alpha3/resource/resource.go
  pkg/models/resources/v1alpha3/serviceaccount/serviceaccount.go
  pkg/models/resources/v1alpha3/serviceaccount/serviceaccount_test.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XL

#3214 Configurable cluster resync perioud
  cmd/controller-manager/app/controllers.go
  cmd/controller-manager/app/server.go
  pkg/controller/cluster/cluster_controller.go
  pkg/simple/client/multicluster/options.go
Labels: approved, dco-signoff: yes, kind/design, lgtm, size/M

#3279 Fix the pipeline list with incorrect paging calculating
  pkg/kapis/devops/v1alpha2/devops.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/M

#3289 fix proxy upgrade error when using kubeconfig with token
  pkg/apiserver/dispatch/dispatch.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#3291 Fix the wrong XML parse of Pipeline choice parameter
  pkg/simple/client/devops/jenkins/pipeline_internal.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/XS

#3173 Add metrics-server client to monitoring
  cmd/ks-apiserver/app/options/options.go
  pkg/apiserver/apiserver.go
  pkg/kapis/monitoring/v1alpha3/handler.go
  pkg/kapis/monitoring/v1alpha3/helper_test.go
  pkg/kapis/monitoring/v1alpha3/register.go
  pkg/models/monitoring/monitoring.go
  pkg/simple/client/monitoring/metricsserver/metricsserver.go
  pkg/simple/client/monitoring/metricsserver/metricsserver_test.go
  pkg/simple/client/monitoring/metricsserver/testdata/metrics-matrix-1.json
  pkg/simple/client/monitoring/metricsserver/testdata/metrics-matrix-2.json
  pkg/simple/client/monitoring/metricsserver/testdata/metrics-matrix-3.json
  pkg/simple/client/monitoring/metricsserver/testdata/metrics-vector-1.json
  pkg/simple/client/monitoring/metricsserver/testdata/metrics-vector-2.json
  pkg/simple/client/monitoring/metricsserver/testdata/metrics-vector-3.json
  tools/cmd/doc-gen/main.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XXL
