Repository kubesphere/kubesphere, pull requests merged in 2021-02, with the labels that each got.

#3296 When the ip4 addres is nil, it should try the next.
  pkg/utils/idutils/id_utils.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#3317 add parameter to allow ignore cert
  pkg/kapis/resources/v1alpha2/handler.go
  pkg/kapis/resources/v1alpha2/register.go
  pkg/models/registries/manifest_test.go
  pkg/models/registries/registries.go
  pkg/models/registries/registry_client.go
  pkg/models/registries/registry_client_test.go
  pkg/models/registries/token_test.go
Labels: approved, dco-signoff: yes, lgtm, size/M

#3337 improvement: update owners for devops
  OWNERS
  pkg/apis/devops/OWNERS
  pkg/controller/s2ibinary/OWNERS
  pkg/controller/s2irun/OWNERS
  pkg/kapis/devops/v1alpha2/OWNERS
  pkg/models/devops/OWNERS
  pkg/models/git/OWNERS
  pkg/simple/client/devops/OWNERS
  pkg/simple/client/mysql/OWNERS
  pkg/simple/client/sonarqube/OWNERS
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M

#3294 Add support to proxy Jenkins API with POST method
  pkg/kapis/devops/v1alpha2/register.go
Labels: approved, area/devops, dco-signoff: yes, kind/feature, lgtm, size/M

#3319 remove http1.1 support code
  pkg/apiserver/dispatch/dispatch.go
  pkg/apiserver/filters/kubeapiserver.go
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/M

#3330 add application unit test files
  pkg/controller/application/application_controller_test.go
  pkg/controller/application/application_suit_test.go
Labels: approved, area/microservice, dco-signoff: yes, lgtm, size/L

#3346 Fix workspace member count
  pkg/models/monitoring/monitoring.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS

#3338 custom alerting tuning
  pkg/api/alerting/v2alpha1/types.go
  pkg/kapis/alerting/v2alpha1/register.go
  pkg/models/alerting/alerting.go
  pkg/models/alerting/rules/ruler.go
  pkg/models/alerting/rules/utils.go
Labels: approved, dco-signoff: yes, kind/optimization, lgtm, size/L

#3286 Fix the incorrect approvable check of Pipeline input
  hack/docker_build.sh
  pkg/apiserver/apiserver.go
  pkg/apiserver/authorization/authorizer/interfaces.go
  pkg/kapis/devops/v1alpha2/devops.go
  pkg/kapis/devops/v1alpha2/handler.go
  pkg/kapis/devops/v1alpha2/register.go
  pkg/simple/client/devops/pipeline.go
  pkg/simple/client/devops/pipeline_test.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/L

#3350 fix duplicate args error
  pkg/models/routers/routers.go
  pkg/utils/sliceutil/sliceutil_test.go
  pkg/utils/sliceutil/sliceutils.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/M

#3360 run update-vendor.sh to update dependencies
  go.mod
  go.sum
  vendor/github.com/docker/docker/pkg/locker/README.md
  vendor/github.com/docker/docker/pkg/locker/locker.go
  vendor/github.com/hashicorp/hcl/.gitignore
  vendor/github.com/hashicorp/hcl/Makefile
  vendor/github.com/pelletier/go-toml/example-crlf.toml
  vendor/github.com/sirupsen/logrus/appveyor.yml
  vendor/github.com/spf13/afero/.travis.yml
  vendor/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
  vendor/k8s.io/metrics/LICENSE
  vendor/k8s.io/metrics/pkg/apis/metrics/doc.go
  vendor/k8s.io/metrics/pkg/apis/metrics/register.go
  vendor/k8s.io/metrics/pkg/apis/metrics/types.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/doc.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/generated.pb.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/generated.proto
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/register.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/types.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/zz_generated.conversion.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/doc.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/generated.pb.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/generated.proto
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/register.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/types.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/metrics/pkg/apis/metrics/zz_generated.deepcopy.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/clientset.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/fake/clientset_generated.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/fake/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/fake/register.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/scheme/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/scheme/register.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/fake/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/fake/fake_metrics_client.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/fake/fake_nodemetrics.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/fake/fake_podmetrics.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/generated_expansion.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/metrics_client.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/nodemetrics.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/podmetrics.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/fake/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/fake/fake_metrics_client.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/fake/fake_nodemetrics.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/fake/fake_podmetrics.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/generated_expansion.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/metrics_client.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/nodemetrics.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/podmetrics.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/cleanup, lgtm, size/XXL

#3254 validate member cluster config while joining member clusters.
  go.mod
  go.sum
  pkg/kapis/cluster/v1alpha1/handler.go
  pkg/kapis/cluster/v1alpha1/handler_test.go
  pkg/kapis/cluster/v1alpha1/register.go
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/L

#3362 Remove k8s.io/kubernetes from go.mod
  go.mod
  go.sum
  pkg/controller/pipeline/pipeline_controller.go
  vendor/k8s.io/apimachinery/pkg/util/proxy/upgradeaware.go
  vendor/k8s.io/kubernetes/LICENSE
  vendor/k8s.io/kubernetes/pkg/util/hash/BUILD
  vendor/k8s.io/kubernetes/pkg/util/hash/hash.go
  vendor/modules.txt
Labels: approved, area/devops, dco-signoff: yes, kind/cleanup, lgtm, size/L

#3349 Trying to avoid the error of `Operation cannot be fulfilled on` by getting the latest resourceVersion
  pkg/models/devops/devops.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/S

#3352 support CAS identity provider
  go.mod
  go.sum
  pkg/apiserver/authentication/identityprovider/cas/cas.go
  pkg/apiserver/authentication/options/authenticate_options.go
  pkg/kapis/oauth/handler.go
  vendor/gopkg.in/cas.v2/.gitignore
  vendor/gopkg.in/cas.v2/LICENSE
  vendor/gopkg.in/cas.v2/README.md
  vendor/gopkg.in/cas.v2/client.go
  vendor/gopkg.in/cas.v2/doc.go
  vendor/gopkg.in/cas.v2/go.mod
  vendor/gopkg.in/cas.v2/go.sum
  vendor/gopkg.in/cas.v2/handler.go
  vendor/gopkg.in/cas.v2/http_helpers.go
  vendor/gopkg.in/cas.v2/logout_request.go
  vendor/gopkg.in/cas.v2/memory_store.go
  vendor/gopkg.in/cas.v2/middleware.go
  vendor/gopkg.in/cas.v2/rest_client.go
  vendor/gopkg.in/cas.v2/rest_handler.go
  vendor/gopkg.in/cas.v2/sanitise.go
  vendor/gopkg.in/cas.v2/service_response.go
  vendor/gopkg.in/cas.v2/service_validate.go
  vendor/gopkg.in/cas.v2/session_store.go
  vendor/gopkg.in/cas.v2/ticket_store.go
  vendor/gopkg.in/cas.v2/url_scheme.go
  vendor/gopkg.in/cas.v2/xml_service_response.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, kind/feature, lgtm, size/XXL

#3342 Fix the Pipeline name filter issues
  pkg/kapis/devops/v1alpha2/devops.go
  pkg/kapis/devops/v1alpha3/handler.go
  pkg/models/devops/devops.go
  pkg/server/params/params.go
  pkg/server/params/params_test.go
  pkg/simple/client/devops/jenkins/pipeline.go
  pkg/simple/client/devops/jenkins/utils.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/L

#3335 Fix the wrong count of total Pipeline Run number
  pkg/simple/client/devops/jenkins/pure_request.go
  pkg/simple/client/devops/jenkins/utils.go
  pkg/simple/client/devops/jenkins/utils_test.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/M

#3370 Update OpenPitrix and Network roadmap
  docs/roadmap.md
Labels: approved, dco-signoff: yes, lgtm, size/XS

#3364 Fix the issues that devops credentials cannot be deleted
  pkg/apis/devops/v1alpha3/credential_types.go
  pkg/controller/devopscredential/devopscredential_controller.go
  pkg/controller/pipeline/pipeline_controller.go
  pkg/controller/utils/hash.go
Labels: approved, area/devops, dco-signoff: yes, kind/bug, lgtm, size/L

#3372 Update roadmap for o11y & edge
  docs/roadmap.md
Labels: approved, dco-signoff: yes, kind/documentation, lgtm, size/S

#3376 Don't exit while synchronizing calico ippool
  pkg/controller/network/ippool/ippool_controller.go
  pkg/simple/client/network/ippool/calico/provider.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#3380 refactor cluster controller
  pkg/controller/cluster/cluster_controller.go
  pkg/simple/client/multicluster/options.go
Labels: approved, dco-signoff: yes, kind/design, lgtm, size/L

#3383 feature: add annotations to pipelines for getting syncstatus
  .gitignore
  pkg/kapis/devops/v1alpha2/devops.go
  pkg/simple/client/devops/pipeline.go
Labels: approved, area/devops, dco-signoff: yes, kind/feature, lgtm, size/XS

#3394 Update calico lib
  go.mod
  go.sum
  vendor/github.com/projectcalico/libcalico-go/lib/apis/v3/globalnetworkpolicy.go
  vendor/github.com/projectcalico/libcalico-go/lib/apis/v3/ipam_block.go
  vendor/github.com/projectcalico/libcalico-go/lib/apis/v3/networkpolicy.go
  vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/conversion/conversion.go
  vendor/github.com/projectcalico/libcalico-go/lib/backend/model/block.go
  vendor/modules.txt
Labels: approved, dco-signoff: yes, lgtm, size/M

#3396 DevOps roles not been initialed
  pkg/controller/namespace/namespace_controller.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/S

#3375 add e2e github action
  .github/workflows/e2e-test.yml
  .github/workflows/kind/kind.yaml
  hack/deploy-kubesphere.sh
Labels: approved, dco-signoff: yes, lgtm, size/L

#3408 Fix cannot modify UserSpec
  pkg/kapis/iam/v1alpha2/handler.go
  pkg/models/iam/im/im.go
Labels: approved, dco-signoff: yes, kind/bug, lgtm, size/XS
