Repository kubesphere/kubesphere, pull requests merged in 2022-09, with the labels that each got.

#5200 alerting v2beta1 tunes
  pkg/api/alerting/v2beta1/types.go
  pkg/controller/alerting/util.go
  pkg/models/alerting/rulegroup.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#5182 fix bug helm repo paging query
  pkg/models/openpitrix/repos.go
Labels: kind/bug, approved, size/XS, lgtm, needs-ok-to-test, release-note

#5154 support recording disable and enable users in auditing
  pkg/apiserver/auditing/types.go
Labels: approved, lgtm, size/M, release-note-none

#5191 Add authorization control for patching workspacetemplates
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/models/tenant/tenant.go
  pkg/utils/clusterclient/clusterclient.go
  pkg/utils/josnpatchutil/jsonpatchutil.go
Labels: kind/feature, approved, lgtm, area/iam, size/L, do-not-merge/release-note-label-needed

#5213 Fix: when placement is empty return error
  pkg/models/tenant/tenant.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#5219 fix rule status set
  pkg/apiserver/apiserver.go
  pkg/controller/alerting/clusterrulegroup_controller.go
  pkg/controller/alerting/globalrulegroup_controller.go
  pkg/controller/alerting/rulegroup_controller.go
  pkg/kapis/alerting/v2beta1/handler.go
  pkg/kapis/alerting/v2beta1/register.go
  pkg/models/alerting/rulegroup.go
  staging/src/kubesphere.io/api/alerting/v2beta1/rulegroup_webhook.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#5215 Refactor the cluster controller using controller-runtime and remove the kubefed dependency
  cmd/controller-manager/app/controllers.go
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/cluster/join.go
  pkg/controller/cluster/unjoin.go
  pkg/controller/cluster/util.go
Labels: approved, size/XXL, lgtm, kind/cleanup, release-note

#4894 add dynamic options for cache
  cmd/ks-apiserver/app/options/options.go
  pkg/apiserver/config/config.go
  pkg/apiserver/config/config_test.go
  pkg/simple/client/cache/cache.go
  pkg/simple/client/cache/factory.go
  pkg/simple/client/cache/inmemory_cache.go
  pkg/simple/client/cache/inmemory_cache_test.go
  pkg/simple/client/cache/options.go
  pkg/simple/client/cache/redis.go
  pkg/simple/client/cache/simple_cache.go
  pkg/simple/client/kiali/client_test.go
Labels: kind/feature, approved, lgtm, size/XL, release-note-none

#5228 invalid config file should not be ignored
  cmd/controller-manager/app/server.go
  cmd/ks-apiserver/app/server.go
  pkg/apiserver/config/config.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#5232 fix gateway upgrade validate error.
  pkg/models/gateway/gateway.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#5240 Add the helm executor common package
  staging/publishing/rules.yaml
  staging/src/kubesphere.io/utils/LICENSE
  staging/src/kubesphere.io/utils/OWNERS
  staging/src/kubesphere.io/utils/README.md
  staging/src/kubesphere.io/utils/helm/executor.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#5247 update ks-core helm chart
  config/ks-core/templates/ks-apiserver.yml
  config/ks-core/templates/ks-console.yml
  config/ks-core/templates/ks-controller-manager.yaml
  config/ks-core/templates/kubesphere-controls-system.yaml
  config/ks-core/templates/role-templates.yaml
  config/ks-core/values.yaml
Labels: approved, lgtm, size/L, kind/flake, kind/cleanup, release-note-none

#5249 Bump alpine to 3.16.2
  build/ks-apiserver/Dockerfile
  build/ks-controller-manager/Dockerfile
Labels: approved, lgtm, size/S, release-note-none

#5248 Fix cluster gateway logs and resource status display exception
  pkg/models/gateway/gateway.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#5245 Implement the helm executor package
  staging/src/kubesphere.io/utils/go.mod
  staging/src/kubesphere.io/utils/go.sum
  staging/src/kubesphere.io/utils/helm/build/Dockerfile
  staging/src/kubesphere.io/utils/helm/executor.go
  staging/src/kubesphere.io/utils/helm/rest_client_getter.go
Labels: kind/feature, approved, size/XXL, lgtm, release-note-none

#5256 utils: remove the controller-runtime dependency
  staging/src/kubesphere.io/utils/go.mod
  staging/src/kubesphere.io/utils/go.sum
  staging/src/kubesphere.io/utils/helm/executor.go
Labels: approved, lgtm, size/M, kind/cleanup, release-note-none
