Repository kubesphere/kubesphere, pull requests merged in 2022-06, with the labels that each got.

#4936 Fix kubeconfig generate bug
  pkg/models/kubeconfig/kubeconfig.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#4928 Add agent to report additional information.
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/server.go
  cmd/ks-apiserver/app/options/options.go
  cmd/ks-apiserver/app/server.go
  go.mod
  go.sum
  vendor/github.com/google/gops/LICENSE
  vendor/github.com/google/gops/agent/agent.go
  vendor/github.com/google/gops/agent/sockopt_reuseport.go
  vendor/github.com/google/gops/agent/sockopt_unsupported.go
  vendor/github.com/google/gops/internal/internal.go
  vendor/github.com/google/gops/internal/internal_go1_13.go
  vendor/github.com/google/gops/internal/internal_lt_go1_13.go
  vendor/github.com/google/gops/signal/signal.go
  vendor/modules.txt
Labels: kind/feature, approved, lgtm, size/XL, release-note-none

#4937 add unit test for GetServiceTracing
  pkg/kapis/servicemesh/metrics/v1alpha2/handler_test.go
  pkg/simple/client/kiali/client_test.go
  pkg/simple/client/kiali/mock_client.go
  pkg/utils/reflectutils/reflect.go
Labels: approved, lgtm, size/L, needs-ok-to-test, release-note-none

#4941 Unified call WriteEntity func
  pkg/kapis/openpitrix/v1/handler.go
Labels: ok-to-test, approved, size/XS, lgtm, kind/cleanup

#4939 Promptly handle the cluster when it is deleted
  pkg/controller/cluster/cluster_controller.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#4938 fix some typos
  pkg/controller/application/application_controller_test.go
  pkg/kapis/gateway/v1alpha1/handler.go
  pkg/models/gateway/gateway.go
  pkg/models/gateway/gateway_test.go
Labels: approved, lgtm, size/M, needs-ok-to-test, kind/cleanup, release-note-none

#4940 create default token for service account
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/cluster/join.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#4952 Add the corresponding label 'kind/bug' to the issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: approved, size/XS, lgtm, tide/merge-method-squash, kind/cleanup, release-note-none

#4995 docs: add CHANGELOG-3.3.md
  CHANGELOG/CHANGELOG-3.3.md
Labels: approved, lgtm, size/L, tide/merge-method-squash, kind/documentation, release-note-none

#4996 docs: Update v3.3.0 changelog
  CHANGELOG/CHANGELOG-3.3.md
Labels: approved, lgtm, size/L, kind/documentation, release-note-none

#4852 Replace the Helm command
  pkg/simple/client/openpitrix/helmwrapper/helm_wrapper.go
  pkg/simple/client/openpitrix/helmwrapper/helm_wrapper_darwin.go
  pkg/simple/client/openpitrix/helmwrapper/helm_wrapper_linux.go
  pkg/simple/client/openpitrix/helmwrapper/helm_wrapper_test.go
  pkg/simple/client/openpitrix/helmwrapper/post_renderer_kustomize.go
  pkg/simple/client/openpitrix/helmwrapper/rest_client_getter.go
Labels: kind/feature, ok-to-test, approved, lgtm, size/XL, release-note-none

#4953 format error log
  pkg/kapis/resources/v1alpha3/handler.go
Labels: approved, size/XS, lgtm, kind/flake, release-note-none
