Repository kubesphere/kubesphere, pull requests merged in 2022-08, with the labels that each got.

#5108 avoid re-allocating ServerRunOptions
  cmd/ks-apiserver/app/server.go
Labels: ok-to-test, approved, size/XS, lgtm, kind/cleanup, release-note-none

#5115 add alerting v2beta1 apis
  pkg/api/alerting/v2beta1/types.go
  pkg/apiserver/apiserver.go
  pkg/client/clientset/versioned/clientset.go
  pkg/client/clientset/versioned/fake/clientset_generated.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/client/clientset/versioned/typed/alerting/v2beta1/alerting_client.go
  pkg/client/clientset/versioned/typed/alerting/v2beta1/clusterrulegroup.go
  pkg/client/clientset/versioned/typed/alerting/v2beta1/doc.go
  pkg/client/clientset/versioned/typed/alerting/v2beta1/fake/doc.go
  pkg/client/clientset/versioned/typed/alerting/v2beta1/fake/fake_alerting_client.go
  pkg/client/clientset/versioned/typed/alerting/v2beta1/fake/fake_clusterrulegroup.go
  pkg/client/clientset/versioned/typed/alerting/v2beta1/fake/fake_globalrulegroup.go
  pkg/client/clientset/versioned/typed/alerting/v2beta1/fake/fake_rulegroup.go
  pkg/client/clientset/versioned/typed/alerting/v2beta1/generated_expansion.go
  pkg/client/clientset/versioned/typed/alerting/v2beta1/globalrulegroup.go
  pkg/client/clientset/versioned/typed/alerting/v2beta1/rulegroup.go
  pkg/client/informers/externalversions/alerting/interface.go
  pkg/client/informers/externalversions/alerting/v2beta1/clusterrulegroup.go
  pkg/client/informers/externalversions/alerting/v2beta1/globalrulegroup.go
  pkg/client/informers/externalversions/alerting/v2beta1/interface.go
  pkg/client/informers/externalversions/alerting/v2beta1/rulegroup.go
  pkg/client/informers/externalversions/factory.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/alerting/v2beta1/clusterrulegroup.go
  pkg/client/listers/alerting/v2beta1/expansion_generated.go
  pkg/client/listers/alerting/v2beta1/globalrulegroup.go
  pkg/client/listers/alerting/v2beta1/rulegroup.go
  pkg/kapis/alerting/v2beta1/handler.go
  pkg/kapis/alerting/v2beta1/register.go
  pkg/models/alerting/rulegroup.go
  pkg/models/alerting/rules/utils.go
  pkg/simple/client/alerting/rule_client.go
  pkg/simple/client/alerting/types.go
  staging/src/kubesphere.io/api/alerting/v2beta1/rulegroup_types.go
Labels: kind/feature, approved, size/XXL, lgtm, release-note

#5120 Update ks-core helm chart
  config/ks-core/templates/ks-controller-manager.yaml
  config/ks-core/templates/role-templates.yaml
Labels: approved, size/S, kind/cleanup, release-note-none

#5114 Fix the tiny typo in ks-openapi-spec
  api/ks-openapi-spec/swagger.json
  pkg/kapis/tenant/v1alpha2/register.go
Labels: approved, size/XS, lgtm, needs-ok-to-test, do-not-merge/release-note-label-needed

#5119 Fix ingress P95 delay time promql statement
  pkg/simple/client/monitoring/prometheus/promql.go
Labels: kind/bug, approved, size/XS, lgtm, release-note

#5134 enhance globalrulegroups
  config/crds/alerting.kubesphere.io_globalrulegroups.yaml
  pkg/api/alerting/v2beta1/types.go
  pkg/controller/alerting/util.go
  pkg/kapis/alerting/v2beta1/register.go
  pkg/models/alerting/rulegroup.go
  staging/src/kubesphere.io/api/alerting/v2beta1/rulegroup_types.go
  staging/src/kubesphere.io/api/alerting/v2beta1/rulegroup_webhook.go
  staging/src/kubesphere.io/api/alerting/v2beta1/zz_generated.deepcopy.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#5130 fix cluster ready condition always true
  pkg/controller/cluster/cluster_controller.go
Labels: approved, size/XS, lgtm, needs-ok-to-test, release-note

#5145 Update role-templates.yaml
  config/ks-core/templates/role-templates.yaml
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#5152 fill field status of helmrepo in response
  pkg/models/openpitrix/types.go
  pkg/models/openpitrix/utils.go
Labels: approved, size/XS, lgtm, needs-ok-to-test, release-note-none

#5147 Remove scheme duplicate registration code
  pkg/controller/storage/capability/capability_controller.go
  pkg/controller/storage/snapshotclass/snapshotclass_controller.go
Labels: approved, lgtm, size/S, kind/cleanup, release-note-none

#5165 chore: add feature-pluggable branch to kubespheredev image build ci jobs
  .github/workflows/build-multiarch.yaml
Labels: approved, size/XS, lgtm, release-note-none

#5166 chore: remove useless build stage
  build/ks-apiserver/Dockerfile
  build/ks-controller-manager/Dockerfile
Labels: approved, size/M, release-note-none

#5146 Fix: index out of range when merging two repo indexes
  pkg/simple/client/openpitrix/helmrepoindex/repo_index.go
  pkg/simple/client/openpitrix/helmrepoindex/repo_index_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#5170 Update ks-core helm chart
  config/ks-core/templates/role-templates.yaml
Labels: approved, size/XS, lgtm, release-note-none

#5171 chore: remove default backend from ks-core helm chart
  config/ks-core/templates/kubesphere-controls-system.yaml
  config/ks-core/values.yaml
Labels: approved, size/L, release-note-none
