Repository kubesphere/kubesphere, pull requests merged in 2022-05, with the labels that each got.

#4838 Fix typo
  pkg/apiserver/apiserver.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#4847 Fix: e2e test failed
  .github/workflows/kind/kind.yaml
  test/e2e/groups.go
Labels: approved, size/XS, lgtm, kind/failing-test, release-note-none

#4605 Cleanup cluster controller and remove unused code
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/cluster/util.go
Labels: approved, lgtm, size/L, kind/cleanup, release-note-none

#4862 Fix disabled status not work for OAuth
  pkg/models/auth/oauth.go
  pkg/models/auth/oauth_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#4866 Fix gpu null pointer exception
  pkg/kapis/config/v1alpha2/register.go
  pkg/simple/client/gpu/options.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#4861 fix tcp match error
  pkg/controller/virtualservice/virtualservice_controller.go
Labels: kind/bug, ok-to-test, approved, size/XS, lgtm, do-not-merge/release-note-label-needed

#4865 fix:modify the default resource reservation of gateway system
  Makefile
  config/crds/gateway.kubesphere.io_gateways.yaml
  config/gateway/templates/nginx-ingress.yaml
  config/gateway/values.yaml
  pkg/models/gateway/gateway.go
  staging/src/kubesphere.io/api/gateway/v1alpha1/gateway_types.go
  staging/src/kubesphere.io/api/gateway/v1alpha1/zz_generated.deepcopy.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#4868 Fix: deny the blocked user request
  pkg/apiserver/authentication/authenticators/jwt/jwt.go
  pkg/kapis/oauth/handler.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#4870 Fix: restricted users cannot activate manually
  pkg/controller/user/user_controller.go
  pkg/controller/user/user_controller_test.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#4880 Add get workspace API
  api/ks-openapi-spec/swagger.json
  pkg/kapis/tenant/v1alpha3/handler.go
  pkg/kapis/tenant/v1alpha3/register.go
  pkg/models/tenant/tenant.go
  staging/src/kubesphere.io/api/cluster/v1alpha1/openapi_generated.go
  staging/src/kubesphere.io/api/devops/v1alpha1/openapi_generated.go
  staging/src/kubesphere.io/api/devops/v1alpha3/openapi_generated.go
  staging/src/kubesphere.io/api/network/v1alpha1/openapi_generated.go
  staging/src/kubesphere.io/api/servicemesh/v1alpha2/openapi_generated.go
  staging/src/kubesphere.io/api/tenant/v1alpha1/openapi_generated.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#4877 Reduce unnecessary status updates
  cmd/controller-manager/app/controllers.go
  pkg/controller/cluster/cluster_controller.go
  pkg/utils/clusterclient/clusterclient.go
Labels: approved, lgtm, size/L, kind/cleanup, release-note-none

#4888 refactor: remove the useless CRD
  pkg/apiserver/apiserver.go
  pkg/client/clientset/versioned/typed/types/v1beta1/fake/fake_federatedresourcequota.go
  pkg/client/clientset/versioned/typed/types/v1beta1/fake/fake_types_client.go
  pkg/client/clientset/versioned/typed/types/v1beta1/federatedresourcequota.go
  pkg/client/clientset/versioned/typed/types/v1beta1/generated_expansion.go
  pkg/client/clientset/versioned/typed/types/v1beta1/types_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/types/v1beta1/federatedresourcequota.go
  pkg/client/informers/externalversions/types/v1beta1/interface.go
  pkg/client/listers/types/v1beta1/expansion_generated.go
  pkg/client/listers/types/v1beta1/federatedresourcequota.go
  staging/src/kubesphere.io/api/gateway/v1alpha1/zz_generated.deepcopy.go
  staging/src/kubesphere.io/api/types/v1beta1/federatedresourcequota_types.go
  staging/src/kubesphere.io/api/types/v1beta1/register.go
  staging/src/kubesphere.io/api/types/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M, kind/cleanup, release-note-none

#4879 fix unformatted log
  pkg/controller/helm/helm_controller.go
Labels: approved, size/XS, lgtm, needs-ok-to-test, release-note-none

#4856 WIP: add lint workflow
  cmd/ks-apiserver/app/options/options.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/dispatch/dispatch.go
  pkg/kapis/metering/v1alpha1/handler.go
  pkg/kapis/metering/v1alpha1/register.go
  pkg/kapis/monitoring/v1alpha3/handler.go
  pkg/kapis/monitoring/v1alpha3/register.go
  pkg/kapis/openpitrix/v1/handler.go
  pkg/kapis/openpitrix/v1/register.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/kapis/tenant/v1alpha3/handler.go
  pkg/kapis/tenant/v1alpha3/register.go
  pkg/models/openpitrix/interface.go
  pkg/models/openpitrix/release.go
  pkg/models/tenant/tenant.go
  pkg/utils/clusterclient/clusterclient.go
  tools/cmd/doc-gen/main.go
Labels: size/L, do-not-merge/work-in-progress, release-note-none

#4896 fix: cluster list granted to users is incorrect
  cmd/controller-manager/app/controllers.go
  pkg/apiserver/apiserver.go
  pkg/controller/cluster/cluster_controller.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/kapis/tenant/v1alpha3/handler.go
  pkg/kapis/tenant/v1alpha3/register.go
  pkg/models/resources/v1alpha3/interface.go
  pkg/models/tenant/tenant.go
  pkg/models/tenant/tenent_test.go
  staging/src/kubesphere.io/api/iam/v1alpha2/types.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#4904 add workspace to review list
  pkg/models/openpitrix/types.go
  pkg/models/openpitrix/utils.go
Labels: approved, size/XS, lgtm, kind/flake, release-note-none

#4915 chore: update vendor
  go.mod
  pkg/controller/network/webhooks/storageclass_accessor.go
  vendor/modules.txt
Labels: approved, lgtm, size/S, kind/cleanup, release-note-none

#4916 add some unit test for models
  pkg/models/resources/v1alpha2/persistentvolumeclaim/persistentvolumeclaims_test.go
  pkg/models/resources/v1alpha3/federatedpersistentvolumeclaim/federatedpersistentvolumeclaims_test.go
Labels: ok-to-test, approved, lgtm, size/L, release-note-none

#4918 fix:goroutine leak when open terminal
  pkg/models/terminal/terminal.go
Labels: kind/bug, ok-to-test, approved, size/XS, lgtm, release-note-none

#4881 feature:test functions in package resources/v1alpha3 by building restful's re…
  pkg/kapis/resources/v1alpha3/handler_test.go
Labels: ok-to-test, approved, lgtm, size/L, release-note-none
