Repository kubesphere/kubesphere, pull requests merged in 2022-12, with the labels that each got.

#5396 Remove the broken test case
  pkg/models/registries/v2/registries_test.go
Labels: approved, lgtm, size/S, kind/failing-test, release-note-none

#5392 controller/cluster: ensure cluster is Ready when cleanup notifications
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/cluster/utils/utils.go
  pkg/utils/clusterclient/clusterclient.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#5407 Fix the registered controller name
  cmd/controller-manager/app/controllers.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#5408 Fix failed to cache resources if group version not found
  pkg/apiserver/apiserver.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#5413 Bump publishing bot go version to 1.18.9
  staging/publishing/rules.yaml
Labels: approved, size/XS, lgtm, kind/flake, release-note-none

#5322 Upgrade dependent version: github.com/deislabs/oras
  go.mod
  staging/src/kubesphere.io/utils/go.mod
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, size/M, release-note, dependencies

#5323 Upgrade dependent version: github.com/containernetworking/cni
  go.mod
  go.sum
  pkg/simple/client/network/ippool/ipam/interface.go
  pkg/simple/client/network/ippool/ipam/ipam.go
  vendor/github.com/containernetworking/cni/pkg/types/020/types.go
  vendor/github.com/containernetworking/cni/pkg/types/040/types.go
  vendor/github.com/containernetworking/cni/pkg/types/args.go
  vendor/github.com/containernetworking/cni/pkg/types/current/types.go
  vendor/github.com/containernetworking/cni/pkg/types/internal/convert.go
  vendor/github.com/containernetworking/cni/pkg/types/internal/create.go
  vendor/github.com/containernetworking/cni/pkg/types/types.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, size/XL, release-note, dependencies

#5420 Upgrade dependent version: helm.sh/helm/v3 v3.9.0 -> v3.10.3
  go.mod
  go.sum
  staging/src/kubesphere.io/api/go.mod
  staging/src/kubesphere.io/api/go.sum
  staging/src/kubesphere.io/client-go/go.mod
  staging/src/kubesphere.io/utils/go.mod
  staging/src/kubesphere.io/utils/go.sum
  vendor/helm.sh/helm/v3/internal/version/version.go
  vendor/helm.sh/helm/v3/pkg/action/install.go
  vendor/helm.sh/helm/v3/pkg/action/lint.go
  vendor/helm.sh/helm/v3/pkg/action/list.go
  vendor/helm.sh/helm/v3/pkg/action/uninstall.go
  vendor/helm.sh/helm/v3/pkg/action/upgrade.go
  vendor/helm.sh/helm/v3/pkg/chart/dependency.go
  vendor/helm.sh/helm/v3/pkg/chart/metadata.go
  vendor/helm.sh/helm/v3/pkg/chartutil/create.go
  vendor/helm.sh/helm/v3/pkg/chartutil/jsonschema.go
  vendor/helm.sh/helm/v3/pkg/chartutil/values.go
  vendor/helm.sh/helm/v3/pkg/cli/environment.go
  vendor/helm.sh/helm/v3/pkg/downloader/chart_downloader.go
  vendor/helm.sh/helm/v3/pkg/engine/lookup_func.go
  vendor/helm.sh/helm/v3/pkg/getter/ocigetter.go
  vendor/helm.sh/helm/v3/pkg/kube/ready.go
  vendor/helm.sh/helm/v3/pkg/kube/wait.go
  vendor/helm.sh/helm/v3/pkg/pusher/ocipusher.go
  vendor/helm.sh/helm/v3/pkg/registry/client.go
  vendor/helm.sh/helm/v3/pkg/repo/chartrepo.go
  vendor/helm.sh/helm/v3/pkg/repo/index.go
  vendor/helm.sh/helm/v3/pkg/repo/repo.go
  vendor/helm.sh/helm/v3/pkg/storage/driver/util.go
  vendor/helm.sh/helm/v3/pkg/strvals/parser.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, size/L, release-note, dependencies

#5401 Fix missing maintainers in helm apps
  pkg/simple/client/openpitrix/helmrepoindex/load_package.go
  pkg/utils/reposcache/repo_cahes.go
Labels: kind/bug, ok-to-test, approved, lgtm, size/S, release-note-none

#5422 fix: Resolved some data out of sync after live-reload.
  cmd/controller-manager/app/options/options.go
  cmd/ks-apiserver/app/options/options.go
  pkg/kapis/openpitrix/v1/handler.go
  pkg/models/openpitrix/interface.go
  pkg/simple/client/ldap/ldap.go
Labels: kind/bug, approved, lgtm, size/S, kind/cleanup, release-note-none

#5425 fix Home field fault in appstore application
  pkg/models/openpitrix/utils.go
Labels: approved, size/XS, lgtm, release-note

#5428 fix: ks-apiserver panic error: ServiceAccount's Secret index out of r…
  pkg/kapis/servicemesh/metrics/v1alpha2/handler.go
Labels: approved, lgtm, size/S, release-note

#5432 Bump sigs.k8s.io/controller-tools from 0.6.2 to 0.11.1
  Makefile
  go.mod
  go.sum
  staging/src/kubesphere.io/api/go.mod
  staging/src/kubesphere.io/api/go.sum
  staging/src/kubesphere.io/client-go/go.mod
  staging/src/kubesphere.io/client-go/go.sum
  staging/src/kubesphere.io/utils/go.mod
  staging/src/kubesphere.io/utils/go.sum
  vendor/github.com/klauspost/compress/fse/README.md
  vendor/github.com/klauspost/compress/huff0/README.md
  vendor/github.com/oliveagle/jsonpath/.travis.yml
  vendor/github.com/oliveagle/jsonpath/readme.md
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/conv.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/doc.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/flatten.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/known_types.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/crd.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/doc.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/topology.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/validation.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/markers/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/schema.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/spec.go
  vendor/sigs.k8s.io/controller-tools/pkg/crd/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/deepcopy/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/doc.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/genall.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/help/pretty/doc.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/options.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/output.go
  vendor/sigs.k8s.io/controller-tools/pkg/genall/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/loader/doc.go
  vendor/sigs.k8s.io/controller-tools/pkg/loader/loader.go
  vendor/sigs.k8s.io/controller-tools/pkg/loader/refs.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/collect.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/doc.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/parse.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/reg.go
  vendor/sigs.k8s.io/controller-tools/pkg/markers/zip.go
  vendor/sigs.k8s.io/controller-tools/pkg/rbac/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/rbac/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/schemapatcher/gen.go
  vendor/sigs.k8s.io/controller-tools/pkg/schemapatcher/zz_generated.markerhelp.go
  vendor/sigs.k8s.io/controller-tools/pkg/version/version.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/parser.go
  vendor/sigs.k8s.io/controller-tools/pkg/webhook/zz_generated.markerhelp.go
Labels: kind/feature, approved, size/XXL, lgtm, kind/cleanup, release-note-none
