Repository kubesphere/kubesphere, pull requests merged in 2022-04, with the labels that each got.

#4752 Update go mod files
  go.mod
  vendor/modules.txt
Labels: approved, size/XS, lgtm, kind/cleanup, release-note-none

#4770 Add storageclass accessor to ks
  cmd/controller-manager/app/server.go
  config/crds/storage.kubesphere.io_storageclasseraccessor.yaml
  config/ks-core/templates/webhook.yaml
  go.mod
  go.sum
  pkg/controller/network/webhooks/storageclass_accessor.go
  vendor/github.com/kubesphere/storageclass-accessor/LICENSE
  vendor/github.com/kubesphere/storageclass-accessor/client/apis/accessor/v1alpha1/accessor_types.go
  vendor/github.com/kubesphere/storageclass-accessor/client/apis/accessor/v1alpha1/groupversion_info.go
  vendor/github.com/kubesphere/storageclass-accessor/client/apis/accessor/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/kubesphere/storageclass-accessor/webhook/certwatcher.go
  vendor/github.com/kubesphere/storageclass-accessor/webhook/convert.go
  vendor/github.com/kubesphere/storageclass-accessor/webhook/pvc.go
  vendor/github.com/kubesphere/storageclass-accessor/webhook/scheme.go
  vendor/github.com/kubesphere/storageclass-accessor/webhook/selector.go
  vendor/github.com/kubesphere/storageclass-accessor/webhook/validation.go
  vendor/github.com/kubesphere/storageclass-accessor/webhook/weebhook.go
  vendor/github.com/spf13/cobra/.gitignore
  vendor/github.com/spf13/cobra/.golangci.yml
  vendor/github.com/spf13/cobra/.travis.yml
  vendor/github.com/spf13/cobra/CHANGELOG.md
  vendor/github.com/spf13/cobra/CONDUCT.md
  vendor/github.com/spf13/cobra/CONTRIBUTING.md
  vendor/github.com/spf13/cobra/Makefile
  vendor/github.com/spf13/cobra/README.md
  vendor/github.com/spf13/cobra/args.go
  vendor/github.com/spf13/cobra/bash_completions.go
  vendor/github.com/spf13/cobra/bash_completions.md
  vendor/github.com/spf13/cobra/bash_completionsV2.go
  vendor/github.com/spf13/cobra/cobra.go
  vendor/github.com/spf13/cobra/command.go
  vendor/github.com/spf13/cobra/completions.go
  vendor/github.com/spf13/cobra/fish_completions.go
  vendor/github.com/spf13/cobra/fish_completions.md
  vendor/github.com/spf13/cobra/go.mod
  vendor/github.com/spf13/cobra/go.sum
  vendor/github.com/spf13/cobra/powershell_completions.go
  vendor/github.com/spf13/cobra/powershell_completions.md
  vendor/github.com/spf13/cobra/projects_using_cobra.md
  vendor/github.com/spf13/cobra/shell_completions.go
  vendor/github.com/spf13/cobra/shell_completions.md
  vendor/github.com/spf13/cobra/user_guide.md
  vendor/github.com/spf13/cobra/zsh_completions.go
  vendor/github.com/spf13/cobra/zsh_completions.md
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm, release-note

#4784 change the default audit webhook port
  pkg/apiserver/auditing/backend.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#4803 docs: update kubekey version to v2.0.0
  README.md
Labels: approved, size/XS, lgtm, needs-ok-to-test, kind/documentation, release-note-none

#4831 Double check in clusterclient if the cluster exists but is not cached
  pkg/utils/clusterclient/clusterclient.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#4833 fix controller-manager Dockerfile kustomize targetos
  build/ks-controller-manager/Dockerfile
Labels: ok-to-test, approved, size/XS, lgtm, do-not-merge/release-note-label-needed

#4815 fix: fix the gateway variable name.
  Makefile
  pkg/models/gateway/gateway.go
  pkg/models/gateway/gateway_test.go
  staging/src/kubesphere.io/api/gateway/v1alpha1/gateway_types.go
  staging/src/kubesphere.io/api/gateway/v1alpha1/zz_generated.deepcopy.go
Labels: kind/bug, ok-to-test, approved, lgtm, size/S, do-not-merge/release-note-label-needed

#4835 Fix crash caused by resouce discovery failed
  pkg/apiserver/apiserver.go
  pkg/informers/informers.go
  pkg/simple/client/k8s/kubernetes.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none
