Repository kubesphere/kubesphere, pull requests merged in 2022-01, with the labels that each got.

#4578 Support snapshotclass management
  pkg/models/resources/v1alpha3/resource/resource.go
  pkg/models/resources/v1alpha3/volumesnapshotclass/volumesnapshotclass.go
  pkg/models/resources/v1alpha3/volumesnapshotclass/volumesnapshotclass_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#4581 fix: the configuration of the Istio virtualservice is overwritten
  pkg/controller/virtualservice/virtualservice_controller.go
  pkg/controller/virtualservice/virtualservice_controller_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#4460 update quick start and feature list in README
  README.md
  README_zh.md
Labels: approved, lgtm, size/M, kind/documentation, release-note-none

#4584 Sync the expiration time of kubeconfig cert file of the cluster
  pkg/controller/cluster/cluster_controller.go
  pkg/kapis/cluster/v1alpha1/handler.go
  pkg/kapis/cluster/v1alpha1/handler_test.go
  pkg/utils/k8sutil/k8sutil.go
  staging/src/kubesphere.io/api/cluster/v1alpha1/cluster_types.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#4602 fix helm_controller assignment to entry in nil map
  pkg/controller/helm/helm_controller.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#4579 Add a function to shell access to the node in the kubesphere
  pkg/apiserver/apiserver.go
  pkg/apiserver/config/config.go
  pkg/apiserver/config/config_test.go
  pkg/kapis/terminal/v1alpha2/handler.go
  pkg/kapis/terminal/v1alpha2/register.go
  pkg/models/terminal/options.go
  pkg/models/terminal/terminal.go
  tools/cmd/doc-gen/main.go
Labels: kind/feature, ok-to-test, approved, lgtm, size/L, kind/api-change, kind/documentation, release-note

#4599 Fix: deepcopy before mutating shared objects
  pkg/models/resources/v1alpha2/persistentvolumeclaim/persistentvolumeclaims.go
  pkg/models/resources/v1alpha2/storageclass/storageclasses.go
  pkg/models/resources/v1alpha2/storageclass/storageclasses_test.go
  pkg/models/resources/v1alpha3/node/nodes.go
  pkg/models/resources/v1alpha3/node/nodes_test.go
  pkg/models/resources/v1alpha3/persistentvolumeclaim/persistentvolumeclaim.go
  pkg/models/resources/v1alpha3/persistentvolumeclaim/persistentvolumeclaim_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#4618 Remove unused helm template
  config/ks-core/Chart.yaml
  config/ks-core/templates/ks-apiserver.yml
  config/ks-core/templates/ks-router-cm.yaml
  config/ks-core/templates/ks-router-config.tpl
  config/ks-core/values.yaml
Labels: approved, lgtm, size/L, kind/flake, release-note-none

#4446 Support importing Grafana templates to the workspace level.
  pkg/apiserver/apiserver.go
  pkg/kapis/metering/v1alpha1/handler.go
  pkg/kapis/metering/v1alpha1/register.go
  pkg/kapis/monitoring/v1alpha3/dashboard_template_test.sh
  pkg/kapis/monitoring/v1alpha3/handler.go
  pkg/kapis/monitoring/v1alpha3/helper_test.go
  pkg/kapis/monitoring/v1alpha3/register.go
  pkg/kapis/monitoring/v1alpha3/scripts/dashboard_template_debug.sh
  pkg/simple/client/monitoring/types.go
  tools/cmd/doc-gen/main.go
Labels: kind/feature, area/console, ok-to-test, approved, lgtm, size/L, kind/api-change, release-note

#4621 Adjust metrics query for monitoring components upgrade
  pkg/simple/client/alerting/rule_client_test.go
  pkg/simple/client/monitoring/prometheus/promql.go
Labels: area/monitoring, approved, lgtm, size/S, release-note

#4626 Delete gateway when namespace is deleted
  cmd/controller-manager/app/controllers.go
  pkg/controller/namespace/namespace_controller.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#4617 feat: Serving CRD in ks apiserver
  pkg/apiserver/apiserver.go
  pkg/kapis/crd/crd.go
  pkg/models/crds/interface.go
  pkg/models/crds/interface_test.go
  pkg/models/crds/typed_handler.go
  pkg/models/crds/typed_handler_test.go
  pkg/models/crds/unstructured_handler.go
Labels: kind/feature, approved, lgtm, size/XL, release-note-none

#4596 Support snapshotcontent management
  pkg/models/resources/v1alpha3/resource/resource.go
  pkg/models/resources/v1alpha3/volumesnapshotcontent/volumesnapshotcontent.go
  pkg/models/resources/v1alpha3/volumesnapshotcontent/volumesnapshotcontent_test.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#4643 Optimize the error message
  pkg/simple/client/es/versions/error.go
  pkg/simple/client/es/versions/v5/v5.go
  pkg/simple/client/es/versions/v6/v6.go
  pkg/simple/client/es/versions/v7/v7.go
  pkg/simple/client/logging/elasticsearch/elasticsearch_test.go
Labels: kind/feature, approved, lgtm, size/M, release-note-none
