Repository kubesphere/kubesphere, pull requests merged in 2022-03, with the labels that each got.

#4660 add pvc-autoresizer controller to ks-controller-manager
  cmd/controller-manager/app/controllers.go
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/server.go
  go.mod
  go.sum
  vendor/github.com/kubesphere/pvc-autoresizer/LICENSE
  vendor/github.com/kubesphere/pvc-autoresizer/metrics/kubernetes_client.go
  vendor/github.com/kubesphere/pvc-autoresizer/metrics/mertics.go
  vendor/github.com/kubesphere/pvc-autoresizer/metrics/metrics_client.go
  vendor/github.com/kubesphere/pvc-autoresizer/metrics/resizer.go
  vendor/github.com/kubesphere/pvc-autoresizer/runners/constants.go
  vendor/github.com/kubesphere/pvc-autoresizer/runners/fake_client_wrapper.go
  vendor/github.com/kubesphere/pvc-autoresizer/runners/metrics_client.go
  vendor/github.com/kubesphere/pvc-autoresizer/runners/pvc_autoresizer.go
  vendor/github.com/kubesphere/pvc-autoresizer/runners/workload_autorestarter.go
  vendor/modules.txt
Labels: kind/feature, approved, size/XXL, lgtm, release-note

#4691 Fix the "index out of range" issue when sort metrics
  pkg/models/monitoring/sort_page.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#4705 add node device usage metrics
  pkg/models/monitoring/named_metrics.go
  pkg/simple/client/monitoring/prometheus/promql.go
Labels: kind/feature, approved, size/XS, lgtm, release-note

#4686 Proxy DevOps APIs with group name and version
  pkg/apiserver/apiserver.go
  pkg/kapis/devops/group.go
  pkg/kapis/devops/register.go
  pkg/kapis/devops/register_test.go
  pkg/kapis/devops/v1alpha2/OWNERS
  pkg/kapis/devops/v1alpha2/register.go
  pkg/kapis/devops/v1alpha3/register.go
  tools/cmd/doc-gen/main.go
Labels: area/devops, approved, lgtm, size/L, tide/merge-method-squash, kind/cleanup, kind/api-change, release-note-none

#4679 Set the name of the current cluster into the kubesphere-config configmap
  cmd/controller-manager/app/controllers.go
  pkg/apiserver/config/config.go
  pkg/constants/constants.go
  pkg/controller/cluster/cluster_controller.go
  pkg/kapis/cluster/v1alpha1/handler.go
  pkg/kapis/cluster/v1alpha1/handler_test.go
  pkg/simple/client/multicluster/options.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#4711 add container processes/threads metrics
  pkg/models/monitoring/named_metrics.go
  pkg/simple/client/monitoring/prometheus/promql.go
Labels: kind/feature, approved, size/XS, lgtm, release-note

#4701 Add "readyToUse" filter field for volumesnapshotcontent
  pkg/models/resources/v1alpha3/volumesnapshotcontent/volumesnapshotcontent.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#4718 Add "snapshot-count" annotation for volumesnapshotClass
  pkg/models/resources/v1alpha3/volumesnapshotclass/volumesnapshotclass.go
  pkg/models/resources/v1alpha3/volumesnapshotclass/volumesnapshotclass_test.go
Labels: kind/feature, approved, lgtm, size/M, release-note-none

#4721 Refactor workspace API and introduced tenant v1alpha3 version
  api/ks-openapi-spec/swagger.json
  pkg/apiserver/apiserver.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/kapis/tenant/v1alpha3/handler.go
  pkg/kapis/tenant/v1alpha3/register.go
  pkg/models/tenant/metering.go
  pkg/models/tenant/tenant.go
  pkg/models/tenant/tenent_test.go
  tools/cmd/doc-gen/main.go
Labels: kind/feature, approved, lgtm, size/XL, release-note-none

#4734 Check if the cluster is the same when updating kubeconfig
  pkg/kapis/cluster/v1alpha1/handler.go
Labels: kind/feature, approved, lgtm, size/S, release-note-none

#4751 Add omitempty option to LoginHistoryMaximumEntries field to avoid it being set to 0
  pkg/apiserver/authentication/options.go
  pkg/apiserver/config/config_test.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none
