Repository kubesphere/kubesphere, pull requests merged in 2022-02, with the labels that each got.

#4664 fix typo in comment
  pkg/controller/user/user_controller.go
Labels: approved, size/XS, lgtm, needs-ok-to-test, do-not-merge/release-note-label-needed

#4678 Fix registry verification failed
  pkg/models/registries/v2/secret_authenticator.go
  pkg/models/registries/v2/secret_authenticator_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#4651 Use the kube-system UID to identify if the member cluster already exists
  api/ks-openapi-spec/swagger.json
  api/openapi-spec/swagger.json
  config/crds/cluster.kubesphere.io_clusters.yaml
  pkg/controller/cluster/cluster_controller.go
  pkg/kapis/cluster/v1alpha1/handler.go
  pkg/kapis/cluster/v1alpha1/handler_test.go
  staging/src/kubesphere.io/api/cluster/v1alpha1/cluster_types.go
  staging/src/kubesphere.io/api/cluster/v1alpha1/openapi_generated.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#4659 feat: live-reload when configuration changed
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/server.go
  cmd/ks-apiserver/app/server.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/config/config.go
  pkg/kapis/metering/v1alpha1/handler.go
  pkg/kapis/metering/v1alpha1/register.go
  pkg/kapis/monitoring/v1alpha3/handler.go
  pkg/kapis/monitoring/v1alpha3/helper_test.go
  pkg/kapis/monitoring/v1alpha3/register.go
  pkg/kapis/openpitrix/v1/handler.go
  pkg/kapis/openpitrix/v1/register.go
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/kapis/tenant/v1alpha2/register.go
  pkg/models/openpitrix/interface.go
  pkg/models/tenant/tenant.go
  pkg/models/tenant/tenent_test.go
  pkg/utils/metrics/metrics.go
  tools/cmd/doc-gen/main.go
Labels: kind/feature, ok-to-test, approved, lgtm, size/L, release-note

#4681 Unify the omitempty configuration of YAML annotation
  pkg/apiserver/authentication/oauth/options.go
  pkg/apiserver/authorization/options.go
  pkg/apiserver/config/config_test.go
  pkg/models/terminal/options.go
  pkg/simple/client/auditing/options.go
  pkg/simple/client/cache/options.go
  pkg/simple/client/devops/jenkins/options.go
  pkg/simple/client/events/options.go
  pkg/simple/client/gateway/options.go
  pkg/simple/client/gpu/options.go
  pkg/simple/client/k8s/options.go
  pkg/simple/client/ldap/options.go
  pkg/simple/client/logging/options.go
  pkg/simple/client/monitoring/prometheus/prometheus_options.go
  pkg/simple/client/multicluster/options.go
  pkg/simple/client/network/options.go
  pkg/simple/client/notification/options.go
  pkg/simple/client/s3/options.go
  pkg/simple/client/servicemesh/options.go
  pkg/simple/client/sonarqube/options.go
Labels: approved, lgtm, size/L, kind/cleanup, release-note-none
