Repository kubesphere/kubesphere, pull requests merged in 2022-11, with the labels that each got.

#5340 fix rulegroup state filter
  pkg/api/alerting/v2beta1/types.go
  pkg/kapis/alerting/v2beta1/register.go
  pkg/models/alerting/rulegroup.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#5345 update k8s versions
  README.md
  README_zh.md
Labels: approved, size/XS, lgtm, release-note-none

#5350 limit rule count per group
  staging/src/kubesphere.io/api/alerting/v2beta1/rulegroup_webhook.go
Labels: kind/feature, approved, lgtm, size/S, release-note-none

#5349 fix rulegroup typemeta miss
  pkg/models/alerting/rulegroup.go
  staging/src/kubesphere.io/api/alerting/v2beta1/rulegroup_types.go
Labels: approved, lgtm, size/M, release-note-none

#5352 Calculating the Number of Logs in opensearch
  pkg/simple/client/es/versions/opensearchv1/opensearchv1.go
  pkg/simple/client/es/versions/opensearchv2/opensearchv2.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#5353 add label_matcher param to filter alerts
  pkg/api/alerting/v2beta1/types.go
  pkg/kapis/alerting/v2beta1/register.go
  pkg/models/alerting/rulegroup.go
Labels: approved, lgtm

#5351 update k8s versions
  README.md
  README_zh.md
Labels: approved, size/XS, lgtm, release-note-none

#5342 Fix:Goroutine leaks when getting audit event sender times out
  pkg/apiserver/auditing/backend.go
Labels: kind/bug, ok-to-test, approved, size/XS, lgtm, release-note-none

#5367 Fix: remove unnecessary case in field selector
  pkg/models/resources/v1alpha3/secret/secrets.go
Labels: ok-to-test, approved, size/XS, lgtm, release-note-none

#5316 Upgrade dependent version: github.com/opencontainers/runc
  go.mod
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, size/S, release-note, dependencies

#5381 fix rule status
  pkg/models/alerting/rulegroup.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#5380 Remove the VolumeSnapshot controller that creates a snapshot class automatically
  cmd/controller-manager/app/controllers.go
  pkg/controller/storage/snapshotclass/snapshotclass_controller.go
  pkg/controller/storage/snapshotclass/snapshotclass_controller_test.go
Labels: approved, lgtm, size/L, release-note-none

#5390 Add api /version and deprecated api /kapi/version
  pkg/kapis/version/register.go
Labels: approved, lgtm, size/M, kind/api-change, release-note
