Repository kubesphere/kubesphere, pull requests merged in 2022-10, with the labels that each got.

#5263 Fix: Can not resolve the resource scope correctly
  pkg/apiserver/request/requestinfo.go
Labels: kind/bug, approved, size/XS, lgtm, do-not-merge/release-note-label-needed

#5271 Dependency: update storageClass-accessor
  go.mod
  go.sum
  vendor/github.com/kubesphere/storageclass-accessor/webhook/pvc.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#5268 fix #5267 by renaming yaml struct tag
  pkg/apiserver/authentication/identityprovider/ldap/ldap.go
Labels: ok-to-test, approved, size/XS, lgtm, kind/cleanup, release-note-none

#5279 support scoped nodes and workloads for global rules
  config/crds/alerting.kubesphere.io_clusterrulegroups.yaml
  config/crds/alerting.kubesphere.io_globalrulegroups.yaml
  config/crds/alerting.kubesphere.io_rulegroups.yaml
  staging/src/kubesphere.io/api/alerting/v2beta1/rulegroup_types.go
  staging/src/kubesphere.io/api/alerting/v2beta1/rulegroup_webhook.go
  staging/src/kubesphere.io/api/alerting/v2beta1/zz_generated.deepcopy.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#5266 refactor: move from io/ioutil to io and os packages
  pkg/apiserver/auditing/types.go
  pkg/apiserver/authentication/identityprovider/aliyunidaas/idaas.go
  pkg/apiserver/authentication/identityprovider/github/github.go
  pkg/apiserver/authentication/identityprovider/ldap/ldap.go
  pkg/apiserver/authentication/identityprovider/ldap/ldap_test.go
  pkg/apiserver/authentication/identityprovider/oidc/oidc.go
  pkg/apiserver/authentication/token/issuer.go
  pkg/apiserver/config/config_test.go
  pkg/controller/cluster/helper.go
  pkg/controller/helm/helm_controller_test.go
  pkg/kapis/cluster/v1alpha1/handler.go
  pkg/kapis/monitoring/v1alpha3/handler.go
  pkg/kapis/network/v1alpha2/handler.go
  pkg/kapis/notification/v2beta2/handler.go
  pkg/kapis/openpitrix/v1/handler.go
  pkg/kapis/servicemesh/metrics/v1alpha2/handler.go
  pkg/models/devops/devops.go
  pkg/models/kubeconfig/kubeconfig.go
  pkg/models/monitoring/sort_page_test.go
  pkg/models/notification/notification.go
  pkg/models/registries/registry_client.go
  pkg/models/routers/routers.go
  pkg/simple/client/devops/fake/fakedevops.go
  pkg/simple/client/devops/jenkins/jenkins.go
  pkg/simple/client/devops/jenkins/request.go
  pkg/simple/client/devops/jenkins/utils.go
  pkg/simple/client/es/client_test.go
  pkg/simple/client/es/versions/opensearchv1/opensearchv1.go
  pkg/simple/client/es/versions/opensearchv2/opensearchv2.go
  pkg/simple/client/es/versions/v5/v5.go
  pkg/simple/client/es/versions/v6/v6.go
  pkg/simple/client/es/versions/v7/v7.go
  pkg/simple/client/kiali/client.go
  pkg/simple/client/kiali/client_test.go
  pkg/simple/client/kiali/mock_client.go
  pkg/simple/client/logging/elasticsearch/elasticsearch_test.go
  pkg/simple/client/monitoring/metricsserver/metricsserver_test.go
  pkg/simple/client/monitoring/prometheus/prometheus_test.go
  pkg/simple/client/openpitrix/helmrepoindex/repo_index.go
  pkg/simple/client/openpitrix/helmwrapper/helm_wrapper_test.go
  pkg/simple/client/s3/fake/fakes3.go
  pkg/test/testing.go
  staging/src/kubesphere.io/api/servicemesh/v1alpha2/strategy_types_test.go
  tools/cmd/crd-doc-gen/main.go
  tools/cmd/doc-gen/main.go
Labels: ok-to-test, approved, lgtm, size/L, kind/cleanup, release-note-none

#5298 fix empty rules in rulegroup of prometheusrules
  pkg/controller/alerting/util.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#5299 Check the cluster ID (kube-system UID) when updating the cluster
  cmd/controller-manager/app/server.go
  pkg/controller/cluster/cluster_webhook.go
Labels: kind/feature, ok-to-test, approved, lgtm, size/M, release-note-none

#5283 Add switch for notification
  pkg/apiserver/apiserver.go
  pkg/simple/client/notification/options.go
Labels: kind/feature, approved, lgtm, size/M, release-note-none

#5305 optimize ks-core chart
  config/ks-core/templates/NOTES.txt
  config/ks-core/templates/_helpers.tpl
  config/ks-core/templates/account.yaml
  config/ks-core/templates/ks-console.yml
  config/ks-core/templates/sample-bookinfo-configmap.yaml
  config/ks-core/values.yaml
Labels: approved, lgtm, size/L, kind/cleanup, release-note

#5302 Check cluster permission for create/update workspacetemplate
  pkg/kapis/tenant/v1alpha2/handler.go
  pkg/models/tenant/tenant.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#5311 fix global alerts filter
  pkg/models/alerting/rulegroup.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#5300 support fieldselector filter query secrets
  go.mod
  go.sum
  pkg/kapis/resources/v1alpha3/register.go
  pkg/models/resources/v1alpha3/secret/secrets.go
  vendor/github.com/oliveagle/jsonpath/.gitignore
  vendor/github.com/oliveagle/jsonpath/.travis.yml
  vendor/github.com/oliveagle/jsonpath/LICENSE
  vendor/github.com/oliveagle/jsonpath/jsonpath.go
  vendor/github.com/oliveagle/jsonpath/readme.md
  vendor/modules.txt
Labels: kind/feature, ok-to-test, approved, lgtm, size/XL, release-note-none

#5331 Fix: globalrole has cluster management right can not manage cluster
  pkg/models/tenant/tenant.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#5335 update readme for cloud
  README.md
  README_zh.md
Labels: approved, lgtm, size/M, release-note-none

#5337 3.3.1 CHANGELOG
  CHANGELOG/CHANGELOG-3.3.1.md
Labels: approved, lgtm, size/M, release-note-none
