Repository kubesphere/kubesphere, pull requests merged in 2022-07, with the labels that each got.

#5019 Update readme for KubeSphere v3.3.0
  README.md
  README_zh.md
Labels: approved, lgtm, size/M, kind/documentation, release-note-none

#5020 cleanup: remove useless file
  pkg/simple/client/db/db.go
Labels: approved, lgtm, size/S, kind/cleanup, release-note-none

#5024 close remote terminal.(#5023)
  pkg/models/terminal/terminal.go
Labels: kind/bug, approved, lgtm, size/S, needs-ok-to-test, release-note-none

#4994 add some unit tests for pkg/api
  pkg/api/alerting/v2alpha1/types_test.go
  pkg/api/auditing/v1alpha1/types_test.go
  pkg/api/events/v1alpha1/types_test.go
  pkg/api/logging/v1alpha2/types_test.go
  pkg/api/metering/v1alpha1/types_test.go
Labels: ok-to-test, approved, lgtm, size/XL, release-note-none

#5035 Remove extra space in Makefile
  Makefile
Labels: approved, size/XS, lgtm, kind/cleanup, release-note-none

#5038 golang-lint skips dir pkg/client
  .golangci.yaml
  hack/verify-golangci-lint.sh
Labels: approved, size/XS, lgtm, kind/flake, release-note-none

#5018 [KS-OIDC] Remove special characters form sub OIDC standard claim
  pkg/apiserver/authentication/identityprovider/oidc/oidc.go
  pkg/apiserver/authentication/identityprovider/oidc/oidc_test.go
Labels: ok-to-test, approved, size/XS, lgtm, do-not-merge/release-note-label-needed

#5041 Delete Helm and Kustomize binaries in Dockerfile
  build/ks-apiserver/Dockerfile
  build/ks-controller-manager/Dockerfile
Labels: kind/feature, ok-to-test, approved, lgtm, size/S, release-note-none

#5050 add opensearch test
  pkg/simple/client/es/client_test.go
  pkg/simple/client/es/testdata/opensearchv2_detect_version_major_200.json
  pkg/simple/client/es/testdata/opensearchv2_search_200.json
  pkg/simple/client/es/testdata/opensearchv2_search_200_result.json
Labels: approved, lgtm, size/L, release-note-none

#5064 add rulegroup definitions for different scopes
  Makefile
  config/crds/alerting.kubesphere.io_clusterrulegroups.yaml
  config/crds/alerting.kubesphere.io_globalrulegroups.yaml
  config/crds/alerting.kubesphere.io_rulegroups.yaml
  staging/src/kubesphere.io/api/alerting/group.go
  staging/src/kubesphere.io/api/alerting/v2beta1/doc.go
  staging/src/kubesphere.io/api/alerting/v2beta1/register.go
  staging/src/kubesphere.io/api/alerting/v2beta1/rulegroup_types.go
  staging/src/kubesphere.io/api/alerting/v2beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: kind/feature, approved, lgtm, do-not-merge/hold, size/XL, release-note

#5071 add admission webhook for rulegroups
  cmd/controller-manager/app/server.go
  pkg/apis/addtoscheme_alerting_v2beta1.go
  staging/src/kubesphere.io/api/alerting/v2beta1/rulegroup_webhook.go
  staging/src/kubesphere.io/api/go.mod
  staging/src/kubesphere.io/api/go.sum
Labels: kind/feature, approved, lgtm, size/XL, release-note

#5069 change default comment style of license header
  .licenserc.yaml
  hack/update-licenses.sh
Labels: approved, lgtm, size/S, kind/flake, release-note-none

#5075 Adjust container terminal priority: bash, sh
  pkg/models/terminal/terminal.go
Labels: approved, size/XS, lgtm, needs-ok-to-test, do-not-merge/release-note-label-needed

#5074 golint with new commit
  hack/verify-golangci-lint.sh
Labels: approved, lgtm, size/S, kind/flake, release-note-none

#5078 skip generated code when fmt code
  hack/update-gofmt.sh
  hack/verify-gofmt.sh
Labels: approved, size/XS, lgtm, kind/flake, do-not-merge/release-note-label-needed

#5072 test: add anonymous unit test
  pkg/apiserver/authentication/request/anonymous/anonymous_test.go
Labels: ok-to-test, approved, lgtm, size/M, release-note-none

#5084 ci: update go version to 1.18
  .github/workflows/e2e-test.yml
  .github/workflows/nightly-builds.yml
  build/ks-apiserver/Dockerfile
  build/ks-controller-manager/Dockerfile
Labels: ok-to-test, approved, lgtm, size/S, do-not-merge/release-note-label-needed

#5082 Add annotation to Makefile for deprecated deepcopy and clientset
  Makefile
Labels: approved, size/XS, lgtm, release-note-none

#5088 add apis for switch the notification language
  pkg/apiserver/apiserver.go
  pkg/kapis/notification/v2beta2/handler.go
  pkg/kapis/notification/v2beta2/register.go
  pkg/models/notification/notification.go
  pkg/models/resources/v1alpha3/notification/notification.go
  pkg/models/resources/v1alpha3/resource/resource.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#5101 Fix ks-core helm chart
  config/ks-core/templates/role-templates.yaml
  config/ks-core/values.yaml
  pkg/apiserver/apiserver.go
Labels: approved, lgtm
