Repository kubesphere/kubesphere, pull requests merged in 2023-04, with the labels that each got.

#5624 Remove the incorrect custom MarshalJSON method to avoid infinite recursion
  pkg/simple/client/cache/cache.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#5615 Update utils.go
  pkg/models/alerting/rules/utils.go
Labels: kind/bug, ok-to-test, approved, lgtm, size/S, release-note-none

#5623 Use the generic Set to replace deprecated methods
  cmd/controller-manager/app/controllers.go
  cmd/controller-manager/app/options/options.go
  kube/pkg/apis/core/v1/helper/qos/qos.go
  kube/pkg/quota/v1/evaluator/core/pods.go
  kube/pkg/quota/v1/resources.go
  kube/plugin/pkg/admission/resourcequota/controller.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/authorization/path/path.go
  pkg/apiserver/request/requestinfo.go
  pkg/apiserver/request/requestinfo_test.go
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/destinationrule/destinationrule_controller.go
  pkg/controller/virtualservice/virtualservice_controller.go
  pkg/models/tenant/tenant.go
  pkg/server/healthz/healthz.go
  pkg/simple/client/cache/inmemory_cache_test.go
Labels: approved, lgtm, size/L, kind/cleanup, release-note-none

#5627 Bump github.com/docker/docker from 20.10.23+incompatible to 20.10.24+incompatible
  go.mod
  go.sum
  staging/src/kubesphere.io/api/go.mod
  staging/src/kubesphere.io/api/go.sum
  staging/src/kubesphere.io/utils/go.mod
  staging/src/kubesphere.io/utils/go.sum
  vendor/github.com/docker/docker/api/types/filters/parse.go
  vendor/github.com/docker/docker/api/types/registry/registry.go
  vendor/github.com/docker/docker/api/types/time/timestamp.go
  vendor/github.com/docker/docker/client/client.go
  vendor/github.com/docker/docker/client/config_inspect.go
  vendor/github.com/docker/docker/client/container_attach.go
  vendor/github.com/docker/docker/client/container_inspect.go
  vendor/github.com/docker/docker/client/container_logs.go
  vendor/github.com/docker/docker/client/image_inspect.go
  vendor/github.com/docker/docker/client/network_inspect.go
  vendor/github.com/docker/docker/client/node_inspect.go
  vendor/github.com/docker/docker/client/plugin_inspect.go
  vendor/github.com/docker/docker/client/request.go
  vendor/github.com/docker/docker/client/secret_inspect.go
  vendor/github.com/docker/docker/client/service_inspect.go
  vendor/github.com/docker/docker/client/task_inspect.go
  vendor/github.com/docker/docker/client/volume_inspect.go
  vendor/github.com/docker/docker/pkg/ioutils/fswriters.go
  vendor/github.com/docker/docker/pkg/ioutils/temp_unix.go
  vendor/github.com/docker/docker/pkg/ioutils/temp_windows.go
  vendor/github.com/docker/docker/registry/endpoint_v1.go
  vendor/github.com/docker/docker/registry/registry.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, size/L, kind/cleanup, release-note, dependencies

#5625 Move struct DynamicOptions to package pkg/server
  pkg/apiserver/authentication/identityprovider/aliyunidaas/idaas.go
  pkg/apiserver/authentication/identityprovider/aliyunidaas/idaas_test.go
  pkg/apiserver/authentication/identityprovider/cas/cas.go
  pkg/apiserver/authentication/identityprovider/generic_provider.go
  pkg/apiserver/authentication/identityprovider/github/github.go
  pkg/apiserver/authentication/identityprovider/github/github_test.go
  pkg/apiserver/authentication/identityprovider/identity_provider_test.go
  pkg/apiserver/authentication/identityprovider/ldap/ldap.go
  pkg/apiserver/authentication/identityprovider/ldap/ldap_test.go
  pkg/apiserver/authentication/identityprovider/oauth_provider.go
  pkg/apiserver/authentication/identityprovider/oidc/oidc.go
  pkg/apiserver/authentication/identityprovider/oidc/oidc_test.go
  pkg/apiserver/authentication/oauth/options.go
  pkg/models/auth/oauth_test.go
  pkg/models/auth/password_test.go
  pkg/server/options/dynamic_options.go
  pkg/simple/client/cache/cache.go
  pkg/simple/client/cache/factory.go
  pkg/simple/client/cache/inmemory_cache.go
  pkg/simple/client/cache/options.go
  pkg/simple/client/cache/redis.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#5637 Merge multiple duplicate tools files
  pkg/tools.go
  tools/tools.go
Labels: approved, lgtm, size/M, kind/cleanup, release-note-none

#5612 IAM v1beta1 controllers
  cmd/controller-manager/app/controllers.go
  pkg/apis/addtoscheme_iam_v1beta1.go
  pkg/conponenthelper/auth/rbac/clusterrole_interface.go
  pkg/conponenthelper/auth/rbac/globalrole_interfaces.go
  pkg/conponenthelper/auth/rbac/helper.go
  pkg/conponenthelper/auth/rbac/interface.go
  pkg/conponenthelper/auth/rbac/policy_comparator.go
  pkg/conponenthelper/auth/rbac/role_interfaces.go
  pkg/conponenthelper/auth/rbac/workspacerole_interfaces.go
  pkg/controller/clusterrole/clusterrole_controller.go
  pkg/controller/globalrole/globalrole_controller.go
  pkg/controller/role/role_controller.go
  pkg/controller/roletemplate/roletemplate_controller.go
  pkg/controller/workspacerole/workspacerole_controller.go
  pkg/utils/sliceutil/sliceutils.go
  staging/src/kubesphere.io/api/iam/v1beta1/types.go
  staging/src/kubesphere.io/api/iam/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, approved, size/XXL, lgtm, area/iam, release-note

#5655 [release-3.3] controller/cluster: retry when updating the KubeFedCluster conflicted
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/cluster/join.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#5650 Uniform code format
  pkg/controller/job/job_controller.go
  pkg/controller/network/nsnetworkpolicy/nsnetworkpolicy_controller.go
  pkg/utils/clusterclient/clusterclient.go
Labels: ok-to-test, approved, lgtm, size/S, kind/cleanup, release-note-none
