Repository kubesphere/kubesphere, pull requests merged in 2023-07, with the labels that each got.

#5802 Fix webhook validation issue for new clusters
  pkg/controller/cluster/cluster_webhook.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#5807 apis/resources: support for searching alias in annotations
  pkg/apiserver/query/field.go
  pkg/models/resources/v1alpha3/interface.go
Labels: kind/feature, approved, lgtm, size/S, release-note

#5820 chore(deps): bump google.golang.org/grpc from 1.52.3 to 1.53.0
  go.mod
  go.sum
  staging/src/kubesphere.io/api/go.mod
  staging/src/kubesphere.io/api/go.sum
  staging/src/kubesphere.io/utils/go.mod
  staging/src/kubesphere.io/utils/go.sum
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/internal/httprule/parse.go
  vendor/github.com/grpc-ecosystem/grpc-gateway/v2/runtime/errors.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/credentials/tls.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/encoding/encoding.go
  vendor/google.golang.org/grpc/encoding/gzip/gzip.go
  vendor/google.golang.org/grpc/grpclog/loggerv2.go
  vendor/google.golang.org/grpc/internal/binarylog/method_logger.go
  vendor/google.golang.org/grpc/internal/binarylog/sink.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/envconfig/xds.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go
  vendor/google.golang.org/grpc/internal/resolver/passthrough/passthrough.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/defaults.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/pickfirst.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, kind/cleanup, size/XL, release-note, dependencies

#5819 fix: enableMultiLogin configuration does not take effect
  pkg/kapis/oauth/handler.go
  pkg/models/auth/token.go
  pkg/simple/client/cache/inmemory_cache.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#5836 feat: support gitlab identity provider
  pkg/apiserver/authentication/identityprovider/gitlab/gitlab.go
  pkg/apiserver/authentication/identityprovider/gitlab/gitlab_test.go
  pkg/apiserver/authentication/options.go
Labels: kind/feature, ok-to-test, approved, lgtm, size/L, release-note

#5833 Use autoscaling/v2 instead of autoscaling/v2beta2
  pkg/api/types.go
  pkg/apiserver/apiserver.go
  pkg/models/resources/v1alpha2/hpa/horizontalpodautoscalers.go
Labels: ok-to-test, approved, lgtm, size/S, kind/api-change, release-note

#5848 Modify permission path
  pkg/kapis/notification/v2beta2/register.go
Labels: approved, size/XS, lgtm, kind/api-change, release-note

#5834 add rule_type label to indicate rule type
  pkg/controller/alerting/util.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none
