Repository kubesphere/kubesphere, pull requests merged in 2023-10, with the labels that each got.

#5927 update storageclass-accessor webhook
  cmd/controller-manager/app/server.go
  go.mod
  go.sum
  pkg/controller/storage/webhooks/storageclass_accessor.go
  staging/src/kubesphere.io/api/go.sum
  staging/src/kubesphere.io/client-go/go.sum
  staging/src/kubesphere.io/utils/go.sum
  vendor/github.com/kubesphere/storageclass-accessor/webhook/certwatcher.go
  vendor/github.com/kubesphere/storageclass-accessor/webhook/pvc.go
  vendor/github.com/kubesphere/storageclass-accessor/webhook/scheme.go
  vendor/github.com/kubesphere/storageclass-accessor/webhook/selector.go
  vendor/github.com/kubesphere/storageclass-accessor/webhook/validation.go
  vendor/github.com/kubesphere/storageclass-accessor/webhook/weebhook.go
  vendor/modules.txt
Labels: kind/bug, kind/feature, approved, lgtm, size/XL, release-note

#5925 Fixed an issue where categories were not updated in the App Store aft…
  pkg/models/openpitrix/applicationversions.go
Labels: ok-to-test, approved, size/XS, lgtm, release-note

#5940 chore(deps): bump golang.org/x/net from 0.7.0 to 0.17.0
  go.mod
  go.sum
  staging/src/kubesphere.io/api/go.mod
  staging/src/kubesphere.io/api/go.sum
  staging/src/kubesphere.io/client-go/go.mod
  staging/src/kubesphere.io/client-go/go.sum
  staging/src/kubesphere.io/utils/go.mod
  staging/src/kubesphere.io/utils/go.sum
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/escape.go
  vendor/golang.org/x/net/html/render.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/Dockerfile
  vendor/golang.org/x/net/http2/Makefile
  vendor/golang.org/x/net/http2/pipe.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/writesched.go
  vendor/golang.org/x/net/http2/writesched_roundrobin.go
  vendor/golang.org/x/net/idna/idna9.0.0.go
  vendor/golang.org/x/net/idna/tables13.0.0.go
  vendor/golang.org/x/net/idna/tables15.0.0.go
  vendor/golang.org/x/net/idna/trie.go
  vendor/golang.org/x/net/idna/trie12.0.0.go
  vendor/golang.org/x/net/idna/trie13.0.0.go
  vendor/golang.org/x/net/internal/socks/socks.go
  vendor/golang.org/x/net/publicsuffix/data/children
  vendor/golang.org/x/net/publicsuffix/data/nodes
  vendor/golang.org/x/net/publicsuffix/data/text
  vendor/golang.org/x/net/publicsuffix/table.go
  vendor/modules.txt
Labels: kind/bug, approved, size/XXL, lgtm, kind/cleanup, release-note, dependencies

#5941 utils/clusterclient: fix the deadlock issue when getting the cluster client
  pkg/utils/clusterclient/clusterclient.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#5950 fix: gateway address is not displayed
  pkg/models/gateway/gateway.go
Labels: kind/bug, approved, size/XS, lgtm, release-note

#5948 fix: when helm application modify, but UpdateTime not update
  pkg/models/openpitrix/applications.go
Labels: ok-to-test, approved, size/XS, lgtm, release-note-none

#5957 Images tag
  pkg/kapis/resources/v1alpha3/handler.go
  pkg/kapis/resources/v1alpha3/register.go
  pkg/models/registries/v2/registries.go
  pkg/models/registries/v2/types.go
Labels: kind/feature, approved, lgtm, size/S, release-note
