Repository kubesphere/kubesphere, pull requests merged in 2023-11, with the labels that each got.

#5975 bump golangci-lint to v1.55.2
  hack/verify-golangci-lint.sh
Labels: approved, size/XS, kind/cleanup, release-note-none

#5973 chore(deps): bump google.golang.org/grpc from 1.53.0 to 1.56.3
  go.mod
  go.sum
  staging/src/kubesphere.io/api/go.mod
  staging/src/kubesphere.io/api/go.sum
  staging/src/kubesphere.io/client-go/go.mod
  staging/src/kubesphere.io/client-go/go.sum
  staging/src/kubesphere.io/utils/go.mod
  staging/src/kubesphere.io/utils/go.sum
  vendor/google.golang.org/grpc/CONTRIBUTING.md
  vendor/google.golang.org/grpc/attributes/attributes.go
  vendor/google.golang.org/grpc/balancer/balancer.go
  vendor/google.golang.org/grpc/balancer_conn_wrappers.go
  vendor/google.golang.org/grpc/binarylog/grpc_binarylog_v1/binarylog.pb.go
  vendor/google.golang.org/grpc/call.go
  vendor/google.golang.org/grpc/clientconn.go
  vendor/google.golang.org/grpc/codes/code_string.go
  vendor/google.golang.org/grpc/dialoptions.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health.pb.go
  vendor/google.golang.org/grpc/health/grpc_health_v1/health_grpc.pb.go
  vendor/google.golang.org/grpc/idle.go
  vendor/google.golang.org/grpc/internal/binarylog/binarylog.go
  vendor/google.golang.org/grpc/internal/binarylog/method_logger.go
  vendor/google.golang.org/grpc/internal/buffer/unbounded.go
  vendor/google.golang.org/grpc/internal/envconfig/envconfig.go
  vendor/google.golang.org/grpc/internal/envconfig/observability.go
  vendor/google.golang.org/grpc/internal/envconfig/xds.go
  vendor/google.golang.org/grpc/internal/grpclog/prefixLogger.go
  vendor/google.golang.org/grpc/internal/grpcrand/grpcrand.go
  vendor/google.golang.org/grpc/internal/grpcsync/callback_serializer.go
  vendor/google.golang.org/grpc/internal/internal.go
  vendor/google.golang.org/grpc/internal/metadata/metadata.go
  vendor/google.golang.org/grpc/internal/serviceconfig/duration.go
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/handler_server.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/internal/transport/http_util.go
  vendor/google.golang.org/grpc/internal/transport/logging.go
  vendor/google.golang.org/grpc/internal/transport/transport.go
  vendor/google.golang.org/grpc/metadata/metadata.go
  vendor/google.golang.org/grpc/picker_wrapper.go
  vendor/google.golang.org/grpc/pickfirst.go
  vendor/google.golang.org/grpc/resolver/manual/manual.go
  vendor/google.golang.org/grpc/resolver/resolver.go
  vendor/google.golang.org/grpc/resolver_conn_wrapper.go
  vendor/google.golang.org/grpc/rpc_util.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/service_config.go
  vendor/google.golang.org/grpc/stats/stats.go
  vendor/google.golang.org/grpc/status/status.go
  vendor/google.golang.org/grpc/stream.go
  vendor/google.golang.org/grpc/version.go
  vendor/google.golang.org/grpc/vet.sh
  vendor/modules.txt
Labels: kind/bug, approved, size/XXL, lgtm, kind/cleanup, release-note, dependencies

#5987 update 3.4.1 changelog
  CHANGELOG/CHANGELOG-3.4.1.md
Labels: approved, lgtm, size/L, kind/documentation, release-note-none

#5965 Update OWNERS
  OWNERS
Labels: approved, size/XS, lgtm, kind/documentation, release-note-none
