Repository kubesphere/kubesphere, pull requests merged in 2023-03, with the labels that each got.

#5558 Fix: cannot extract identity provider name
  pkg/kapis/oauth/handler.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#5561 fix rulegroups to prometheusrules
  pkg/controller/alerting/util.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#5562 Use batch/v1 instead of batch/v1beta1
  pkg/api/types.go
  pkg/apiserver/apiserver.go
  pkg/models/quotas/quotas.go
  pkg/models/resources/v1alpha2/cronjob/cronjobs.go
Labels: approved, lgtm, size/S, kind/api-change, release-note

#5502 Add iam v1beta1 APIs
  config/ks-core/crds/iam.kubesphere.io_loginrecords.yaml
  pkg/apiserver/query/types.go
  pkg/kapis/iam/v1alpha2/register.go
  staging/src/kubesphere.io/api/iam/v1beta1/category_types.go
  staging/src/kubesphere.io/api/iam/v1beta1/clusterrole_types.go
  staging/src/kubesphere.io/api/iam/v1beta1/doc.go
  staging/src/kubesphere.io/api/iam/v1beta1/globalrole_types.go
  staging/src/kubesphere.io/api/iam/v1beta1/register.go
  staging/src/kubesphere.io/api/iam/v1beta1/role_types.go
  staging/src/kubesphere.io/api/iam/v1beta1/roletemplate_types.go
  staging/src/kubesphere.io/api/iam/v1beta1/types.go
  staging/src/kubesphere.io/api/iam/v1beta1/workspacerole_types.go
  staging/src/kubesphere.io/api/iam/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XL, release-note

#5564 call validate when config update coz apiserver restart
  cmd/ks-apiserver/app/server.go
Labels: kind/bug, ok-to-test, approved, size/XS, lgtm, release-note

#5573 Fix dynamic resource API
  pkg/apiserver/apiserver.go
  pkg/apiserver/dispatch/dispatch_test.go
  pkg/apiserver/filters/auditing.go
  pkg/apiserver/filters/authentication.go
  pkg/apiserver/filters/authorization.go
  pkg/apiserver/filters/dispatch.go
  pkg/apiserver/filters/dynamicresource.go
  pkg/apiserver/filters/kubeapiserver.go
  pkg/apiserver/filters/middleware.go
  pkg/apiserver/filters/multicluster.go
  pkg/apiserver/filters/requestinfo.go
  pkg/apiserver/filters/responder.go
  pkg/apiserver/proxies/unregistered.go
  pkg/models/resources/v1beta1/cache.go
  pkg/models/resources/v1beta1/interface.go
  pkg/models/resources/v1beta1/resourcelgetter.go
  pkg/models/resources/v1beta1/resourcemanager.go
Labels: approved, size/XXL, lgtm, release-note-none

#5582 fix:Return cluster gateway duplicates
  pkg/models/gateway/gateway.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#5590 fix hyperlink content in README_zh.md
  README_zh.md
Labels: approved, size/XS, lgtm, needs-ok-to-test, kind/documentation, release-note-none

#5591 fix hyperlink content in README_zh.md
  README_zh.md
Labels: approved, size/XS, lgtm, needs-ok-to-test, kind/documentation, release-note-none

#5599 Bump github.com/containerd/containerd from v1.6.16 to 1.6.18
  go.mod
  go.sum
  staging/src/kubesphere.io/utils/go.mod
  staging/src/kubesphere.io/utils/go.sum
  vendor/github.com/containerd/containerd/platforms/defaults_windows.go
  vendor/github.com/containerd/containerd/version/version.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, size/M, kind/cleanup, release-note, dependencies

#5609 chore: install goimports automatically
  hack/update-goimports.sh
  hack/verify-goimports.sh
  hack/verify-golangci-lint.sh
Labels: approved, lgtm, size/M, kind/cleanup, release-note-none
