Repository kubesphere/kubesphere, pull requests merged in 2023-08, with the labels that each got.

#5885 update README.md
  README.md
  README_zh.md
Labels: approved, size/L, kind/documentation, release-note-none

#5878 Validate clusterRole when adding a cluster
  pkg/kapis/cluster/v1alpha1/handler.go
  pkg/kapis/cluster/v1alpha1/handler_test.go
  pkg/simple/client/multicluster/options.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#5894 update 3.4 changelog
  CHANGELOG/CHANGELOG-3.4.0.md
Labels: approved, lgtm, size/L
