Repository kubesphere/kubesphere, pull requests merged in 2023-09, with the labels that each got.

#5895 change v3.4.0 release note url
  README_zh.md
Labels: approved, size/XS, kind/documentation

#5907 update go-restful/v3 to v3.11.0
  go.mod
  go.sum
  staging/src/kubesphere.io/api/go.mod
  staging/src/kubesphere.io/api/go.sum
  staging/src/kubesphere.io/client-go/go.mod
  staging/src/kubesphere.io/client-go/go.sum
  staging/src/kubesphere.io/utils/go.mod
  staging/src/kubesphere.io/utils/go.sum
  vendor/github.com/emicklei/go-restful/v3/CHANGES.md
  vendor/github.com/emicklei/go-restful/v3/README.md
  vendor/github.com/emicklei/go-restful/v3/route.go
  vendor/github.com/emicklei/go-restful/v3/route_builder.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, size/XL, release-note-none

#5909 Update base image version to alpine 3.18.3
  build/ks-apiserver/Dockerfile
  build/ks-controller-manager/Dockerfile
Labels: kind/feature, approved, size/XS, lgtm, release-note

#5908 Add more devops supported k8s version
  README.md
  README_zh.md
Labels: approved, size/XS, lgtm, release-note

#5921 Feat: Support search pods by pod ip
  pkg/models/resources/v1alpha3/pod/pods.go
Labels: approved, lgtm, size/S, release-note
