Repository kubesphere/kubesphere, pull requests merged in 2023-05, with the labels that each got.

#5665 controller/cluster: improve the process for updating the cluster certificate's expiration date
  pkg/controller/cluster/cluster_controller.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#5666 Fix wrong params naming in openpitrix
  pkg/kapis/openpitrix/v1/handler.go
  pkg/models/openpitrix/release.go
Labels: kind/bug, ok-to-test, approved, lgtm, size/S, kind/api-change, release-note-none

#5671 refactor: remove usless options
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/server.go
  cmd/ks-apiserver/apiserver.go
  cmd/ks-apiserver/app/options/options.go
  cmd/ks-apiserver/app/server.go
  pkg/apiserver/apiserver.go
  pkg/simple/client/cache/cache.go
  pkg/simple/client/cache/inmemory_cache.go
  pkg/simple/client/cache/options.go
  pkg/simple/client/s3/s3.go
  vendor/k8s.io/component-base/cli/OWNERS
  vendor/k8s.io/component-base/cli/run.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, kind/cleanup, release-note-none

#5674 Improve Unreasonable Comments
  pkg/controller/certificatesigningrequest/certificatesigningrequest_controller.go
  pkg/controller/clusterrolebinding/clusterrolebinding_controller.go
  pkg/controller/globalrole/globalrole_controller.go
  pkg/controller/globalrolebinding/globalrolebinding_controller.go
  pkg/controller/notification/notification_controller.go
Labels: ok-to-test, approved, lgtm, size/M, kind/cleanup, release-note-none

#5601 Add write operation for dynamic resource
  pkg/apiserver/filters/dynamicresource.go
  pkg/apiserver/request/requestinfo.go
  pkg/models/resources/v1beta1/interface.go
  pkg/models/resources/v1beta1/resourcemanager.go
Labels: approved, lgtm, size/L, release-note

#5677 docs: modified section about style shields display issues in readme
  README.md
Labels: approved, size/XS, lgtm, kind/documentation, release-note-none

#5678 docs: modified section about style shields display issues in readme-zh
  README_zh.md
Labels: size/XS, kind/documentation, release-note-none

#5682 Bump github.com/docker/distribution from 2.8.1+incompatible to 2.8.2+incompatible
  go.mod
  go.sum
  staging/src/kubesphere.io/api/go.mod
  staging/src/kubesphere.io/api/go.sum
  staging/src/kubesphere.io/utils/go.mod
  staging/src/kubesphere.io/utils/go.sum
  vendor/github.com/docker/distribution/.dockerignore
  vendor/github.com/docker/distribution/.golangci.yml
  vendor/github.com/docker/distribution/.mailmap
  vendor/github.com/docker/distribution/Dockerfile
  vendor/github.com/docker/distribution/Makefile
  vendor/github.com/docker/distribution/docker-bake.hcl
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/registry/api/v2/descriptors.go
  vendor/github.com/docker/distribution/registry/api/v2/errors.go
  vendor/github.com/docker/distribution/registry/client/errors.go
  vendor/github.com/docker/distribution/registry/client/repository.go
  vendor/github.com/docker/distribution/registry/client/transport/http_reader.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, size/L, kind/cleanup, release-note, dependencies

#5690 Migrate iam CRDs version to v1beta1
  staging/src/kubesphere.io/api/iam/v1beta1/im_types.go
  staging/src/kubesphere.io/api/iam/v1beta1/register.go
  staging/src/kubesphere.io/api/iam/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#5696 apiserver: fix the issue that the /kapis/version API cannot be matched by routing
  pkg/apiserver/runtime/runtime.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none
