Repository kubesphere/kubesphere, pull requests merged in 2023-02, with the labels that each got.

#5416 ResourceGetter v1beta1
  cmd/ks-apiserver/app/options/options.go
  pkg/apiserver/apiserver.go
  pkg/apiserver/filters/middleware.go
  pkg/apiserver/proxies/unregistered.go
  pkg/apiserver/query/types.go
  pkg/kapis/crd/crd.go
  pkg/models/crds/interface_test.go
  pkg/models/crds/typed_handler.go
  pkg/models/crds/typed_handler_test.go
  pkg/models/crds/unstructured_handler.go
  pkg/models/resources/v1alpha3/secret/secrets_test.go
  pkg/models/resources/v1beta1/cache.go
  pkg/models/resources/v1beta1/interface.go
  pkg/models/resources/v1beta1/resourcelgetter.go
Labels: kind/feature, approved, size/XXL, lgtm, kind/api-change, release-note

#5512 3.3.2 Changelog
  CHANGELOG/CHANGELOG-3.3.2.md
Labels: approved, lgtm, size/L, release-note-none

#5511 chore: Bump golangci-lint to v1.51.1
  .golangci.yaml
  hack/lib/golang.sh
  hack/tools/Makefile
  hack/tools/README.md
  hack/tools/go.mod
  hack/tools/go.sum
  hack/verify-all.sh
  hack/verify-golangci-lint.sh
Labels: approved, size/XXL, lgtm, kind/failing-test, release-note-none

#5516 Update the password minimum length to 8
  config/ks-core/crds/iam.kubesphere.io_federatedusers.yaml
  config/ks-core/crds/iam.kubesphere.io_users.yaml
  staging/src/kubesphere.io/api/iam/v1alpha2/types.go
Labels: kind/feature, approved, size/XS, lgtm, release-note

#5515 Fix cannot get registered resource
  pkg/apiserver/proxies/unregistered.go
  pkg/models/resources/v1beta1/cache.go
  pkg/models/resources/v1beta1/resourcelgetter.go
Labels: kind/bug, approved, size/XS, lgtm, release-note

#5529 chore(docs): Update to the latest v3.3.2
  README.md
  README_zh.md
Labels: approved, size/XS, lgtm, needs-ok-to-test, kind/documentation, release-note-none

#5532 Use golang-jwt/jwt instead of form3tech-oss/jwt-go
  LICENSES/vendor/github.com/golang-jwt/jwt/v4/LICENSE
  go.mod
  go.sum
  pkg/apiserver/authentication/identityprovider/oidc/oidc.go
  pkg/apiserver/authentication/identityprovider/oidc/oidc_test.go
  pkg/apiserver/authentication/token/issuer.go
  pkg/apiserver/authentication/token/issuer_test.go
  pkg/kapis/oauth/handler.go
  pkg/simple/client/devops/jenkins/request.go
  staging/src/kubesphere.io/api/go.mod
  staging/src/kubesphere.io/api/go.sum
  staging/src/kubesphere.io/client-go/go.mod
  staging/src/kubesphere.io/client-go/go.sum
  staging/src/kubesphere.io/utils/go.mod
  staging/src/kubesphere.io/utils/go.sum
  vendor/github.com/form3tech-oss/jwt-go/.travis.yml
  vendor/github.com/form3tech-oss/jwt-go/MIGRATION_GUIDE.md
  vendor/github.com/form3tech-oss/jwt-go/claims.go
  vendor/github.com/form3tech-oss/jwt-go/map_claims.go
  vendor/github.com/form3tech-oss/jwt-go/token.go
  vendor/github.com/golang-jwt/jwt/v4/.gitignore
  vendor/github.com/golang-jwt/jwt/v4/LICENSE
  vendor/github.com/golang-jwt/jwt/v4/MIGRATION_GUIDE.md
  vendor/github.com/golang-jwt/jwt/v4/README.md
  vendor/github.com/golang-jwt/jwt/v4/VERSION_HISTORY.md
  vendor/github.com/golang-jwt/jwt/v4/claims.go
  vendor/github.com/golang-jwt/jwt/v4/doc.go
  vendor/github.com/golang-jwt/jwt/v4/ecdsa.go
  vendor/github.com/golang-jwt/jwt/v4/ecdsa_utils.go
  vendor/github.com/golang-jwt/jwt/v4/ed25519.go
  vendor/github.com/golang-jwt/jwt/v4/ed25519_utils.go
  vendor/github.com/golang-jwt/jwt/v4/errors.go
  vendor/github.com/golang-jwt/jwt/v4/hmac.go
  vendor/github.com/golang-jwt/jwt/v4/map_claims.go
  vendor/github.com/golang-jwt/jwt/v4/none.go
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v4/parser_option.go
  vendor/github.com/golang-jwt/jwt/v4/rsa.go
  vendor/github.com/golang-jwt/jwt/v4/rsa_pss.go
  vendor/github.com/golang-jwt/jwt/v4/rsa_utils.go
  vendor/github.com/golang-jwt/jwt/v4/signing_method.go
  vendor/github.com/golang-jwt/jwt/v4/staticcheck.conf
  vendor/github.com/golang-jwt/jwt/v4/token.go
  vendor/github.com/golang-jwt/jwt/v4/types.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, kind/cleanup, release-note-none

#5542 Update version root path
  pkg/kapis/version/register.go
Labels: kind/feature, approved, size/XS, lgtm, release-note

#5543 fix: can not re-upgrade helm application in a failed state
  pkg/controller/openpitrix/helmrelease/helm_release_controller.go
  pkg/models/openpitrix/release.go
Labels: kind/bug, ok-to-test, approved, lgtm, size/S, release-note-none

#5555 Fix: Get nothing when the filter is empty
  pkg/models/resources/v1beta1/interface.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#5548 Revert PR #5018
  pkg/apiserver/authentication/identityprovider/oidc/oidc.go
  pkg/apiserver/authentication/identityprovider/oidc/oidc_test.go
Labels: kind/feature, approved, size/XS, lgtm, release-note

#5534 Add api for identity provider login
  pkg/apiserver/authentication/authenticators/basic/basic.go
  pkg/kapis/oauth/handler.go
  pkg/kapis/oauth/register.go
  pkg/models/auth/authenticator.go
  pkg/models/auth/password.go
  pkg/models/auth/password_test.go
  staging/src/kubesphere.io/api/iam/v1alpha2/types.go
Labels: approved, lgtm, size/L, kind/api-change, release-note
