Repository kubesphere/kubesphere, pull requests merged in 2023-01, with the labels that each got.

#5443 Update the url of slack
  README.md
  README_zh.md
Labels: approved, size/XS, lgtm, release-note-none

#5445 feat: Gateway supports the configuration of forwarding tcp/udp traffic.
  config/crds/gateway.kubesphere.io_gateways.yaml
  config/gateway/templates/nginx-ingress.yaml
  config/gateway/values.yaml
  staging/src/kubesphere.io/api/gateway/v1alpha1/gateway_types.go
  staging/src/kubesphere.io/api/gateway/v1alpha1/zz_generated.deepcopy.go
Labels: kind/feature, approved, lgtm, size/S, release-note

#5446 Upgrade go version to 1.19
  .github/workflows/e2e-test.yml
  .github/workflows/nightly-builds.yml
  build/ks-apiserver/Dockerfile
  build/ks-controller-manager/Dockerfile
  go.mod
  staging/publishing/rules.yaml
  staging/src/kubesphere.io/api/go.mod
  staging/src/kubesphere.io/client-go/go.mod
  staging/src/kubesphere.io/utils/go.mod
  vendor/modules.txt
Labels: kind/feature, approved, lgtm, size/S, kind/cleanup, release-note-none

#5462 Resolved Conflict [release-3.3] fix: Resolved some data out of sync after live-reload. #5458
  cmd/controller-manager/app/options/options.go
  cmd/ks-apiserver/app/options/options.go
  pkg/kapis/openpitrix/v1/handler.go
  pkg/models/openpitrix/interface.go
  pkg/simple/client/ldap/ldap.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#5457 fix: concurrent map read and map write caused by reloading in ks-apiserver
  cmd/ks-apiserver/app/options/options.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#5465 Resolved Conflict [release-3.3] Fix id generate error in IPv6-only environment. #5419
  pkg/utils/idutils/id_utils.go
Labels: kind/bug, approved, lgtm, size/M, kind/cleanup, release-note

#5466 Resolved Conflict [release-3.3] Fix failed to cache resources if group version not found #5408
  pkg/apiserver/apiserver.go
Labels: kind/bug, approved, size/XS, lgtm, kind/cleanup, release-note-none

#5483 adjust Pod status filter
  pkg/models/resources/v1alpha3/pod/pods.go
  pkg/models/resources/v1alpha3/pod/pods_test.go
Labels: kind/bug, approved, lgtm, size/L, release-note-none

#5080 Add RoleTemplate CRD
  staging/src/kubesphere.io/api/iam/v1beta1/category_types.go
  staging/src/kubesphere.io/api/iam/v1beta1/clusterrole_types.go
  staging/src/kubesphere.io/api/iam/v1beta1/globalrole_types.go
  staging/src/kubesphere.io/api/iam/v1beta1/register.go
  staging/src/kubesphere.io/api/iam/v1beta1/role_types.go
  staging/src/kubesphere.io/api/iam/v1beta1/roletemplate_types.go
  staging/src/kubesphere.io/api/iam/v1beta1/workspacerole_types.go
  staging/src/kubesphere.io/api/iam/v1beta1/zz_generated.deepcopy.go
Labels: kind/feature, approved, lgtm, size/L, kind/api-change, release-note

#5467 fix the issue that the upload app template did not display icons
  pkg/models/openpitrix/applications.go
  pkg/models/openpitrix/types.go
Labels: approved, lgtm, size/S, release-note

#5490 feat: upgrade ingress nginx version.
  build/ks-controller-manager/Dockerfile
  config/gateway/values.yaml
Labels: kind/feature, approved, size/XS, lgtm, release-note

#5496 feat: update health check API
  pkg/apiserver/apiserver.go
  pkg/server/healthz/healthz.go
Labels: approved, lgtm, size/L, release-note-none
