Repository kubesphere/kubesphere, pull requests merged in 2023-06, with the labels that each got.

#5778 chore: slice replace loop
  kube/plugin/pkg/admission/resourcequota/resource_access.go
Labels: ok-to-test, approved, size/XS, lgtm, kind/cleanup, release-note-none

#5779 chore: pkg imported more than once
  pkg/controller/job/job_controller_test.go
  pkg/simple/client/openpitrix/helmwrapper/post_renderer_kustomize.go
Labels: ok-to-test, approved, size/XS, lgtm, kind/cleanup, release-note-none

#5786 refactor: code reformat
  pkg/simple/client/openpitrix/helmwrapper/post_renderer_kustomize.go
Labels: approved, size/XS, lgtm, kind/cleanup, release-note-none

#5792 feat: upgrade servicemesh version
  pkg/simple/client/kiali/client.go
Labels: kind/feature, approved, size/XS, lgtm, release-note

#5793 fix: the infinite loop after installation failure
  pkg/controller/openpitrix/helmrelease/helm_release_controller.go
Labels: kind/bug, approved, size/XS, release-note

#5794 Support configuring the maximum number of logs that can be exported
  pkg/simple/client/es/versions/opensearchv1/opensearchv1.go
  pkg/simple/client/es/versions/opensearchv2/opensearchv2.go
  pkg/simple/client/es/versions/v5/v5.go
  pkg/simple/client/es/versions/v6/v6.go
  pkg/simple/client/es/versions/v7/v7.go
  pkg/simple/client/logging/elasticsearch/elasticsearch.go
  pkg/simple/client/logging/options.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#5795 Fix: require cluster name can not be repeated
  config/ks-core/crds/tenant.kubesphere.io_workspacetemplates.yaml
  staging/src/kubesphere.io/api/types/v1beta1/types.go
Labels: kind/bug, approved, size/XS, lgtm, release-note

#5797 fix: clear all oauth Providers when reloading configuration
  pkg/apiserver/authentication/identityprovider/identity_provider.go
  pkg/apiserver/authentication/identityprovider/identity_provider_test.go
Labels: kind/bug, approved, lgtm, size/S, release-note
