Repository kubesphere/kubesphere, pull requests merged in 2024-09, with the labels that each got.

#6157 fix chunked encoding API no response
  pkg/apiserver/auditing/client.go
  pkg/apiserver/filters/filters.go
Labels: approved, size/S, release-note-none

#6159 fix: change default go-version for code sync rule
  staging/publishing/rules.yaml
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#6160 add CHANGELOG-4.1.1.md
  CHANGELOG/CHANGELOG-4.1.1.md
Labels: approved, lgtm, size/L, release-note-none

#6161 push difference docker repo by tags
  .github/workflows/build-multiarch.yaml
Labels: approved, lgtm, size/S, kind/documentation, release-note-none

#6162 fix: sync image to aliyuns repo
  .github/workflows/build-multiarch.yaml
Labels: approved, lgtm, size/M, kind/documentation, release-note-none

#6163 fix: sync helm chart to diff dir
  .github/workflows/build-multiarch.yaml
  .github/workflows/sync-helm-chart.yaml
Labels: approved, lgtm, size/M, kind/documentation, release-note-none

#6166 fix typo (#1965)
  pkg/controller/application/apprelease_controller.go
Labels: approved, size/XS, lgtm, release-note-none

#6167 Update telemetry config
  config/ks-core/templates/kubesphere-config.yaml
  config/ks-core/values.yaml
Labels: approved, lgtm, size/S, release-note-none

#6168 feat: add extension-museum in helm
  config/ks-core/Chart.yaml
  config/ks-core/templates/_images.tpl
  config/ks-core/templates/extension-museum.yaml
  config/ks-core/values.yaml
Labels: kind/feature, approved, lgtm, size/M, release-note

#6171 Use responsewriter.UserProvidedDecorator instead of auto flush response
  pkg/apiserver/auditing/client.go
  pkg/apiserver/filters/auditing.go
  pkg/apiserver/filters/filters.go
Labels: approved, size/M, kind/cleanup, release-note-none

#6177 sync helm chart to main when build a helm-chart release
  .github/workflows/sync-helm-chart.yaml
Labels: kind/feature, approved, size/XS, lgtm, release-note-none

#6178 fix: cronjob.batch/v1 is invalid in k8s v1.19
  config/ks-core/Chart.yaml
  config/ks-core/templates/extension-museum.yaml
Labels: approved, size/XS, lgtm, kind/documentation, release-note-none

#6190 sync images to huaweicloud
  .github/workflows/build-multiarch.yaml
Labels: approved, lgtm, size/S, kind/cleanup, release-note

#6191 Update sync-helm-chart.yaml
  .github/workflows/sync-helm-chart.yaml
Labels: approved, size/XS, lgtm, release-note-none

#6195 fix: add tls when get repository index.
  Makefile
  config/ks-core/charts/ks-crds/crds/application.kubesphere.io_applicationreleases.yaml
  config/ks-core/charts/ks-crds/crds/kubesphere.io_repositories.yaml
  config/ks-core/templates/extension-museum.yaml
  hack/generate_manifests.sh
  pkg/controller/core/installplan_controller.go
  pkg/controller/core/repository_controller.go
  pkg/controller/core/util.go
  pkg/kapis/package/v1alpha1/handler.go
  staging/src/kubesphere.io/api/core/v1alpha1/repository_types.go
  staging/src/kubesphere.io/utils/helm/repo_index.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6199 fix: failed to get PR in kubesphere/helm-charts
  .github/workflows/sync-helm-chart.yaml
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#6201 fix: add annotation checksum/cert to extensions-museum pod
  config/ks-core/templates/extension-museum.yaml
Labels: approved, lgtm, size/S, release-note

#6200 feat: Adapt to oci-based helmchart repo
  build/ks-apiserver/Dockerfile
  build/ks-controller-manager/Dockerfile
  pkg/controller/application/helm_repo_controller.go
  pkg/simple/client/application/helper.go
  pkg/simple/client/application/oci.go
  pkg/simple/client/application/oci_test.go
  pkg/simple/client/application/store.go
  pkg/simple/client/oci/errors.go
  pkg/simple/client/oci/oci_test.go
  pkg/simple/client/oci/registry.go
  pkg/simple/client/oci/url.go
  pkg/simple/client/oci/utils.go
Labels: kind/feature, ok-to-test, approved, lgtm, size/XL, release-note

#6207 adjust the log level of unexpected exceptions
  pkg/controller/openapi/openapi_controller.go
Labels: approved, size/XS, lgtm, kind/cleanup, release-note-none

#6209 fix: remove the incorrect RBAC rule merging logic
  pkg/componenthelper/auth/rbac/helper.go
  pkg/componenthelper/auth/rbac/policy_comparator.go
  pkg/controller/namespace/namespace_controller.go
  pkg/controller/namespace/namespace_controller_test.go
  pkg/controller/role/role_controller.go
Labels: kind/bug, approved, lgtm, size/S, release-note

#6212 Release v4.1.2
  config/ks-core/Chart.yaml
  config/ks-core/values.yaml
Labels: approved, size/XS, release-note-none

#6213 Update build-multiarch.yaml
  .github/workflows/build-multiarch.yaml
Labels: approved, size/M, release-note-none

#6214 fix: resolve the apprelease upgrade issue
  pkg/controller/application/apprelease_controller.go
  pkg/controller/application/executor.go
Labels: approved, lgtm
