Repository kubesphere/kubesphere, pull requests merged in 2024-10, with the labels that each got.

#6221 config/ks-core: fix the CronJob API version determination issue
  config/ks-core/templates/extension-museum.yaml
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#6220 Improve the readability of some codes
  pkg/controller/core/util.go
Labels: ok-to-test, approved, lgtm, size/M, kind/cleanup, release-note-none

#6223 Fix: `fatal error: fault` panic
  go.mod
  go.sum
  pkg/simple/client/es/query/query_test.go
  vendor/github.com/json-iterator/go/README.md
  vendor/github.com/json-iterator/go/go.mod
  vendor/github.com/json-iterator/go/go.sum
  vendor/github.com/json-iterator/go/iter_float.go
  vendor/github.com/json-iterator/go/iter_int.go
  vendor/github.com/json-iterator/go/reflect.go
  vendor/github.com/json-iterator/go/reflect_json_raw_message.go
  vendor/github.com/json-iterator/go/reflect_struct_decoder.go
  vendor/github.com/modern-go/reflect2/.travis.yml
  vendor/github.com/modern-go/reflect2/Gopkg.lock
  vendor/github.com/modern-go/reflect2/Gopkg.toml
  vendor/github.com/modern-go/reflect2/go.mod
  vendor/github.com/modern-go/reflect2/go_above_118.go
  vendor/github.com/modern-go/reflect2/go_above_17.go
  vendor/github.com/modern-go/reflect2/go_above_19.go
  vendor/github.com/modern-go/reflect2/go_below_118.go
  vendor/github.com/modern-go/reflect2/go_below_17.go
  vendor/github.com/modern-go/reflect2/go_below_19.go
  vendor/github.com/modern-go/reflect2/reflect2.go
  vendor/github.com/modern-go/reflect2/test.sh
  vendor/github.com/modern-go/reflect2/type_map.go
  vendor/github.com/modern-go/reflect2/unsafe_link.go
  vendor/github.com/modern-go/reflect2/unsafe_map.go
  vendor/modules.txt
Labels: kind/bug, ok-to-test, approved, lgtm, size/L, release-note-none

#6230 Update Chart.yaml
  config/ks-core/Chart.yaml
Labels: approved, size/XS, lgtm, release-note-none

#6234 [release 3.2] cherry pick #6223 to release 3.2
  go.mod
  go.sum
  pkg/simple/client/es/query/builder_test.go
  vendor/github.com/json-iterator/go/README.md
  vendor/github.com/json-iterator/go/go.mod
  vendor/github.com/json-iterator/go/go.sum
  vendor/github.com/json-iterator/go/iter_float.go
  vendor/github.com/json-iterator/go/iter_int.go
  vendor/github.com/json-iterator/go/reflect.go
  vendor/github.com/json-iterator/go/reflect_json_raw_message.go
  vendor/github.com/json-iterator/go/reflect_struct_decoder.go
  vendor/github.com/modern-go/reflect2/.travis.yml
  vendor/github.com/modern-go/reflect2/Gopkg.lock
  vendor/github.com/modern-go/reflect2/Gopkg.toml
  vendor/github.com/modern-go/reflect2/go.mod
  vendor/github.com/modern-go/reflect2/go_above_118.go
  vendor/github.com/modern-go/reflect2/go_above_17.go
  vendor/github.com/modern-go/reflect2/go_above_19.go
  vendor/github.com/modern-go/reflect2/go_below_118.go
  vendor/github.com/modern-go/reflect2/go_below_17.go
  vendor/github.com/modern-go/reflect2/go_below_19.go
  vendor/github.com/modern-go/reflect2/reflect2.go
  vendor/github.com/modern-go/reflect2/test.sh
  vendor/github.com/modern-go/reflect2/type_map.go
  vendor/github.com/modern-go/reflect2/unsafe_link.go
  vendor/github.com/modern-go/reflect2/unsafe_map.go
  vendor/modules.txt
Labels: kind/bug, ok-to-test, approved, lgtm, size/L, release-note-none

#6237 disable extensions-museum in member cluster
  config/ks-core/templates/extension-museum.yaml
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#6244 Refactor FormatVersion function to handle invalid characters
  pkg/controller/application/helm_repo_controller.go
  pkg/kapis/application/v2/handler_appversion.go
  pkg/simple/client/application/helper.go
  staging/src/kubesphere.io/utils/helm/executor.go
Labels: approved, lgtm, size/M, release-note-none

#6249 refactor: workspace cascading deletion logic
  pkg/constants/constants.go
  pkg/controller/namespace/namespace_controller.go
  pkg/controller/namespace/namespace_controller_test.go
  pkg/controller/workspace/workspace_controller.go
  pkg/controller/workspace/workspace_controller_test.go
  pkg/controller/workspacetemplate/workspacetemplate_controller.go
  pkg/models/tenant/tenant.go
Labels: kind/bug, approved, lgtm, size/L, release-note

#6250 correct and clarify potentially misleading terms in the license file
  LICENSE
Labels: approved, size/XS, lgtm, kind/documentation, release-note-none

#6253 fix: there is a serious privilege escalation vulnerability in the kubectl terminal tool
  pkg/apiserver/apiserver.go
  pkg/models/terminal/terminal.go
Labels: kind/bug, ok-to-test, approved, size/XS, lgtm, release-note

#6255 fix failing unit tests
  pkg/controller/namespace/namespace_controller_test.go
Labels: approved, lgtm, size/M, kind/failing-test, release-note-none

#6257 Allow version comparison errors
  pkg/simple/client/application/helper.go
Labels: approved, size/XS, lgtm, release-note-none

#6261 Fix conflict and cherry-pick (cherry-pick from #0e8c6d5)
  pkg/controller/application/apprelease_controller.go
  pkg/controller/application/cluster.go
  pkg/controller/application/delete_predicate.go
  pkg/controller/application/helm_repo_controller.go
  pkg/simple/client/application/helper.go
Labels: approved, lgtm, size/L, release-note-none
