Repository kubesphere/kubesphere, pull requests merged in 2024-12, with the labels that each got.

#6300 fix: make the prerelease version compatible
  pkg/utils/k8sutil/version.go
Labels: kind/bug, area/apiserver, approved, size/XS, lgtm, release-note-none

#6308 feat: Enhance JSBundle Api to declare auxiliary asset files required for extending components
  config/ks-core/charts/ks-crds/crds/extensions.kubesphere.io_jsbundles.yaml
  pkg/apiserver/filters/jsbundle.go
  pkg/controller/extension/jsbundle_webhook.go
  staging/src/kubesphere.io/api/extensions/v1alpha1/jsbundle_types.go
  staging/src/kubesphere.io/api/extensions/v1alpha1/zz_generated.deepcopy.go
Labels: kind/feature, ok-to-test, approved, lgtm, size/L, release-note

#6315 chore: add helm release namespace check
  config/ks-core/templates/kubesphere-config.yaml
Labels: approved, size/XS, lgtm, release-note-none

#6316 fix: incorrect redis config (#2130)
  config/ks-core/templates/redis.yaml
Labels: approved, lgtm, size/M, release-note-none

#6320 fix: support LDAPS && STARTTLS
  pkg/apiserver/authentication/identityprovider/ldap/ldap.go
Labels: approved, lgtm, size/M, release-note

#6323 clean up unnecessary warning logs
  pkg/controller/core/installplan_controller.go
Labels: approved, lgtm, size/M, kind/cleanup, release-note-none
