Repository kubesphere/kubesphere, pull requests merged in 2024-11, with the labels that each got.

#6262 fix: publishing bot run failed
  staging/publishing/rules.yaml
Labels: kind/bug, approved, lgtm, size/S, release-note

#6260 enhancement: disable redis when running as member cluster
  config/ks-core/templates/kubesphere-config.yaml
  config/ks-core/templates/redis.yaml
Labels: approved, size/XS, lgtm, tide/merge-method-merge, release-note

#6269 fix regression bug
  pkg/controller/namespace/namespace_controller.go
Labels: approved, lgtm, size/M, release-note-none

#6280 Support manual triggering of a repository update.
  config/ks-core/charts/ks-crds/crds/application.kubesphere.io_applicationreleases.yaml
  config/ks-core/charts/ks-crds/crds/application.kubesphere.io_repos.yaml
  config/ks-core/charts/ks-crds/crds/extensions.kubesphere.io_apiservices.yaml
  config/ks-core/charts/ks-crds/crds/extensions.kubesphere.io_extensionentries.yaml
  config/ks-core/charts/ks-crds/crds/extensions.kubesphere.io_jsbundles.yaml
  config/ks-core/charts/ks-crds/crds/extensions.kubesphere.io_reverseproxies.yaml
  config/ks-core/charts/ks-crds/crds/iam.kubesphere.io_builtinroles.yaml
  config/ks-core/charts/ks-crds/crds/iam.kubesphere.io_clusterroles.yaml
  config/ks-core/charts/ks-crds/crds/iam.kubesphere.io_globalroles.yaml
  config/ks-core/charts/ks-crds/crds/iam.kubesphere.io_roles.yaml
  config/ks-core/charts/ks-crds/crds/iam.kubesphere.io_roletemplates.yaml
  config/ks-core/charts/ks-crds/crds/iam.kubesphere.io_workspaceroles.yaml
  config/ks-core/charts/ks-crds/crds/kubesphere.io_extensions.yaml
  config/ks-core/charts/ks-crds/crds/kubesphere.io_extensionversions.yaml
  config/ks-core/charts/ks-crds/crds/kubesphere.io_installplans.yaml
  config/ks-core/charts/ks-crds/crds/kubesphere.io_serviceaccounts.yaml
  config/ks-core/charts/ks-crds/crds/quota.kubesphere.io_resourcequotas.yaml
  config/ks-core/charts/ks-crds/crds/tenant.kubesphere.io_workspacetemplates.yaml
  config/ks-core/templates/roletemplates.yaml
  pkg/apiserver/apiserver.go
  pkg/controller/application/helm_repo_controller.go
  pkg/kapis/application/v2/errors.go
  pkg/kapis/application/v2/handler_app.go
  pkg/kapis/application/v2/handler_apprls.go
  pkg/kapis/application/v2/handler_appversion.go
  pkg/kapis/application/v2/handler_category.go
  pkg/kapis/application/v2/handler_repo.go
  pkg/kapis/application/v2/operator.go
  pkg/kapis/application/v2/register.go
  pkg/kapis/application/v2/utils.go
  pkg/kapis/workloadtemplate/v1alpha1/handler.go
  pkg/kapis/workloadtemplate/v1alpha1/register.go
  pkg/simple/client/application/helper.go
  pkg/utils/k8sutil/k8sutil.go
  staging/src/kubesphere.io/api/application/v2/constants.go
  staging/src/kubesphere.io/api/application/v2/repo_types.go
  staging/src/kubesphere.io/api/application/v2/zz_generated.deepcopy.go
Labels: kind/feature, approved, lgtm, size/XL, release-note

#6285 update workloadtemplates RoleTemplate
  config/ks-core/templates/roletemplates.yaml
Labels: approved, size/XS, lgtm, release-note-none

#6288 fix: update license-eye version to v0.6.0
  hack/update-licenses.sh
  hack/verify-licenses.sh
  pkg/controller/application/delete_predicate.go
  pkg/controller/application/helm_repo_controller.go
  pkg/kapis/application/v2/handler_appversion.go
  pkg/kapis/workloadtemplate/v1alpha1/handler.go
  pkg/kapis/workloadtemplate/v1alpha1/register.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#6286 feat: create extensionVersions by depth
  config/ks-core/charts/ks-crds/crds/kubesphere.io_repositories.yaml
  pkg/controller/core/repository_controller.go
  pkg/controller/core/util.go
  pkg/controller/core/util_test.go
  staging/src/kubesphere.io/api/core/v1alpha1/constants.go
  staging/src/kubesphere.io/api/core/v1alpha1/repository_types.go
  staging/src/kubesphere.io/api/core/v1alpha1/zz_generated.deepcopy.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#6290 Replace vulnerable dependency gopkg.in/square/go-jose.v2
  LICENSES/LICENSE
  LICENSES/vendor/gopkg.in/square/go-jose.v2/LICENSE
  go.mod
  go.sum
  pkg/apiserver/authentication/identityprovider/oidc/oidc_test.go
  pkg/apiserver/authentication/token/issuer.go
  pkg/apiserver/authentication/token/issuer_test.go
  pkg/kapis/oauth/handler.go
  pkg/kapis/oauth/register.go
  vendor/golang.org/x/crypto/ed25519/ed25519.go
  vendor/gopkg.in/square/go-jose.v2/.gitcookies.sh.enc
  vendor/gopkg.in/square/go-jose.v2/.gitignore
  vendor/gopkg.in/square/go-jose.v2/.travis.yml
  vendor/gopkg.in/square/go-jose.v2/BUG-BOUNTY.md
  vendor/gopkg.in/square/go-jose.v2/CONTRIBUTING.md
  vendor/gopkg.in/square/go-jose.v2/LICENSE
  vendor/gopkg.in/square/go-jose.v2/README.md
  vendor/gopkg.in/square/go-jose.v2/asymmetric.go
  vendor/gopkg.in/square/go-jose.v2/cipher/cbc_hmac.go
  vendor/gopkg.in/square/go-jose.v2/cipher/concat_kdf.go
  vendor/gopkg.in/square/go-jose.v2/cipher/ecdh_es.go
  vendor/gopkg.in/square/go-jose.v2/cipher/key_wrap.go
  vendor/gopkg.in/square/go-jose.v2/crypter.go
  vendor/gopkg.in/square/go-jose.v2/doc.go
  vendor/gopkg.in/square/go-jose.v2/encoding.go
  vendor/gopkg.in/square/go-jose.v2/json/LICENSE
  vendor/gopkg.in/square/go-jose.v2/json/README.md
  vendor/gopkg.in/square/go-jose.v2/json/decode.go
  vendor/gopkg.in/square/go-jose.v2/json/encode.go
  vendor/gopkg.in/square/go-jose.v2/json/indent.go
  vendor/gopkg.in/square/go-jose.v2/json/scanner.go
  vendor/gopkg.in/square/go-jose.v2/json/stream.go
  vendor/gopkg.in/square/go-jose.v2/json/tags.go
  vendor/gopkg.in/square/go-jose.v2/jwe.go
  vendor/gopkg.in/square/go-jose.v2/jwk.go
  vendor/gopkg.in/square/go-jose.v2/jws.go
  vendor/gopkg.in/square/go-jose.v2/opaque.go
  vendor/gopkg.in/square/go-jose.v2/shared.go
  vendor/gopkg.in/square/go-jose.v2/signing.go
  vendor/gopkg.in/square/go-jose.v2/symmetric.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, release-note
