Repository kubesphere/kubesphere, pull requests merged in 2025-03, with the labels that each got.

#6385 fix: During the creation of a workspace, it will be determined whethe…
  pkg/models/tenant/tenant.go
Labels: approved, size/XS, lgtm, release-note

#6390 feature: reduce telemetry dependence
  LICENSES/vendor/github.com/robfig/cron/v3/LICENSE
  build/ks-controller-manager/Dockerfile
  cmd/controller-manager/app/options/options.go
  cmd/controller-manager/app/server.go
  config/ks-core/templates/kubesphere-config.yaml
  config/ks-core/templates/platformconfig-telemetry.yaml
  go.mod
  go.sum
  hack/verify-all.sh
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/constants/constants.go
  pkg/controller/options/options.go
  pkg/controller/telemetry/options.go
  pkg/controller/telemetry/runnable.go
  pkg/controller/telemetry/telemetry_controller.go
  pkg/controller/telemetry/telemetry_runnable.go
  vendor/github.com/robfig/cron/v3/.gitignore
  vendor/github.com/robfig/cron/v3/.travis.yml
  vendor/github.com/robfig/cron/v3/LICENSE
  vendor/github.com/robfig/cron/v3/README.md
  vendor/github.com/robfig/cron/v3/chain.go
  vendor/github.com/robfig/cron/v3/constantdelay.go
  vendor/github.com/robfig/cron/v3/cron.go
  vendor/github.com/robfig/cron/v3/doc.go
  vendor/github.com/robfig/cron/v3/logger.go
  vendor/github.com/robfig/cron/v3/option.go
  vendor/github.com/robfig/cron/v3/parser.go
  vendor/github.com/robfig/cron/v3/spec.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, release-note

#6391 feat: platform config API
  config/ks-core/templates/_helpers.tpl
  config/ks-core/templates/platformconfig-telemetry.yaml
  pkg/constants/constants.go
  pkg/controller/telemetry/options.go
  pkg/controller/telemetry/runnable.go
  pkg/controller/telemetry/telemetry_controller.go
  pkg/kapis/config/v1alpha2/handler.go
  pkg/kapis/config/v1alpha2/register.go
Labels: approved, lgtm, size/L, release-note

#6395 fix: replace user displayname with annotation
  pkg/kapis/iam/v1beta1/handler.go
Labels: approved, size/XS, lgtm, release-note

#6401 update ks-core helm chart
  config/ks-core/templates/NOTES.txt
  config/ks-core/templates/_helpers.tpl
  config/ks-core/templates/extension-categories.yaml
  config/ks-core/templates/extension-museum.yaml
  config/ks-core/templates/globalroles.yaml
  config/ks-core/templates/ks-agent.yaml
  config/ks-core/templates/ks-apiserver.yaml
  config/ks-core/templates/ks-console.yaml
  config/ks-core/templates/ks-controller-manager.yaml
  config/ks-core/templates/kubesphere-config.yaml
  config/ks-core/templates/oauthclient-config.yaml
  config/ks-core/templates/platformconfig-telemetry.yaml
  config/ks-core/templates/redis.yaml
  config/ks-core/templates/services.yaml
  config/ks-core/templates/webhook.yaml
  config/ks-core/templates/workspace.yaml
  config/ks-core/values.yaml
  pkg/controller/cluster/helper.go
Labels: approved, lgtm, size/M, release-note

#6407 update ks-core helm chart (#6401)
  config/ks-core/templates/NOTES.txt
  config/ks-core/templates/_helpers.tpl
  config/ks-core/templates/extension-categories.yaml
  config/ks-core/templates/extension-museum.yaml
  config/ks-core/templates/globalroles.yaml
  config/ks-core/templates/ks-agent.yaml
  config/ks-core/templates/ks-apiserver.yaml
  config/ks-core/templates/ks-console.yaml
  config/ks-core/templates/ks-controller-manager.yaml
  config/ks-core/templates/kubesphere-config.yaml
  config/ks-core/templates/oauthclient-config.yaml
  config/ks-core/templates/platformconfig-telemetry.yaml
  config/ks-core/templates/redis.yaml
  config/ks-core/templates/services.yaml
  config/ks-core/templates/webhook.yaml
  config/ks-core/templates/workspace.yaml
  config/ks-core/values.yaml
  pkg/controller/cluster/helper.go
Labels: approved, lgtm, size/M, release-note

#6419 fix: helm template error
  config/ks-core/templates/kubesphere-config.yaml
Labels: approved, lgtm

#6423 Update util.go
  pkg/controller/core/util.go
Labels: approved, lgtm

#6425 docs: update architecture image and social media link in README
  README.md
  README_zh.md
  docs/images/architecture.png
Labels: approved, lgtm, size/L, release-note-none

#6431 docs: update security policy and supported versions in SECURITY.md
  SECURITY.md
Labels: approved, size/M, release-note-none

#6432 fix: regression bugs
  pkg/controller/core/extension_controller.go
Labels: approved, size/XS, lgtm, release-note-none

#6438 deps: update go-jose to v4.0.5 (#6435)
  go.mod
  go.sum
  staging/src/kubesphere.io/api/go.mod
  staging/src/kubesphere.io/api/go.sum
  staging/src/kubesphere.io/client-go/go.sum
  staging/src/kubesphere.io/utils/go.mod
  staging/src/kubesphere.io/utils/go.sum
  vendor/github.com/go-jose/go-jose/v4/CHANGELOG.md
  vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/v4/README.md
  vendor/github.com/go-jose/go-jose/v4/crypter.go
  vendor/github.com/go-jose/go-jose/v4/jwe.go
  vendor/github.com/go-jose/go-jose/v4/jwk.go
  vendor/github.com/go-jose/go-jose/v4/jws.go
  vendor/github.com/go-jose/go-jose/v4/opaque.go
  vendor/github.com/go-jose/go-jose/v4/signing.go
  vendor/modules.txt
Labels: approved, lgtm, size/L, release-note-none

#6439 deps: update github.com/stretchr/testify to latest versions
  go.mod
  go.sum
  staging/src/kubesphere.io/api/go.mod
  staging/src/kubesphere.io/api/go.sum
  staging/src/kubesphere.io/client-go/go.mod
  staging/src/kubesphere.io/client-go/go.sum
  staging/src/kubesphere.io/utils/go.mod
  staging/src/kubesphere.io/utils/go.sum
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_custom.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_default.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_fail.go
  vendor/modules.txt
Labels: approved, lgtm, size/XL, release-note-none

#6441 chore: simplify telemetry config
  config/ks-core/templates/platformconfig-telemetry.yaml
Labels: approved, size/XS, lgtm, release-note-none

#6443 Update SECURITY.md
  SECURITY.md
Labels: approved, size/XS, lgtm, release-note-none

#6447 feat: add imagesearch provider
  cmd/ks-apiserver/app/options/options.go
  pkg/kapis/resources/v1alpha3/handler.go
  pkg/kapis/resources/v1alpha3/register.go
  pkg/models/registries/imagesearch/configuration.go
  pkg/models/registries/imagesearch/controller.go
  pkg/models/registries/imagesearch/dockerhub/provider.go
  pkg/models/registries/imagesearch/harbor/provider.go
  pkg/models/registries/imagesearch/registry_provider.go
Labels: approved, lgtm, size/XL, release-note

#6448 update pod status.Phase
  pkg/models/resources/v1alpha3/pod/pods.go
Labels: approved, size/XS, lgtm, release-note

#6457 chore: remove deprecated CronJob for restarting extensions museum
  config/ks-core/templates/extension-museum.yaml
Labels: approved, lgtm, size/S, release-note-none

#6456 Release 4.1.3-rc.0
  config/ks-core/Chart.yaml
  config/ks-core/values.yaml
Labels: approved, lgtm, size/M

#6460 deps: bump google.golang.org/protobuf to v1.35.2
  go.mod
  go.sum
  staging/src/kubesphere.io/api/go.mod
  staging/src/kubesphere.io/api/go.sum
  staging/src/kubesphere.io/client-go/go.mod
  staging/src/kubesphere.io/client-go/go.sum
  staging/src/kubesphere.io/utils/go.mod
  staging/src/kubesphere.io/utils/go.sum
  vendor/google.golang.org/protobuf/encoding/protojson/decode.go
  vendor/google.golang.org/protobuf/encoding/protojson/encode.go
  vendor/google.golang.org/protobuf/encoding/protojson/well_known_types.go
  vendor/google.golang.org/protobuf/internal/descopts/options.go
  vendor/google.golang.org/protobuf/internal/editiondefaults/editions_defaults.binpb
  vendor/google.golang.org/protobuf/internal/editionssupport/editions.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_init.go
  vendor/google.golang.org/protobuf/internal/filedesc/desc_lazy.go
  vendor/google.golang.org/protobuf/internal/filedesc/editions.go
  vendor/google.golang.org/protobuf/internal/genid/doc.go
  vendor/google.golang.org/protobuf/internal/genid/go_features_gen.go
  vendor/google.golang.org/protobuf/internal/genid/map_entry.go
  vendor/google.golang.org/protobuf/internal/genid/wrappers.go
  vendor/google.golang.org/protobuf/internal/impl/codec_extension.go
  vendor/google.golang.org/protobuf/internal/impl/codec_field.go
  vendor/google.golang.org/protobuf/internal/impl/codec_message.go
  vendor/google.golang.org/protobuf/internal/impl/codec_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/codec_unsafe.go
  vendor/google.golang.org/protobuf/internal/impl/convert.go
  vendor/google.golang.org/protobuf/internal/impl/encode.go
  vendor/google.golang.org/protobuf/internal/impl/equal.go
  vendor/google.golang.org/protobuf/internal/impl/legacy_extension.go
  vendor/google.golang.org/protobuf/internal/impl/message.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_reflect.go
  vendor/google.golang.org/protobuf/internal/impl/pointer_unsafe.go
  vendor/google.golang.org/protobuf/internal/strs/strings_pure.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go120.go
  vendor/google.golang.org/protobuf/internal/strs/strings_unsafe_go121.go
  vendor/google.golang.org/protobuf/internal/version/version.go
  vendor/google.golang.org/protobuf/proto/equal.go
  vendor/google.golang.org/protobuf/proto/extension.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc.go
  vendor/google.golang.org/protobuf/reflect/protodesc/desc_init.go
  vendor/google.golang.org/protobuf/reflect/protodesc/editions.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/methods.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_pure.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go120.go
  vendor/google.golang.org/protobuf/reflect/protoreflect/value_unsafe_go121.go
  vendor/google.golang.org/protobuf/runtime/protoiface/methods.go
  vendor/google.golang.org/protobuf/types/descriptorpb/descriptor.pb.go
  vendor/google.golang.org/protobuf/types/gofeaturespb/go_features.pb.go
  vendor/google.golang.org/protobuf/types/known/anypb/any.pb.go
  vendor/google.golang.org/protobuf/types/known/durationpb/duration.pb.go
  vendor/google.golang.org/protobuf/types/known/emptypb/empty.pb.go
  vendor/google.golang.org/protobuf/types/known/fieldmaskpb/field_mask.pb.go
  vendor/google.golang.org/protobuf/types/known/structpb/struct.pb.go
  vendor/google.golang.org/protobuf/types/known/timestamppb/timestamp.pb.go
  vendor/google.golang.org/protobuf/types/known/wrapperspb/wrappers.pb.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, release-note-none

#6459 Release v4.1.3
  config/ks-core/Chart.yaml
  config/ks-core/templates/extension-museum.yaml
  config/ks-core/values.yaml
Labels: approved, size/S, release-note-none

#6462 deps: remove unused dependency github.com/hashicorp/golang-lru
  LICENSES/vendor/github.com/hashicorp/golang-lru/LICENSE
  go.mod
  go.sum
  pkg/controller/quota/accessor.go
  vendor/github.com/hashicorp/golang-lru/.gitignore
  vendor/github.com/hashicorp/golang-lru/.golangci.yml
  vendor/github.com/hashicorp/golang-lru/2q.go
  vendor/github.com/hashicorp/golang-lru/LICENSE
  vendor/github.com/hashicorp/golang-lru/README.md
  vendor/github.com/hashicorp/golang-lru/arc.go
  vendor/github.com/hashicorp/golang-lru/doc.go
  vendor/github.com/hashicorp/golang-lru/lru.go
  vendor/github.com/hashicorp/golang-lru/simplelru/lru.go
  vendor/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/github.com/hashicorp/golang-lru/testing.go
  vendor/modules.txt
Labels: approved, size/XXL, lgtm, release-note-none

#6463 update extension-museum.yaml
  config/ks-core/templates/extension-museum.yaml
Labels: approved, lgtm
