Repository kubesphere/kubesphere, pull requests merged in 2025-04, with the labels that each got.

#6475 deps: bump github.com/golang-jwt/jwt/v4 to v4.5.2
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, release-note-none

#6473 feat: move ks-core agent installer to job
  pkg/controller/cluster/cluster_controller.go
  pkg/controller/cluster/helper.go
Labels: kind/feature, approved, lgtm, size/L, release-note-none

#6483 fix: add PersistentVolumeClaim definition to prepare upgrade job
  config/ks-core/Chart.yaml
  config/ks-core/templates/pre-upgrade-job.yaml
  config/ks-core/templates/prepare-upgrade-job.yaml
  config/ks-core/values.yaml
Labels: approved, size/M, release-note-none

#6474 feat: multicluster config API
  pkg/constants/constants.go
  pkg/kapis/config/v1alpha2/handler.go
  pkg/kapis/config/v1alpha2/register.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#6488 refactor: update ks-console-config.yaml use dynamic configuration values
  config/ks-core/templates/ks-console-config.yaml
  config/ks-core/values.yaml
Labels: approved, size/XS, release-note-none

#6491 fix slack links in readme
  README.md
  README_zh.md
Labels: kind/bug, approved, size/XS, lgtm, release-note
