Repository kubesphere/kubesphere, pull requests merged in 2025-02, with the labels that each got.

#6348 Fix OIDC logout redirect uri
  pkg/apiserver/authentication/identityprovider/oidc/oidc.go
  pkg/apiserver/authentication/identityprovider/oidc/oidc_test.go
Labels: approved, lgtm, size/S, release-note

#6352 fix: fix cve for telemetry and kubesphere
  build/ks-apiserver/Dockerfile
  build/ks-controller-manager/Dockerfile
  go.mod
  staging/src/kubesphere.io/api/go.mod
  staging/src/kubesphere.io/client-go/go.mod
  staging/src/kubesphere.io/utils/go.mod
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, size/S, release-note

#6370 fix: pod list with owner filter logic
  pkg/models/resources/v1alpha3/pod/pods.go
Labels: approved, lgtm, size/M, release-note

#6299 feat(auth): support multiple identity provider associations
  pkg/apiserver/authentication/identityprovider/configuration.go
  pkg/controller/user/user_controller.go
  pkg/kapis/iam/v1beta1/handler.go
  pkg/kapis/oauth/handler.go
  pkg/models/auth/authenticator.go
  pkg/models/auth/login_recoder.go
  pkg/models/auth/mapper.go
  pkg/models/auth/oauth.go
  pkg/models/auth/oauth_test.go
  pkg/models/auth/password.go
  pkg/models/auth/password_test.go
  staging/src/kubesphere.io/api/iam/v1beta1/constants.go
Labels: kind/feature, approved, lgtm, size/L, release-note

#6303 feat: platform config API (#2052)
  config/ks-core/templates/_helpers.tpl
  config/ks-core/templates/platformconfig-telemetry.yaml
  pkg/constants/constants.go
  pkg/controller/telemetry/options.go
  pkg/controller/telemetry/runnable.go
  pkg/controller/telemetry/telemetry_controller.go
  pkg/kapis/config/v1alpha2/handler.go
  pkg/kapis/config/v1alpha2/register.go
Labels: approved, lgtm, size/L, release-note-none

#6379 fix: Fixed the issue where the user status was empty when the third-p…
  pkg/controller/user/user_controller.go
Labels: approved, lgtm

#6377 feat: add category for deepseek
  config/ks-core/templates/extension-categories.yaml
Labels: kind/feature, approved, lgtm, size/S, release-note
